### ISSUE TITLE
Bug: P2CE Source mods not loading localisation files

### ISSUE THREAD

**Issue by lil-lemby** [ChaosInitiative/Portal-2-Community-Edition#1004]
### Describe the bug

P2CE Source mod fails to load / utilize localization files, resulting in chapter titles not showing up, etc. 
![image](https://user-images.githubusercontent.com/53302665/189178178-b58d27f7-fb2e-4b25-9777-6f380b5db2e1.png)

### Issue Map

Any, look towards maps that start with a chapter title

### To Reproduce

1. load any p2ce mod
2. look at where a localization file would be used
3. see it is not working properly

**Comment by pivotman319-owo** [comment]
this is caused by the lack of a (modname)_(language).txt file

![image](https://user-images.githubusercontent.com/15126754/200636494-29e8979b-bbec-4d3a-ac56-587d96fff167.png)
