### ISSUE TITLE
Bug: Funnels crash on Jolt

### ISSUE THREAD

**Issue by verygladen** [ChaosInitiative/Portal-2-Community-Edition#1011]
### Describe the bug

When using the new Jolt physics, trying to extend a Funnel with portals or turning on a disabled funnel crashes the game

### Issue Map

Any map with a Funnel or Bridge

### To Reproduce

1. Open a map with a Funnel 
2. Try to extend a Funnel with Portals
3. See game crash

**Comment by AnthonyPython** [comment]
I got this too

**Comment by JJL772** [comment]
This will be fixed in the next release

**Comment by ShygalCoco** [comment]
this issue has been fixed
