### ISSUE TITLE
Bug: Players cannot interact with Portals in Jolt Physics

### ISSUE THREAD

**Issue by verygladen** [ChaosInitiative/Portal-2-Community-Edition#1012]
### Describe the bug

When attempting to enter a Portal in Jolt Physics, the player cannot enter, however objects can.

### Issue Map

Any

### To Reproduce

1. Open a map
2. Place a pair of Portals
3. Attempt to enter a Portal
4. See that you cannot enter a Portal

**Comment by JJL772** [comment]
Superseded by #1019
