### ISSUE TITLE
Bug: Starting Elevators are bugged in Jolt

### ISSUE THREAD

**Issue by verygladen** [ChaosInitiative/Portal-2-Community-Edition#1013]
### Describe the bug

When you load up a chamber map, the starting elevator won't move.
![image](https://user-images.githubusercontent.com/37459940/189503728-d4666a95-1b2d-44f2-9088-8b8a9f8f3f40.png)

### Issue Map

Any map with Elevators

### To Reproduce

1. Open a map with an elevator
2. See elevator not move

**Comment by JJL772** [comment]
Superseded by #1019
