### ISSUE TITLE
Bug: Turrets don't deal damage in Volt (Vphysics Jolt)

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#1014]
### Describe the bug

Turrets don't deal damage in Volt (Vphysics Jolt)
you can condition them to damage you under very rare circumstances I haven't been able to reproduce.

### Issue Map

sp_a2_turret_intro

### To Reproduce

open sp_a2_turret_intro
walk in front of it.
take no damage.

**Comment by JJL772** [comment]
Superseded by #1019
