### ISSUE TITLE
Bug: npc_security_camera does not pop off the wall Volt (Vphysics Jolt)

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#1015]
### Describe the bug

npc_security_camera when a portal is shot behind it will normally pop off the wall with a small bit of momentum behind it. in Volt it does not do this.

### Issue Map

sp_a2_triple_laser

### To Reproduce

open sp_a2_triple_laser
shoot the camera and a wall.
watch it slide down instead of pop off.

**Comment by JJL772** [comment]
Superseded by #1019
