### ISSUE TITLE
Bug: Gel won't affect cubes if it's against dynamic prop. Volt (Vphysics Jolt)

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#1016]
### Describe the bug

Gel won't affect a cube (more specifically bounce gel) if the cube is against a dynamic prop. it may be more prop types but will not bounce off of prop_dynamic.

### Issue Map

sp_a3_crazy_box

### To Reproduce

open sp_a3_crazy_box
noclip to the second chamber.
get the cube covered in gel.
watch it sit there.

**Comment by JJL772** [comment]
Superseded by #1019
