### ISSUE TITLE
Bug: Gel has undefined behaviour around portals. volt (Vphysics Jolt)

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#1018]
### Describe the bug

Gel has undefined behaviour when attempting to interact with portals. sometimes stopping in mid air for a hot second before dropping down. other times just dropping into the portal but never going through. it seems to be random. in my previous tests with the GMod binaries I even had a gel blob stuck in mid air.

### Issue Map

sp_a3_crazy_box

### To Reproduce

open sp_a3_crazy_box
portal the gel.
observe.

**Comment by JJL772** [comment]
Superseded by #1019
