### ISSUE TITLE
Feature: prop_weighted_cube custom models

### ISSUE THREAD

**Issue by Doclic** [ChaosInitiative/Portal-2-Community-Edition#1024]
### Which component should be improved?

Entity

### Describe your suggestion

[prop_weighted_cube](https://developer.valvesoftware.com/wiki/Prop_weighted_cube) has a model string for cube type 6.
It works fine, it means that you can't have reflective cubes with custom models for example.
I think type 6 should be scrapped, and custom models should be usable for all cube types.

**Comment by Luke18033** [comment]
Duplicate of #311, my/TeamSpen's suggestion was to have `NewSkins 2` which makes it always use the model specified in the model keyvalue
