### ISSUE TITLE
Portal 2 Bug: Portal rendertargets do not work correctly on sp_a1_intro3

### ISSUE THREAD

**Issue by pivotman319-owo** [ChaosInitiative/Portal-2-Community-Edition#1027]
### Describe the bug

Portals will display a black render target surface in place of what the player sees when any portal is placed in the mural/portalgun pickup section of `sp_a1_intro3`.

### To Reproduce

1. Transition to/open `sp_a1_intro3`
2. Grab the portal gun/give weapon_portalgun
3. Attempt to place a portal on any surface before the next destroyed chamber

Repro video:
https://user-images.githubusercontent.com/15126754/190663792-f61e87bb-b83f-4a2e-a565-0eb269ac22bb.mp4

Build specifics (via `version` command):

```
Exe version 1.37.0.3 (p2ce)
[engine] Exe build: 09:18:26 Sep 12 2022 (8710) (440000)
[engine] Windows version 10.0
```

### Operating System

Windows 11 Insider Preview, v22H2 (10.0.22622.598 (ni_release_svc_prod2.220901-1704), amd64fre)

**Comment by PiMoNFeeD** [comment]
![image](https://user-images.githubusercontent.com/36343425/190689538-9a621b00-5ca1-4f8d-bbf6-e88f51a34a6f.png)
also it's not exclusive to this map

**Comment by JJL772** [comment]
These aren't rendertargets, I believe this is an issue with vis. If you set `r_novis` to 1, it looks fine. No idea why this is broken specifically in dx11, maybe related to clipping planes?
