### ISSUE TITLE
Bug: Entering and exiting vehicles while using a weapon not based off of BasePortalCombatWeapon does not draw weapon viewmodel again

### ISSUE THREAD

**Issue by pivotman319-owo** [ChaosInitiative/Portal-2-Community-Edition#1029]
### Describe the bug

As described above. The viewmodel will only reappear if the player switches to a different weapon, either via `use` or `phys_swap`.

### Issue Map

N/A

### To Reproduce

1. Spawn a vehicle (e.g.: jeep or airboat)
2. Give yourself an HL2 weapon and equip it
3. Enter and exit the vehicle

Repro video:
https://user-images.githubusercontent.com/15126754/190679431-8aa82b23-9b82-4e48-8504-027f8f8b6f57.mp4

### Operating System

Windows 11 Insider Preview, v22H2 (10.0.22622.598 (ni_release_svc_prod2.220901-1704), amd64fre)

**Comment by pivotman319-owo** [comment]
also happens if the phys_swap command is issued before the holster animation on the initial weapon finishes

**Comment by JJL772** [comment]
Will be fixed in next update. Weapon lowering code was HL2 only, but is now shared between hl2 and p2ce.

**Comment by tmob03** [comment]
Fixed in latest bsp-limits update
