### ISSUE TITLE
Bug: Destroying a weapon_striderbuster results in a crash

### ISSUE THREAD

**Issue by pivotman319-owo** [ChaosInitiative/Portal-2-Community-Edition#1034]
### Describe the bug

As described above.

### Issue Map

N/A

### To Reproduce

1. `ent_create weapon_striderbuster`
2. Damage it

Reproduction video:
https://user-images.githubusercontent.com/15126754/190866161-bfd79684-0976-4c4d-a58d-55449823b7ac.mp4

**Comment by JJL772** [comment]
This should be fixed in the steam build. If not, try again on Friday
