### ISSUE TITLE
Bug: Gel on the conveyor belt in sp_a4_finale3 doesn't affect the player

### ISSUE THREAD

**Issue by Evanpie711** [ChaosInitiative/Portal-2-Community-Edition#1037]
### Describe the bug

In sp_a4_finale3 the Convery docent speed me up move when covered in propulsion gel

### Issue Map

sp_a4_finale3

### To Reproduce

in sp_a4_finale3 go to the conveyor, cover it in propulsion gel, walk on conveyer with propulsion gel.

**Comment by Trico-Everfire** [comment]
This goes deeper, gel doesn't seem to function correctly on brush entities. I had a bug where bounce gel does not function on a rotating brush.

**Comment by pivotman319-owo** [comment]
seems to be fixed in latest nightly/QA/developer build
