### ISSUE TITLE
Feature: Portal gun ammo use + type CVar

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#1043]
### Which component should be improved?

Entity

### Describe your suggestion

This one requires some explanation, so let me give you the long version:

The weapon script for the portal gun has parameters for ammo type and clip size, both go unused as internally the code probably overwrites this to never need ammo, nor to reload. 
Having essentially a cvar to enable it to take these parameters (if changed from their default values) to allow limited portal gun fire usage.
A neat addition would be to have 2 new custom ammo types. Portal primary fire and portal secondary fire. allowing you to control what portals you have left. This'd allow for some pretty interesting tests to be developed around the concept of limited portal management and resource retrieval/management. It would also allow for potential custom game modes where limited portal gun usage requires you to resource manage.

**Comment by AWildErin** [comment]
We don't think this a good idea. A 4 person council has voted this is just not a good idea.
