### ISSUE TITLE
Bug: Physcannon applies very little impulse force when launching grabbed objects

### ISSUE THREAD

**Issue by pivotman319-owo** [ChaosInitiative/Portal-2-Community-Edition#1047]
### Describe the bug

Impulse force from the physcannon's primary fire applies correctly when an object is launched without being held. This force is significantly reduced when attempting to launch a held object, although properties such as health and exploding on impact still apply.

### Issue Map

N/A

### To Reproduce

1. Get a physcannon
2. Grab and throw some objects around

**Comment by AWildErin** [comment]
Duplicate of #573, it does extent to more objects than *just* the weighted cube, but the issue existed non the less

**Comment by AWildErin** [comment]
Gonna close this since it's a duplicate
