### ISSUE TITLE
Ability to render more than 4 portals at once.

### ISSUE THREAD

**Issue by donsimone** [ChaosInitiative/Portal-2-Community-Edition#105]
Hi! This would be very useful for a custom element like "world portals field" or on its own. 
Here is what I'm talking about:
![20180212221544_1](https://user-images.githubusercontent.com/67149686/85128211-23ae7980-b231-11ea-867f-ed6e30149bc5.jpg)
![20180212222122_1](https://user-images.githubusercontent.com/67149686/85128216-25783d00-b231-11ea-830a-516190181c47.jpg)

**Comment by anexistantperson** [comment]
use r_portal_fastpath 0, they could either automatically turn that off when theres an error or actually fix the problem but that command fixes the problem. it also fixes the edges of portals not scaling properly when resizing them, and allows you to higher the stencil depth command thing whatever it was without it being buggy, at the cost of some performance (but usually not enough to stop hitting the fps cap for good computers)

**Comment by donsomeone** [comment]
> use r_portal_fastpath 0, they could either automatically turn that off when theres an error or actually fix the problem but that command fixes the problem. it also fixes the edges of portals not scaling properly when resizing them, and allows you to higher the stencil depth command thing whatever it was without it being buggy, at the cost of some performance (but usually not enough to stop hitting the fps cap for good computers)

Thank you! Didn't know that.

**Comment by JJL772** [comment]
r_portal_fastpath is defaulted to 0 now
