### ISSUE TITLE
Bug: weapon_physcannon punts prop_weighted_cube with little force

### ISSUE THREAD

**Issue by Lifegivesmelemons** [ChaosInitiative/Portal-2-Community-Edition#1052]
### Describe the bug

When attempting to punt a cube, it launches with very little force.

### Issue Map

N/A

### To Reproduce

1. Open any map.
2. Give self weapon_physcannon.
3. Spawn prop_weighted_cube.
4. Pick up cube.
5. Attempt to punt cube.

**Comment by AWildErin** [comment]
Duplicate of #573
