### ISSUE TITLE
OS-specific files in shared depot

### ISSUE THREAD

**Issue by Doclic** [ChaosInitiative/Portal-2-Community-Edition#1053]
Some OS-specific files such as `p2ce_legacyui.sh`/`p2ce_legacyui.bat` are both in P2:CE's shared Steam depot, meaning that you'll download unnecessary files.
I think those files should be moved to their specific OS's depot, like `p2ce.sh`/`p2ce.bat` is.

Here are all the scripts I found in the shared depot:
| File          | OS       |
|--------------|-----------|
| `p2ce_legacyui.sh` | Linux |
| `p2ce_legacyui.bat` | Windows |
| `sdk_tools/install-hammer.sh` | Linux |
| `hammer/filters/add1x1.ico` | Windows |
| `hammer/filters/add3x3.ico` | Windows |
| `hammer/filters/add5x5.ico` | Windows |
| `hammer/filters/add7x7.ico` | Windows |
| `hammer/filters/add9x9.ico` | Windows |
| `hammer/filters/flat1x1.ico` | Windows |
| `hammer/filters/flat3x3.ico` | Windows |
| `hammer/filters/flat5x5.ico` | Windows |
| `hammer/filters/flat7x7.ico` | Windows |
| `hammer/filters/flat9x9.ico` | Windows |
| `hammer/filters/raiseto1x1.ico` | Windows |
| `hammer/filters/raiseto5x5.ico` | Windows |
| `hammer/filters/smooth3x3.ico` | Windows |
| `p2ce/resource/game.ico` | Windows |
| `platform/resource/game.ico` | Windows |

\+ maybe some others that I didn't find

**Comment by AWildErin** [comment]
the ico files are unlikely to get stripped for Linux builds. Hammer content is straight from our chaos-fgd repo and working out stripping windows files from that is just gonna be a complicated problem.

**Comment by Doclic** [comment]
What about the `game.ico` files?
Those aren't part of the fgd repo

**Comment by AWildErin** [comment]
I mean they can probably get stripped sure, we'd have to alter the upload scripts but I guess that'd be possible

**Comment by craftablescience** [comment]
convert_bik_to_webm.ps1 is a cross-platform PowerShell script

**Comment by craftablescience** [comment]
The other scripts in sdk_tools should be cross-platform too

**Comment by craftablescience** [comment]
It's pointless to care about `game.ico` being shipped when it's like half a megabyte at most (and that's being really generous)

**Comment by Doclic** [comment]
> convert_bik_to_webm.ps1 is a cross-platform PowerShell script

Oh I didn't know that there's a Linux PowerShell build

> It's pointless to care about `game.ico` being shipped when it's like half a megabyte at most (and that's being really generous)

I mean yeah, it's just 18kb, but I found it so I added it to the list

**Comment by JJL772** [comment]
Certain files are shared across depots for simplicity's sake and so linux users can easily run Hammer, HLMV, etc. in WINE. Unless a platform-specific file is relatively large, say 1mb+, we're not going to put them in their own depots. 

So to clarify, including Hammer files and windows binaries in the linux build is intentional *for now*, and it will not be the configuration the game ships with on release day. Scripts and .ico files are tiny, so we need not worry about shipping a few of them for the wrong platform.

I appreciate the issue though!
