### ISSUE TITLE
Bug: Models in editor glitching and turning red and black

### ISSUE THREAD

**Issue by theEthonic** [ChaosInitiative/Portal-2-Community-Edition#1062]
### Describe the bug

When using the P2CE hammer for my mod, All the models change red and black. This error does not happen when using normal p2ce, It only happens in mod
![image](https://user-images.githubusercontent.com/90005001/197053022-a1445f8a-3016-4d75-987b-7bccdade4234.png)
It might be a problem with my gameinfo.

### Issue Map

All Maps In the editor while using a mod

### To Reproduce

1. open hammer
2. look at 3d view
![image](https://user-images.githubusercontent.com/90005001/197052708-f52e6ff6-33a1-4df5-a534-40c434518098.png)

**Comment by theEthonic** [comment]
I have tried the default one that came with the p2ce mod template but I changed the game name

**Comment by ozxybox** [comment]
Is this still an issue?

**Comment by theEthonic** [comment]
No. I recently found out that a folder named platform that was in my sourcemods folder might have been causing the problem so I removed it and everything is fixed.

**Comment by ozxybox** [comment]
Makes sense, platform was getting mounted incorrectly until just recently. Thanks!
