### ISSUE TITLE
Workshop moderation

### ISSUE THREAD

**Issue by distributivgesetz** [ChaosInitiative/Portal-2-Community-Edition#108]
**The idea**
---
The workshop of Portal 2 is lacking ways of separating good maps or map series, from the notorious 12-minutes-of-effortless-work BEEMod maps™.
This is why any kind of moderation or system of workshop maps (e.g. "Preferred maps" picked every week, or just "Made in Hammer/PeTI/BEEMod" tags instead of the <put used test element here> tags) would be a nice to have.

**Comment by SpyceTewan** [comment]
I wouldn't want dev-picked favorite maps be promoted more. That's just not fair. More tags can be added though

**Comment by SpyceTewan** [comment]
Not related to the engine, will close this issue
