### ISSUE TITLE
Bug: Updating Beams causes a crash

### ISSUE THREAD

**Issue by tmob03** [ChaosInitiative/Portal-2-Community-Edition#1083]
### Describe the bug

In bsp-limits, going into a map with lasers and then attempting to move the laser with a cube will soon cause a crash.

Apparently related to DX11
![image](https://user-images.githubusercontent.com/33987871/206829474-c38b3870-c292-4ed6-9502-8341eb97590a.png)

EDIT: Also occurs with funnels shooting a portal to the portable surface on sp_a4_jump_polarity

### Issue Map

Any map with laser and cube

### To Reproduce

Go to sp_a2_triple_laser

Go pick up the reflection cube that spawns already intersecting a laser

Crash

### Operating System

Windows 10 Home 19044

**Comment by ozxybox** [comment]
Is this still an issue in the latest build?

**Comment by tmob03** [comment]
@ozxybox Nope! All good now :)
