### ISSUE TITLE
[bsp-limit build] Interacting with reflection cubes / schrödinger cubes and lasers crashes the game

### ISSUE THREAD

**Issue by LambdaCore21** [ChaosInitiative/Portal-2-Community-Edition#1089]
### Describe the bug

As soon as the laser hits reflection cubes / schrödinger cubes, the game crashes

### Issue Map

Any map with reflection cubes / schrödinger cubes

Any bsp format

### To Reproduce

1. Open Triple Laser
2. Try to play the map

**Comment by JJL772** [comment]
We've fixed this internally last night, keep an eye out for a new game build
