### ISSUE TITLE
[bsp-limit build] Laser is not visible at times (when interacting with reflection cubes / schrödinger cubes)

### ISSUE THREAD

**Issue by LambdaCore21** [ChaosInitiative/Portal-2-Community-Edition#1090]
### Describe the bug

Laser is not visible at times (when interacting with reflection cubes / schrödinger cubes

It is not related to DX9 or DX11

![grafik](https://user-images.githubusercontent.com/63379443/209232606-2c885b28-bad4-4ba6-a30c-cc7da40be784.png)

### Issue Map

For example Triple laser or double decker laser (workshop)

Every map with laser and cubes basically

### To Reproduce

Interact with reflection cubes / schrödinger cubes and lasers

**Comment by tmob03** [comment]
Duplicate of #1084
