### ISSUE TITLE
Steam Input nonfunctional in P2CE

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#1097]
Steam Input in P2CE is currently very broken:
- Before launching P2CE, the controller settings screen will appear as it does for games with no built-in Steam Input support - with no official layout, and no game actions.
- However, starting P2CE will cause the settings to seemingly be replaced by those of CS:GO.
	- An "official layout for P2CE" appears but is the same as the CS:GO bindings
	- The CS:GO game actions appear
	- Other controller layouts or templates get blanked on load and have CS:GO's action sets added. The action sets can be removed, but will reappear almost immediately.
	- All of this takes effect permanently until the next time Steam is restarted, even if P2CE is closed.
- Regardless of how any of this is configured, no actual inputs appear to ever be sent to the game, but controller icons do appear in menus so the game is detecting it.

All this testing was done with a Steam Controller, though I'd imagine other controllers will behave the same (including Steam Deck).

"Official Layout for P2CE":
![chaos_oBJeZts7R2](https://user-images.githubusercontent.com/19228201/210286618-2b8498d8-0920-47eb-b159-77aa0fa14750.png)

"Custom Portal2", my personal Portal 2 bindings, when loaded in P2CE:
![chaos_wYxFfRWoh8](https://user-images.githubusercontent.com/19228201/210286731-bda59032-ca90-4851-807b-c97cce8cdbff.png)

Game actions:
![image](https://user-images.githubusercontent.com/19228201/210286976-c86472ec-51c8-46e0-a7ab-60942feac8b7.png)

### What needs to be changed

It's hard for me to say exactly since I don't have access to the code or Steamworks, but here's what I can infer.
- Most of what needs to be done is just bringing stuff over from Portal 2:
	- Portal 2's game actions need to be supported, as well as its action sets, with one exception - the Puzzlemaker Controls set should be removed since we don't have that.
	- The controller section of VGUI settings should open the Steam Input config screen, instead of the in-game UI. (Somewhat pointless since we're dropping support for VGUI, but Portal 2 did it, might as well copy that over.)
	- Replace the crappy 2011 looking button icons with the modern ones pulled from Steam
- The inputs not being sent needs to be fixed, which might be because the proper action sets are missing
- The discrepancy between before/after launching needs to be fixed, probably need to configure something in Steamworks.
- P2CE has a few additional commands which should probably be exposed as game actions:
	- Swap paintgun/portalgun (`+alt1`)
	- Next paint (`nextpaint`)
	- Previous paint (`prevpaint`)
	- "Weapon extra (reload etc.)" (this is apparently what we call `+reload` in keyboard settings)
- Ideally workshop addons should be able to define their own actions, but I'm not sure how to best handle that, if Steam even allows the game actions list to be dynamically modified per-user like that.
- Whenever we get around to actually implementing our Pano UI, we should design it with controller support in mind. The controller settings tab should also open Steam Input settings like in VGUI.

**Comment by TeamSpen210** [comment]
The actions couldn't be modified per-level, but the best solution there would just be to define a bunch of generic `addon digital 1` etc inputs, then let addons detect those.

**Comment by Luke18033** [comment]
It wouldn't be per-map, custom addon actions would just show up in Steam Input as long as the addon was installed. But either way it probably wouldn't work because I think game actions have to be predefined through Steamworks, although JJ implied it might be possible.

**Comment by Luke18033** [comment]
Fixed
