### ISSUE TITLE
Contraption Cube

### ISSUE THREAD

**Issue by Coke-Unity** [ChaosInitiative/Portal-2-Community-Edition#1100]
### Which component should be improved?

Gameplay

### Describe your suggestion

The contraption cube is a type of cube only seen in Learning with Portals (Yes, Portal 2 was going to be in schools before it ultimately ended) where you can set the weight in kilometers to make it slower and faster as well as chose friction and bounce. The later 2 uses 5 presets however bounce can be made to be more like weight, and the friction also adds little pads onto the corner edges and the weight effects a weight ball in the center. There is also a light ring that does not have any functions but could be used to determine the bounce of the cube. There is also a button that goes with it that probably has the same settings but it’s for target, again with similar indicators but they make more sense for a button.
![BF9D2307-6686-42A7-B852-3B0060008EE5](https://user-images.githubusercontent.com/121594464/211276886-a1d5f8d6-6051-4fd5-a1e1-7a066be371b3.png) ![DE27C390-2B87-4666-A9FC-79BE35F41B3F](https://user-images.githubusercontent.com/121594464/211276892-206fc21e-fbc0-4aaf-ad8d-ef9acd8e6213.png)
Max weight, max bounce and no friction.

**Comment by AWildErin** [comment]
We've discussed this in the past, but we're not sure if we're going to implement these ourselves. We don't have the code nor are we sure if we can use the assets from it. If it'll be added, likely hood is it's going to be because a developer on the team wants to.

That said, we're implementing better scripting to allow users to make any kind of entity they want which means, when that is implemented, anybody can create this!

**Comment by Luke18033** [comment]
I don't see much reason to add this in code. Having played the educational version, it's not a very interesting mechanic, it's kind of neat for the first few minutes until you realize you can't actually think of any good gameplay uses for it that couldn't be replaced with normal cubes. Once we have our new scripting system in place it should be easy for other people to make a cube that can have its physical properties changed like this, as well as a corresponding button.

**Comment by Coke-Unity** [comment]
Oh ok, thank you for telling me this. I will probably try to recreate it in a way that can be used to solve puzzles by affecting its properties live, and then put it in the workshop for others. I just liked the idea and wanted others to experience it!
