### ISSUE TITLE
Bug: Overlays disappearing on building cubemaps

### ISSUE THREAD

**Issue by vikent8** [ChaosInitiative/Portal-2-Community-Edition#1108]
### Describe the bug

Overlays disappear after building cubemaps, whether they are on a envmapped texture or not. Doesn't affect decals.
![Снимок экрана 2023-01-12 115428](https://user-images.githubusercontent.com/4971070/212027569-9fef5f9b-99c5-4966-a63b-90db574c3709.png)
![Снимок экрана 2023-01-12 115408](https://user-images.githubusercontent.com/4971070/212027577-59c043e7-d303-4ce5-b3bd-a081a6c7a042.png)

### Issue Map

Occurs in custom maps

### To Reproduce

1. Open a custom map with overlays in it
2. Build cubemaps for the map

**Comment by Luke18033** [comment]
Does it fix after a game restart, or are they permanently gone from that map?
