### ISSUE TITLE
Bug: Model Z-Fighting in escape_02

### ISSUE THREAD

**Issue by tmob03** [ChaosInitiative/Portal-2-Community-Edition#1117]
### Describe the bug

In the turret battle in escape_02, when the turret fight starts, the doors Z-Fight with the surrounding brushes.

![image](https://user-images.githubusercontent.com/33987871/214080688-aa79a805-4a9e-4899-a133-0ef52ac7f919.png)

### Issue Map

escape_02

### To Reproduce

Open escape_02

Start the turret fight

Notice model Z-Fighting

### Operating System

Windows 10 Home 19045

**Comment by AWildErin** [comment]
This looks like it's using the portal 2 model, which would probably explain the z-fighting

**Comment by tmob03** [comment]
Damn I’m blind I didn’t realise it was the P2 Model at all

**Comment by ozxybox** [comment]
Closing this as it seems to be related to mounting order
