### ISSUE TITLE
p2ce_publish fails to update workshop maps.

### ISSUE THREAD

**Issue by Lifegivesmelemons** [ChaosInitiative/Portal-2-Community-Edition#1120]
### Describe the bug

Attempting to update maps with p2ce_publish will result in a error message. I've tried replacing the thumbnail and installing in a different directory, but it always fails to update.
![failmessage](https://user-images.githubusercontent.com/11589957/215196045-ff5bf0b9-3dbf-4dcc-9d96-7b8cf49374b0.PNG)

### Issue Map

p2ce_publish.exe

### To Reproduce

Use p2ce_publish to update a map.

**Comment by craftablescience** [comment]
p2ce_publish is unofficial and unsupported, we will be revamping the workshop soon making this tool and likely all existing workshop content obsolete
