### ISSUE TITLE
Bug: First portal in map occationally crashes P2CE.

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#1121]
### Describe the bug

When loading any map, there is a chance that placing the first portal will crash the game. It's random and can be difficult to reproduce, but does happen often enough to where I make this issue.

If it's not possible to reproduce, it may be after a map transition.

### Issue Map

any map in the portal 2 campaign.

### To Reproduce

1: open a map.
2: shoot a portal (for me I always shoot blue first)
3: game may crash.

### Operating System

Linux

**Comment by JJL772** [comment]
Use nightly, it should be fixed there

**Comment by Trico-Everfire** [comment]
Nightly or BSP_Limit?

**Comment by Trico-Everfire** [comment]
Because I am on bsp_limit

**Comment by Trico-Everfire** [comment]
Ignore that, P2CE reset my beta opt-in

**Comment by JJL772** [comment]
we retired (deleted) bsp-limits earlier this week, unfortunately steam decides to set you to default when that happens

**Comment by Trico-Everfire** [comment]
Makes sense.
