### ISSUE TITLE
Bug: Changing the color of a laser going through a Schrodinger's cube won't change the color of the output laser.

### ISSUE THREAD

**Issue by mthedoodler** [ChaosInitiative/Portal-2-Community-Edition#1142]
### Describe the bug

When:

-A laser is going through a Schrodinger's cube,
-and the color of that laser is changed,
-the laser coming out the other cube will not have its color changed as well.

### Issue Map

Occurs on the following map:

https://steamcommunity.com/sharedfiles/filedetails/?id=2716312871

### To Reproduce

1. Open map, which has a color-changing laser.
2. Place Schrodinger's cube in front of the laser.
3. Wait for the laser to change color.
4. Observe that the other cube's resulting laser's color has not changed with it.

![image](https://user-images.githubusercontent.com/108304734/215889435-19b8565a-af3c-4ec2-b414-6f2f62172803.png)

**Comment by DrPeeper228** [comment]
reapeat of #1098

**Comment by tmob03** [comment]
Repeat, as above says
