### ISSUE TITLE
Panorama Server Browser

### ISSUE THREAD

**Issue by betaRadiation** [ChaosInitiative/Portal-2-Community-Edition#1145]
### Which component should be improved?

Other

### Describe your suggestion

Add back the old vgui2 (or a panorama recreation) server browser so mods can have custom game modes and community servers.

**Comment by Luke18033** [comment]
For now, the plan is to use Steam's server browser (`View > Servers` in the Steam client) - you can filter it to P2CE servers, they won't actually appear currently but that should be fixed soon. Eventually there will be an in-game Panorama based server browser, which will likely be similar to the gmod one.
