### ISSUE TITLE
Option to suppress robot footsteps

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#115]
If your using the playermodel atlas or pbody, they have very loud footstep sounds. Normally in coop this isn't a huge deal as you're paying attention to your partner and the valve maps don't require too much walking. However in community coop maps or even singleplayer maps where you're using a robot player model, sometimes you'll be walking a long stretch or chamber with nothing but the clanging of robot feet. A simple option as either just a console variable or even an advanced option to suppress these specific sounds would make me happy.

**Comment by craftablescience** [comment]
The cvar is `sv_footsteps`, set it to 0
