### ISSUE TITLE
New Single Player model

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#116]
A robot like test subject, probably vague in gender, more humanoid in appearance than the coop robots. This model should allow for coop cosmetics to work with it. IE hats, skins, flags, etc.

**Comment by alpacca4** [comment]
I dont have anything to add expect that this is a greaat idea!

**Comment by Fennecai** [comment]
why not just chell? it's not like they are making a sequel to p2 or anything.

**Comment by JJL772** [comment]
Singleplayer model is not changing for the portal 2 campaign. For the p2ce campaign, we will be using robots, probably similar to the coop robots.
