### ISSUE TITLE
AI_disabled in "sp_a2_bts5"

### ISSUE THREAD

**Issue by ThatPlasma** [ChaosInitiative/Portal-2-Community-Edition#1167]
### Describe the bug

in "sp_a2_bts5" AI gets disabled stopping dialogue

unfortunately, I don't know if this soft locks it as I just re-enabled AI while playing

### To Reproduce

Open "sp_a2_bts5" 
You'll see a pop-up saying "AI_disabled"
no characters will talk or move
unless manually enabled

**Comment by AWildErin** [comment]
Thanks for confirming this still happens! I've been having a hard time trying to replicate this, unfortunately, it's a duplicate of #856
