### ISSUE TITLE
Bug: Level Transitions in Portal 1 Escape Sequence are broken.

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#1196]
### Describe the bug

The trigger_changelevel entities used to transition the maps` testchmb_a_15`, `escape_00`, `escape_01`, and `escape_02` sequentially are all broken, Luke18033 has pointed out to me this is because they are using the wrong spawnflag behaviour, which should be inverting Flag 1.

Video attached of a level transition failing to trigger:
https://cdn.discordapp.com/attachments/704919726052343848/1073575640671985734/2023-02-10_23-03-34.mp4

### Issue Map

`testchmb_a_15`, `escape_00`, and `escape_01`

### To Reproduce

1. Load up either of the 3 maps listed.
2. Go up to the end of the map where the the map should transition to the next.
3. The Level Transition should not work.

**Comment by Luke18033** [comment]
See #1002
