### ISSUE TITLE
Fix coop cosmetic item glitching

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#120]
I know specifically flags will sometimes break and get stuck somewhere in the level. I don't know how or when it happens though.

**Comment by FrozenDragon0** [comment]
Is the robot enrichment even available in this version? I don't think valve would give out the code or whatever in regards to the in-game store and it's items.

**Comment by Luke18033** [comment]
It doesn't appear to be, trying to go to it just softlocks the game on a black screen, though that could just be a bug. Either way, the code for rendering the cosmetics in-game is probably still present, and they were planning on implementing their own system anyway.

**Comment by SpyceTewan** [comment]
P2ce probably wont have cosmetics, or at least not the same
