### ISSUE TITLE
Bug: Light covers for Cool blue recessed lights are not rendering correctly

### ISSUE THREAD

**Issue by Equalizer5118** [ChaosInitiative/Portal-2-Community-Edition#1201]
### Describe the bug

I was making a custom entry for a level and I found that when I tested the cool blue 32x128 chamber light (instance path is: `instances/lights/light_panel_32x128_cool_med.vmf`) I found that the cover model does not render correctly. Images from P2:CE and Portal 2 are below:
Expected behaviour (Portal 2):
![Screenshot 2023-02-13 174627](https://user-images.githubusercontent.com/113145248/218641794-7be33526-82f0-4790-9e12-502ba3b840a4.png)

Existing behaviour (Portal 2: Community Edition):
![Screenshot 2023-02-13 174536](https://user-images.githubusercontent.com/113145248/218641897-e3787fdc-d6a6-4018-9535-43e4e24fa54f.png)

### Issue Map

Any map with the 32x128 cool blue panel light, but it is easily seen on sp_a2_triple_laser

### To Reproduce

1. Open sp_a2_triple_laser
2. Enter the chamber
3. look up and to the left
4. Observe bug

### Operating System

Tested on Windows 11

**Comment by JJL772** [comment]
I can't reproduce this on linux. What are your system specs?

**Comment by Luke18033** [comment]
It's fine for me on windows
![image](https://user-images.githubusercontent.com/19228201/218654054-bb8cab8a-259b-4646-b7e9-00f62694256f.png)

**Comment by vikent8** [comment]
I had  a similar issue with csgo content imported. I don't remember the exact material, but one of the materials from glass/ conflicts with just the skin 0 for lightcovers

**Comment by Equalizer5118** [comment]
Ok so it's a mounting issue? Cause I have all the pre-specified games in mounts.kv mounted, so maybe.

**Comment by Equalizer5118** [comment]
I'll try unmounting the games in my mounts.kv file when I get back to my computer

**Comment by Equalizer5118** [comment]
This is a mounting issue, closing this issue because it is not actually a p2ce issue.
