### ISSUE TITLE
Coop community map partner soundscripts missing

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#121]
Custom music and certain assets don't get loaded properly for a non-host player.

**Comment by distributivgesetz** [comment]
Elaborate, what assets exactly don't function?

**Comment by Konclan** [comment]
The issue seems to be that soundscripts are not being downloaded or maybe just loaded for the coop partner.

**Comment by Luke18033** [comment]
This was in reference to BEEmod/BEE2.4#912, which we ended up figuring out was because we didn't tell the joining client to reload their soundscripts, they're getting sent/loaded fine. It would probably be good to clean up custom soundscript loading in general but that should be a separate issue.
