### ISSUE TITLE
Coop loading forever

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#122]
Sometimes while queuing with a friend, the game will not load the custom map. It might be because it gets stuck downloading. If this happens and the partner leaves, the host will then be sent to a broken ui where they cannot do anything soft locking the game. This is usually fixed by the partner downloading the map before hand but its not guaranteed.

**Comment by anexistantperson** [comment]
i like to call this the "downloading test chamber softlock", i hate it. sometimes ill just try to wait it out and it can take up to 10 minutes. plz fix.

**Comment by ENDERZOMBI102** [comment]
Usually i taskkill p2 after that...
That happens like 4 times on 6

**Comment by JJL772** [comment]
coop loads now, but still broken in other ways
