### ISSUE TITLE
sv_portal_blue & sv_portal_orange

### ISSUE THREAD

**Issue by ACBob** [ChaosInitiative/Portal-2-Community-Edition#13]
I mean it just makes sense to remove the hard-coded part of portal colors, and deligate it to commands.
It'd make everything a whole lot easier.

**Comment by Luke18033** [comment]
Why are these `sv_`? Shouldn't they be client-side (the same way portal colors currently are)? There should also be Co-op versions of these, for both players. Ideally, if you customize your portal colors the person you're playing with should be able to see that.

**Comment by CitadelCore** [comment]
I'll add:
r_portal_player_primary_colour, r_portal_player_secondary_colour
r_portal_atlas_primary_colour, r_atlas_secondary_colour
r_portal_pbody_primary_colour, r_pbody_secondary_colour

Will also add this as an entity input/vscript function on the player entity, i.e. SetPortalPrimaryColour and SetPortalSecondaryColour.

**Comment by ACBob** [comment]
I added sv_ as i didin't really have any other ideas for the names, but what Citadel came up with seems good.

**Comment by SpyceTewan** [comment]
I would rather abstract `atlas` and `pbody` as `player1` or `player2`

**Comment by Fennecai** [comment]
in reply to spycetewan: i actually think pbody and atlas are better myself; cause then player1 cant be as easily confused to be the command for single player.

**Comment by SpyceTewan** [comment]
Might be easier to understand but multiplayer may not be limited to 2 players and involve the 2 robots

**Comment by Fennecai** [comment]
> Might be easier to understand but multiplayer may not be limited to 2 players and involve the 2 robots

well in that case; then it should all be one command like r_portal_primary_color [player] [rgb]

where you'd put a number in [player] and 0 is sp, 1 is atlas, 2 pbody, and so on for additional players
and rgb is ofc. the r,g, and b values of the desired color.

i'd think this to be a good solution so that multiple commands might be easier kept straight in the code. but i could be wrong; as my only programming experience has been in c# in unity. i havent worked with the Source engine's c++ before and have no clue what its like.

**Comment by SpyceTewan** [comment]
That was my thought, yes

**Comment by Luke18033** [comment]
I also said earlier that I wanted other players to be able to be able to see custom portal colors that you set. If that's done, it would make more sense to just have two sets of commands - `r_portal_sp_primary/secondary` and `r_portal_mp_primary/secobdary`. The former would be used for singleplayer, while the latter would control the portal colors fired by you and seen by other people in multiplayer.
