### ISSUE TITLE
Loading VCD files without Scenes.image

### ISSUE THREAD

**Issue by NoNameToPut** [ChaosInitiative/Portal-2-Community-Edition#131]
Custom voicelines. Don't know what else to write. Maybe allow using both scenes.image and raw VCD files

**Comment by Luke18033** [comment]
Why does Valve require them to be compiled into `scenes.image` anyway? Just speed I guess, since it only has to access one file? In that case I don't see why this would be a problem - it'd just be slightly slower, if anything.

**Comment by NoNameToPut** [comment]
I heard it's optimized for consoles. Which I don't think will be a problem since P2CE probably wont be ported to consoles

**Comment by Luke18033** [comment]
That would make sense.

**Comment by CitadelCore** [comment]
This is too big a change for too little reward and breaks backwards compatibility.

**Comment by Luke18033** [comment]
What do you mean it "breaks backwards compatibility"? The suggestion was to allow using raw VCD files in addition to `scenes.image`, they wouldn't replace it.

**Comment by Luke18033** [comment]
The VDC provides [example code](https://developer.valvesoftware.com/wiki/Scenes.image#Bypassing) to implement this for SDK 2013, which should be able to be ported to the CS:GO branch. Note that this code prioritizes loose scenes over those in `scenes.image`, which you might want to reverse.

**Comment by JJL772** [comment]
Implemented by demez recently, on steam build.
