### ISSUE TITLE
weapon_custom

### ISSUE THREAD

**Issue by DrMeepster** [ChaosInitiative/Portal-2-Community-Edition#132]
A blank weapon entity defined through key values and vscripts.

**Comment by Luke18033** [comment]
Weapons have script files that define what models they use, and what animations/sounds they play. The way I'd imagine this working is you would be able to specify a weapon script by keyvalue, which could be packed into the map or included with a mod. You'd then use VScript to give the weapon(s) functionality.

**Comment by JJL772** [comment]
We're going to be implementing this via the new scripting system (not vscript). Going to close this because it's vague and vscript-related
