### ISSUE TITLE
Player Momentum control through VScript

### ISSUE THREAD

**Issue by HugoBDesigner** [ChaosInitiative/Portal-2-Community-Edition#133]
Allow map-makers to have control over player momentum through VScript (and possibly some specific entity).
By that, I mean providing tools to define the direction and velocity of the player's momentum, as well as extract that information so that it can be used for other purposes.
Ideally, the player momentum's vector should be obtainable both as a vector aligned with relationship to the world and a vector aligned with relationship to player's view (to facilitate calculations).

**Comment by distributivgesetz** [comment]
Functions for setting the players velocity already exist, but its limited to being aligned with the world origin (CBaseEntity::GetVelocity(), CBaseEntity::SetVelocity()). Also, applying velocity to players on the ground doesn't work at all (?)

**Comment by JJL772** [comment]
As mentioned, we already have `SetVelocity`/`GetVelocity`. Considering `Momentum = m * v`, you can calculate it yourself (but you'll need to pick a mass for chell :P)
