### ISSUE TITLE
Portal Gun cube pick up animation

### ISSUE THREAD

**Issue by donsomeone** [ChaosInitiative/Portal-2-Community-Edition#142]
Be able to hide a portal gun with animation when picking up cubes. Valve also left sound files with very short pick up sound just like in the pre-release videos.

**Comment by distributivgesetz** [comment]
Why should this be added? You could just customize the view model animations.

**Comment by SpyceTewan** [comment]
I had a thought about using the portal gun pickup animation for heavy objects like cubes, turrets and chairs and the hl2 pickup animation for light objects like mugs, clipboards or file boxes.

Could add a cvar to use the weight system and another cvar to override the animation altogether

**Comment by Luke18033** [comment]
The hidden cvar `hide_gun_when_holding 1` will enable this behavior. It still uses the final sounds though, which should maybe be changed along with unhiding it by default.

**Comment by CitadelCore** [comment]
The cvar has been enabled, though I've renamed it to player_hide_gun_when_holding to be in-line with the other player grab controller cvars.
