### ISSUE TITLE
Setting to suppress weapon pickup sounds

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#143]
Remove the portal gun pickup sound when the player spawns with the portal gun

**Comment by SpyceTewan** [comment]
I can add an option to suppress pickup sounds of weapons

**Comment by SpyceTewan** [comment]
Added this as spawnflag 8. There's still a bug that the pickup sound is still always played when picking up a second portalgun, but since this feature is mainly used to disable the sound on map start, this shouldn't be a problem.
