### ISSUE TITLE
Fix broken model culling through portals when point_camera is active

### ISSUE THREAD

**Issue by distributivgesetz** [ChaosInitiative/Portal-2-Community-Edition#146]
If a `point_camera` is active, all models viewed through a portal will disappear and appear again.

Video demonstration by Sejievan over on VDC:
https://www.youtube.com/watch?v=oJCAPLYHHnM

**Comment by Luke18033** [comment]
I don't think this is actually caused by the `point_camera`. I have several cameras+monitors in my test map, and haven't been able to reproduce this. I *have* seen it happen in maps with leaks though.

**Comment by distributivgesetz** [comment]
Hmm, I'll try it for myself, see if I can get the bug to reproduce for myself

**Comment by distributivgesetz** [comment]
Yep, I've confirmed that this only occurs on maps that leak. This makes this issue kind of pointless though, since you won't be seeing this in final ships of maps, plus you will have to go out of your way to disable VVIS to even see this bug in action.

**Comment by Luke18033** [comment]
It could happen with an areaportal leak, which doesn't stop VVIS. Either way it's not really worth fixing.
