### ISSUE TITLE
Hammer Discord Rich Presence

### ISSUE THREAD

**Issue by LOVANG3L** [ChaosInitiative/Portal-2-Community-Edition#149]
Add Rich Presence to P2CE's Hammer (and P2CE itself if possible)

**Comment by ENDERZOMBI102** [comment]
This is semi duplicated

**Comment by LOVANG3L** [comment]
> This is semi duplicated, look at [#69](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/69)

Oh I didn't know, maybe just Hammer then?
