### ISSUE TITLE
Additional forms of UGC in the Workshop

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#15]
Add support for other types of user-generated content on the workshop other than just maps, these could include:
- Prefabs/Instances
- Scripts
- Assets (models, textures, etc.)

**Comment by CitadelCore** [comment]
Could just let users upload entire VPKs.

**Comment by JJL772** [comment]
We're going to be allowing entire VPKs to be uploaded to the workshop. Issue is obsolete
