### ISSUE TITLE
Differences in console variables between P2 and P2CE

### ISSUE THREAD

**Issue by Krzyhau** [ChaosInitiative/Portal-2-Community-Edition#153]
Several console variables have different default values, causing the game to control differently than Portal 2. Here are the ones that I found:
 - `sv_accelerate` is equal to 5.5, while it should be 10 (the default in the main game)
 - `zoom_sensitivity_ratio_mouse` - default value is 0.5 in P2, while here is 1.0
 - `sv_alternateticks` is 1 as default in P2 singleplayer. In P2CE, the default is 0, making some tricks impossible to execute. Setting it to 1 makes the game behave really weird (?)

**Comment by CitadelCore** [comment]
Fixed.
