### ISSUE TITLE
Visual nitpicking

### ISSUE THREAD

**Issue by Krzyhau** [ChaosInitiative/Portal-2-Community-Edition#154]
These issues most likely have different roots, but I've decided to put them into one list:
 - Portal gun recoil is too fast and too weak.
 - Angles for holding laser cube are incorrect. It's obvious when you get your hands on one.
 - Sound effects (mainly dialogues) are slightly pitched up.
 - You cannot see your model through portal.
 - Small technical nitpick, but in the main game your camera moves down really slowly when your pitch value is close to 0. This does not happen in P2CE.

**Comment by distributivgesetz** [comment]
These bugs are all different from eachother, so please open separate issues for these instead of putting them in one issue.
