### ISSUE TITLE
Saveloading breaks prop_floor_button

### ISSUE THREAD

**Issue by Krzyhau** [ChaosInitiative/Portal-2-Community-Edition#155]
Steps to reproduce:
1. Enter any level containing prop_floor_button (I tested it on sp_a1_intro2)
2. Make a save and load it.
3. After that, it should be impossible to press the button by standing on it.

**Comment by Luke18033** [comment]
I can't replicate this.

**Comment by Luke18033** [comment]
OH, is this an issue in P2CE itself?

**Comment by distributivgesetz** [comment]
> OH, is this an issue in P2CE itself?

Yes, Kryzhau is a playtester.

**Comment by Luke18033** [comment]
Ah, I didn't realize he had access.

**Comment by CitadelCore** [comment]
Should now be fixed.
