### ISSUE TITLE
Consistent crash in sp_a3_jump_intro

### ISSUE THREAD

**Issue by Krzyhau** [ChaosInitiative/Portal-2-Community-Edition#156]
Placing a pair of portals in the first section of the level seems to cause either a crash or freeze.
Having shader details set to low is required for this to happen for whatever reason.

**Comment by CitadelCore** [comment]
Does this still happen?

**Comment by Krzyhau** [comment]
I believe the issue is gone after portal rendering was fixed. Could not replicate it in the newest build.
