### ISSUE TITLE
Game runs at 64 tickrate instead of 60

### ISSUE THREAD

**Issue by betsruner** [ChaosInitiative/Portal-2-Community-Edition#157]
![dXw6s7XKGg](https://user-images.githubusercontent.com/55611319/86634840-fd5e3d00-bf97-11ea-9332-5e66633515f7.png)

**Comment by CitadelCore** [comment]
Why is this an issue?

**Comment by betsruner** [comment]
We had a thing in the speedrun community about this before. Raising the tickrate broke some elevators (they wouldn't start moving), made most moving objects do their movements faster, and changed what decimals were possible in CM. Although if you guys are gonna fix up stuff like that might as well fix it up for 100 instead of 64 so the CM timer gets all the times possible. Would probably just be easier to have it at 60 though.

**Comment by CitadelCore** [comment]
Set back to 60.
