### ISSUE TITLE
Cvar to put away the Portal Gun when holding cubes

### ISSUE THREAD

**Issue by creative-collective** [ChaosInitiative/Portal-2-Community-Edition#166]
In Portal 2's prerelease, you would put away the Portal Gun when picking up an object. It would hide from the UI and either sounds/player/object_use_01 or the HL2 pick up sound would play.
Could this be re-implemented as an optional feature?

**Comment by Luke18033** [comment]
I'm pretty sure I found a hidden cvar at one point that enables this. Can't remember what it was called though.

**Comment by Luke18033** [comment]
Okay, it's literally just `hide_gun_when_holding`. It still uses the final sounds though, which should maybe be changed.

**Comment by distributivgesetz** [comment]
Duplicate of #142 
@Luke18033 could you share your findings in that issue again so it isn't lost?

**Comment by distributivgesetz** [comment]
@Luke18033 can you share your findings in that issue so it doesn't go lost?
