### ISSUE TITLE
point_posecontrollers slowly "drift" in one direction

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#170]
In my test map, I have a camera (a `prop_dynamic_override`) that is aimed in a specific direction using two `point_posecontrollers`. In Portal 2, this works fine; the camera begins pointed in the correct direction and stays there:
![portal2_Dto3TVKhYi](https://user-images.githubusercontent.com/19228201/87259370-b83a7f00-c45f-11ea-888d-3fd0b4b451f5.png)
When the same map is loaded in P2CE, the camera also begins pointed in the correct direction. However, it begins to slowly "drift" off to the side, eventually facing completely backwards:
![chaos_xuYcqpLjgK](https://user-images.githubusercontent.com/19228201/87259376-be306000-c45f-11ea-82cb-19324b648358.png)
![chaos_oxmMjCtG8e](https://user-images.githubusercontent.com/19228201/87259379-bf618d00-c45f-11ea-9903-b9b6b6f6fab9.png)
Further testing revealed that this is indeed caused by the posecontroller, as it happens with other models as well. Firing a `SetPoseValue` input will move the prop to the specified pose, but the drifting will continue. [Here](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/4909922/pointable_camera.txt) is a copy of the camera instance used, if it's of any help.

**Comment by CitadelCore** [comment]
Fixed. More floating point precision issues...
