### ISSUE TITLE
Lasers do not display end particles until redirected

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#171]
Immediately after turning on a laser (by input or at the start of the map), the end spark particles will not appear:
![chaos_710xa4qOWb](https://user-images.githubusercontent.com/19228201/87259952-b377ca00-c463-11ea-9bf8-1b095082e2a1.png)
After redirecting the laser using a cube or portals, the particles will appear correctly:
![chaos_8dwonSAXvC](https://user-images.githubusercontent.com/19228201/87259972-cd191180-c463-11ea-8e58-61aa0f53d83f.png)
Turning the laser off and on again resets this.

**Comment by CitadelCore** [comment]
I can't replicate this. What map did you test it on?

**Comment by distributivgesetz** [comment]
I was able to replicate, maybe the first loading of laser particles is inconsistent?

**Comment by Luke18033** [comment]
That's `sp_a2_dual_lasers`.

**Comment by CitadelCore** [comment]
Appears to now be fixed.
