### ISSUE TITLE
VGUI screens extend downward instead of upward

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#172]
All VGUI screen entities (including `vgui_screen` itself and `prop_indicator_panel`) extend downwards from the bottom-left corner, instead of upwards. In existing maps, this results in them appearing directly below their intended locations.
![chaos_q9kN9fIFem](https://user-images.githubusercontent.com/19228201/87260330-31d56b80-c466-11ea-9f19-5ba2423ccda4.png)
![chaos_FsiDsmkxks](https://user-images.githubusercontent.com/19228201/87260333-326e0200-c466-11ea-8e73-85c5c077e628.png)

**Comment by SpyceTewan** [comment]
Finally someone could tell me if chamber signs work or not..

**Comment by CitadelCore** [comment]
Fixed.

**Comment by SpyceTewan** [comment]
Bounding box checked for visibility or whatever still points downwards. Go fix it already or I eat you  https://www.youtube.com/watch?v=FJqFd80q88w

**Comment by CitadelCore** [comment]
Fixed for real this time!
