### ISSUE TITLE
Reflection cube rotation is buggy

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#173]
When looking upward, the cube tilts downward, and vice-versa. In the original game, it always stays flat. The cube's Z axis rotation also seems to get stuck sometimes, instead of matching your view angle. When viewmodel grabbing is enabled (in Co-op or with the cvar), the laser is reflected normally, though the cube will visually tilt left and right when turning.

**Comment by Luke18033** [comment]
Okay, the cube in `sphere_peek` has now started consistently snapping to this angle:
![image](https://user-images.githubusercontent.com/19228201/87262640-8f21ea80-c46f-11ea-8b2d-c183b51bb52c.png)
I have no idea what I did to cause this, though it was partially fixed by spawning a new cube.

**Comment by Luke18033** [comment]
The frankenturret in `sp_a4_tb_intro` also got stuck like this:
![image](https://user-images.githubusercontent.com/19228201/87382101-04aeb900-c54b-11ea-88b3-2768304f17e2.png)
It seems like carry angles are just broken in general, you should probably try and figure that out.

**Comment by CitadelCore** [comment]
Fixed.
