### ISSUE TITLE
Crouching does not slow down player, sometimes gets stuck

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#174]
When the player crouches, they will not be slowed down like they are in the original game. They can also sometimes get stuck crouching (even when the key is released and there's room), but I'm not sure exactly what causes this.

**Comment by OssyFlawol** [comment]
Crouching on props seems to cause some issues, that might be related to getting stuck.

**Comment by Luke18033** [comment]
Crouching on or near props does seem to cause it, yeah.

**Comment by CitadelCore** [comment]
Fixed
