### ISSUE TITLE
Voice lines are slightly pitched up

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#175]
All voice lines are slightly pitched up compared to the original game. This is especially noticeable with GLaDOS lines or the Announcer's smooth jazz, but is present for all characters. Other sounds are played at the correct pitch.

**Comment by Luke18033** [comment]
Still an issue

**Comment by CitadelCore** [comment]
I think this should be fixed now but I'm not 100% sure, let me know if it persists
