### ISSUE TITLE
Chapter titles are missing

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#178]
Not sure if you intend to fix this since you're doing a custom campaign, but I figured I'd open an issue for it anyway.
![image](https://user-images.githubusercontent.com/19228201/87262383-9ac0e180-c46e-11ea-9a13-fa012ffe6d93.png)

**Comment by CitadelCore** [comment]
This is already fixed on our internal branch.
