### ISSUE TITLE
Held turret rotation is buggy

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#181]
In the original game, looking down while holding a turret would cause it to rotate to sit flat on the floor. This does not happen in P2CE, making it nearly impossible to set turrets upright.
![image](https://user-images.githubusercontent.com/19228201/87265418-a533a900-c477-11ea-8100-cca06534bc9e.png)
On a related note, the phong on the turret texture seems different...

**Comment by CitadelCore** [comment]
The phong is to be expected, P2CE uses updated shaders from CS:GO. Otherwise, this is a bug.

**Comment by Luke18033** [comment]
Defective turrets have completely broken hold angles...
![image](https://user-images.githubusercontent.com/19228201/87275103-4a5b7b00-c492-11ea-96bf-be2b131f6228.png)

**Comment by CitadelCore** [comment]
Fixed.
