### ISSUE TITLE
Most subtitles are the wrong colors

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#182]
In Portal 2, turret subtitles are red:
![image](https://user-images.githubusercontent.com/19228201/87266531-5cc9ba80-c47a-11ea-924c-fba5060a28ea.png)
In P2CE, they're instead green:
![chaos_U3CpTdFFwJ](https://user-images.githubusercontent.com/19228201/87266538-5fc4ab00-c47a-11ea-8a68-d54d16c1d2b1.png)
This is a pretty minor thing that doesn't really matter, but it was bugging me. I'm not sure why it would have even been different in the first place. ~Maybe someone was trying to make Adhesion Gel green, and accidentally recolored these instead?~

**Comment by OssyFlawol** [comment]
Theres also similar cases of colour difference in other character dialogue such as Cave Johnson.

**Comment by SpyceTewan** [comment]
I'm really curious how that happened

**Comment by CitadelCore** [comment]
This is probably due to the differences in friend/enemy team types in CS:GO.

**Comment by CitadelCore** [comment]
Fixed. The colour map was being loaded from the wrong location.
