### ISSUE TITLE
Water overlay does not reset when reloading a save

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#183]
When the player goes in water (goo), a refractive water overlay is applied to the screen. However, if a save is reloaded while in the water, the overlay will remain on-screen for a few seconds. This is especially bad for Goo in particular, since it kills the player (and reloads a save) the moment they enter it.

**Comment by CitadelCore** [comment]
This is disabled by default in Portal 2. I've disabled it by default in P2CE too.

**Comment by Luke18033** [comment]
Still enabled by default in the latest build
