### ISSUE TITLE
Audio sometimes mutes randomly

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#185]
I'm not sure exactly what causes it, but sometimes during gameplay all audio will just fade out. It fades back in a few seconds later.

**Comment by Luke18033** [comment]
I haven't had this happen in a while, might be fixed?

**Comment by CitadelCore** [comment]
Closing as fixed, I haven't experienced this either.

**Comment by SpyceTewan** [comment]
No this is not fixed

**Comment by SpyceTewan** [comment]
Little thing i found:

When it happens, snd_show still shows the full list of sounds
Tabbing in and out of the game can cause it (Unconfirmed, it's still random)

**Comment by JJL772** [comment]
Fixed, finally.
