### ISSUE TITLE
sp_a2_core: Wheatley spawns from the wrong place

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#186]
In `sp_a2_core`, when GLaDOS lowers down the neurotoxin tube, Wheatley can be heard in the tube but does not appear. Instead, he'll fall to the ground on the other side of the room a few seconds after the glass breaks. When picked up, he is rotated sideways:
![image](https://user-images.githubusercontent.com/19228201/87276136-8db6e900-c494-11ea-8efc-23ca2ac1ed76.png)
If viewmodel grabbing is enabled using the cvar (which amazingly didn't get hidden), he is rotated correctly.

**Comment by CitadelCore** [comment]
Fixed. In CS:GO, path_tracks are server only, which means parenting them fails. I reverted this change.
