### ISSUE TITLE
showtriggers does not render correctly

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#187]
The triggers appear to be black, with the orange color only appearing where projected textures (?) hit the brush.
![image](https://user-images.githubusercontent.com/19228201/87276478-44b36480-c495-11ea-8cdc-e44cf5b04b12.png)

**Comment by SpyceTewan** [comment]
I see this as a minor issue. It still renders, it's just different

**Comment by Luke18033** [comment]
I guess it could just be different rendering, though they can be difficult to see in darker areas.

**Comment by Luke18033** [comment]
Seems to no longer happen
![image](https://user-images.githubusercontent.com/19228201/93152110-ab7e1580-f6b2-11ea-987e-76d6eeb4bc56.png)
