### ISSUE TITLE
sp_a2_bts5: Moving panels are rotated wrong

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#188]
The title says it all
![chaos_d7dvpFBmBc](https://user-images.githubusercontent.com/19228201/87277006-4f222e00-c496-11ea-9e9a-f5a0a043c21b.jpg)
![image](https://user-images.githubusercontent.com/19228201/87277013-50ebf180-c496-11ea-8477-2611efbf4f8a.png)

**Comment by CitadelCore** [comment]
Fixed.

There were two issues at play here:
- sv_phys_props_block_movers was set to 0
- tracktrain angles were not being set correctly due to angular velocity being clamped; I have increased the maximum angular velocity from 3600 to 14400 which is sufficient to handle most scenarios.
