### ISSUE TITLE
Some cvars are incorrectly set as dev-only

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#189]
I already reported this on Discord, though there are a few more that I have bound to keys, or otherwise change mid-game:
```
r_portal_use_dlights
r_waterforcereflectentities
gl_clear
r_portal_fastpath
speed_paint_color
bounce_paint_color
portal_paint_color
cl_portal_cleanser_scanline
ui_transition_effect
ui_loadingscreen_fadein_time
ui_loadingscreen_transition_time
ui_loadingscreen_mintransition_tme"
r_paintblob_otherviews_highres
hud_saytext_time
mp_dev_wait_for_other_player
sv_player_funnel_into_portals
stick_paint_color
reflect_paint_color
erase_paint_color
sv_allow_mobile_portals
joy_remap_player_for_controller1
mat_picmip
r_WaterDrawReflection
r_WaterDrawRefraction
mat_wateroverlaysize
r_lod
mat_diffuse
mat_bumpmap
r_shadows
mat_forceaniso
mat_forcehardwaresync
mat_reducefillrate
mat_mipmaptextures
mat_filtertextures
mat_envmapsize
mat_envmaptgasize
mat_antialias
mat_filterlightmaps
ss_force_primary_fullscreen
map_wants_save_disable
```
Mobile portals are required for the neurotoxin generator map, making it impossible with this bug. `map_wants_save_disable` is also used to disable saving during certain sequences, but isn't necessary for gameplay.

**Comment by Luke18033** [comment]
Added `r_skybox_draw_last`

**Comment by Luke18033** [comment]
Added `joy_remap_player_for_controller1`

**Comment by Luke18033** [comment]
Removed `r_skybox_draw_last`, it doesn't seem to be necessary anymore and might have been removed.

**Comment by Konclan** [comment]
Here are more commands:
```
mat_picmip
r_WaterDrawReflection
r_WaterDrawRefraction
mat_wateroverlaysize
r_lod
mat_diffuse
mat_bumpmap
r_shadows
mat_forceaniso
mat_forcehardwaresync
mat_reducefillrate
mat_mipmaptextures
mat_filtertextures
mat_envmapsize
mat_envmaptgasize
mat_antialias
mat_filterlightmaps
```

**Comment by Luke18033** [comment]
I noticed you were able to change `mat_picmip` in your screenshot on Discord, did you find a way to unhide them? The plugin didn't work for me.

**Comment by Konclan** [comment]
I think that was mat_showlowresimage

**Comment by Luke18033** [comment]
Added `ss_force_primary_fullscreen`

**Comment by Luke18033** [comment]
Added `map_wants_save_disable`

**Comment by CitadelCore** [comment]
Should all be fixed now. Please re-open this if there are still issues with this in the next build.
