### ISSUE TITLE
sp_a3_speed_ramp: Ramp does not function correctly

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#192]
When activated, the ramp will fully extend before immediately retracting again.
![p2ce_speed_ramp_opt](https://user-images.githubusercontent.com/19228201/87348336-664e3380-c509-11ea-8c9d-9007a2ad49ba.png)
Activating the ramp using `ent_fire` will also cause it to immediately retract.

**Comment by Luke18033** [comment]
This seems to be caused by the ramp having a reset time of 0 seconds - apparently P2 treats that as "never reset", but P2CE/CS:GO treats it as "reset instantly".

**Comment by Luke18033** [comment]
This is also a problem with the rotating panel in `sp_a3_speed_flings`

**Comment by SpyceTewan** [comment]
I think we should retain portal 2's functionality in this case for backwards compatibility

**Comment by CitadelCore** [comment]
Fixed. This was actually caused by the cvar sv_phys_props_block_movers being set to 0.
