### ISSUE TITLE
Cvars for remapping controllers don't exist

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#194]
Specifically joy_remap_player_for_controller1 is an unknown command in P2CE.

**Comment by distributivgesetz** [comment]
Pretty random issue, but still relevant in some way

**Comment by Konclan** [comment]
Its required to do local coop if you don't have 2 controllers

**Comment by Luke18033** [comment]
See #189, it probably got set as dev-only.

**Comment by CitadelCore** [comment]
Support for this was removed for some reason in CS:GO. I've re-implemented it.
