### ISSUE TITLE
Going noclip while on blue gel makes fly speed a crawl

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#195]
Happens in sp_a3_crazy_box, probably happens everywhere.

**Comment by Konclan** [comment]
Nvm I have no idea why I'm slow

**Comment by Konclan** [comment]
Ah, there is a +speed command in P2CE which is probably CS:GO's shift key which makes you walk slower. I have my own command which is the same thing that is supposed to host timescale but is being overwritten. I typed +speed in console making flying in noclip super slow.

**Comment by Luke18033** [comment]
You should probably change that to something like `+fast` so it doesn't conflict, I did that a while ago. (My autoexec is actually based on a version of yours which you posted way back on NPH)
