### ISSUE TITLE
trigger_paint_cleanser ignores flags

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#197]
When the player passes through a `trigger_paint_cleanser`, their paint types will be cleared regardless of whether the Clients flag is checked on the trigger. Physics objects will also always be cleaned on contact. This should not happen when the flags are unchecked, as is the case with `trigger_portal_cleanser`.

**Comment by TeamSpen210** [comment]
Note this happens in vanilla Portal 2. Additionally physics objects are also cleaned regardless of flags/filters. Ideally it should have toggles for these behaviours.

**Comment by CitadelCore** [comment]
Fixed.

**Comment by Luke18033** [comment]
Right after I added this bug to the VDC page.
