### ISSUE TITLE
mat_wireframe causes crashes

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#198]
When `mat_wireframe` is turned on, the game tends to crash randomly. I haven't found anything in particular that causes it, but usually just moving around and loading/unloading different parts of the map can trigger the crash.

**Comment by Luke18033** [comment]
[Here's the mdmp.](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/4916109/mdump.zip) These things are huge, I had to put it in a ZIP to get it down to a size GitHub would allow.

**Comment by SpyceTewan** [comment]
I'm guessing this is a memory overflow as it happens when rendering large amounts of items

**Comment by CitadelCore** [comment]
I can't reproduce this.

**Comment by Luke18033** [comment]
It first happened in `sp_a1_intro5` when passing through the entrance door, and later in my testmap when passing through a...OH, is this caused by passing through areaportals with it on?

**Comment by Luke18033** [comment]
I was able to reproduce both crashes just now, in the exact same places.

**Comment by Luke18033** [comment]
Passing through a Portal portal also appears to cause the crash.

**Comment by CitadelCore** [comment]
Fixed (I think).
