### ISSUE TITLE
trigger_look does not work

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#199]
If the player goes into the observation room where the portrait of Caroline is found, no voice lines will play, and the Portrait of a Lady achievement will not be given (as indicated by the lack of a `stats and achievements disabled` message when cheats are on). A `trigger_look` is used to activate this - perhaps that entity is broken?

**Comment by Luke18033** [comment]
`trigger_look` does not appear to work, as indicated by these panels in my old test map:
![image](https://user-images.githubusercontent.com/19228201/87826316-88a7c000-c82d-11ea-8010-0165f7ddb343.png)

**Comment by SpyceTewan** [comment]
The trigger_looks in sp_a1_intro1 do work. Can you test this again?

**Comment by Luke18033** [comment]
You mean the ones used for "look up at the ceiling, look down at the floor"? Those are `ai_script_conditions` I'm pretty sure.

**Comment by Luke18033** [comment]
I checked the map. Those aren't `trigger_look`s , but there are a couple others (which I'd assume are the ones you were talking about). The one to turn on the chamber sign doesn't work, but it has an invalid target entity set so I'm not sure if it did to begin with. The one to activate the cube dropper *does* work, however. Odd...

**Comment by CitadelCore** [comment]
Fixed. This was caused because CS:GO checks the spawnflags of trigger_look, while Portal 2 does not. I've made it so in P2CE the "Allow Clients" flag gets added automatically to ensure backwards compatibility with the campaign and existing maps.
