### ISSUE TITLE
VScript IDE

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#20]
Create a VScript IDE for Hammer and Puzzlemaker. Add similar functionality to that of Visual Studio such as function suggestion/auto-completion, Go to Definition, Debugging (step-through, see variable values, etc)

**Comment by CitadelCore** [comment]
This can be added as a feature of Chaos Launcher.

**Comment by SpyceTewan** [comment]
Nope
