### ISSUE TITLE
Gel splashing on screen effects do not appear

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#200]
While it looks like it might be there in the screenshot, if you look closely you can see that those are just the normal gel splat particles.
![image](https://user-images.githubusercontent.com/19228201/87372586-cdd1a680-c53c-11ea-81bb-47844122d576.png)
On a related note, in the base game, the overlay never appears when gel falls onto you from above (even if you're looking upwards). While this may be intentional, it seems kind of weird and should probably be changed either way.

**Comment by Luke18033** [comment]
For #262, this would need to always appear regardless of what direction the gel hits you from.

**Comment by CitadelCore** [comment]
Fixed.
