### ISSUE TITLE
sp_a4_speed_tb_catch: P-Body does not move

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#204]
When Wheatley pulls apart the other chamber to make an exit, P-Body remains stuck by the exit door in their idle pose, instead of leaving as they should. This also prevents the exit door from opening, making it impossible to complete the chamber without cheats.
![image](https://user-images.githubusercontent.com/19228201/87387506-b48a2380-c557-11ea-9868-f18c81a254d7.png)

**Comment by CitadelCore** [comment]
Fixed by #199.
