### ISSUE TITLE
sp_a4_finale2: Gel pipe catwalk destruction sequence doesn't work correctly

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#205]
The pipe is briefly visible on the left, but misses the catwalk entirely:
![image](https://user-images.githubusercontent.com/19228201/87388512-d4224b80-c559-11ea-8956-e7fcef219e57.png)
The gel still gets applied to the surface at the start of the catwalk, coming from an invisible paint sprayer:
![image](https://user-images.githubusercontent.com/19228201/87388594-fb791880-c559-11ea-85f3-52a698f4feb4.png)
The catwalk breaks when the player steps on it, which seems to be an otherwise unused behavior...
![image](https://user-images.githubusercontent.com/19228201/87388714-2a8f8a00-c55a-11ea-8b4d-3c971ce3018e.png)

**Comment by CitadelCore** [comment]
Fixed by #176.

**Comment by Luke18033** [comment]
Really? Seems unrelated, but alright.

**Comment by Luke18033** [comment]
Still not working correctly for me.

**Comment by CitadelCore** [comment]
A new issue should be opened for this bug you're still experiencing. It's unrelated to the original animation bug.

**Comment by Luke18033** [comment]
Sure? It's the exact same thing that's happening though.

**Comment by CitadelCore** [comment]
Yes. 100%. The same code path that was causing the original bug has been completely disabled.
