### ISSUE TITLE
Turrets sometimes emit fiddlesticks errors after being tipped

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#206]
I'm not sure exactly what causes this, but sometimes after turrets have been tipped over and are in their "random firing" state, a fiddlesticks error can be heard. The console reports the missing sound `FX_RicochetSound.Ricochet_Legacy`.

**Comment by CitadelCore** [comment]
This is because for some reason CSGO implemented a 1% chance of playing the legacy ricochet sound. I've removed this "feature".
