### ISSUE TITLE
Community-contributed (Free/Earned) Economy Items

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#21]
Bring back the old Economy items and add new items that can be contributed by the community that can be earned as random drops, earn in specific ways (e.g. achievements), or upon completing a specific map or finding an easter egg, etc.

Models could be specifically made for both the bots and Bendy or just one of them.

(You would need to make an approval process for items and integrating item drops into maps).

**Comment by ozxybox** [comment]
Superseded by https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/118.
