### ISSUE TITLE
env_portal_credits fails to load credits.txt from a mounted game, and crashes when activated

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#211]
This is also a result of Bink being removed, at least it doesn't freeze the game this time. Until WEBM support is implemented, it should just display a static image as the background (there's already one in the game files at `materials/vgui/scanline/sp_credits_bg`).

**Comment by Luke18033** [comment]
Okay, this is actually caused by a missing `scripts/credits.txt` (apparently it can't be in a mounted game). Adding it to the P2CE folder and then attempting to play the credits causes a crash.

**Comment by CitadelCore** [comment]
Fixed - this no longer causes a hard crash. I chose not to implement support for a static image for now, as we'll be implementing Video Services to support WEBM very soon anyway.

**Comment by Luke18033** [comment]
So it just does nothing for now?

**Comment by CitadelCore** [comment]
Correct.

**Comment by Luke18033** [comment]
Ah, that's basically the behavior I expected originally.
