### ISSUE TITLE
Player always spawns with a dual portal gun

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#212]
Even in maps without any prefix and the earlier campaign maps, the player will always spawn with a dual portal gun.

**Comment by SpyceTewan** [comment]
Please see if this is tied to `sv_can_carry_both_guns`. In the original code, this cvar will _spawn_ you with the paintgun and the portalgun. I removed this a while ago but maybe the changes didn't take effect for some reason?

**Comment by CitadelCore** [comment]
Can confirm that was the issue. I've fixed it on dev.
