### ISSUE TITLE
sp_a1_intro1: Wheatley's dialogue stops after "brain damage" line

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#213]
Immediately after Wheatley's "very minor case of serious brain damage" line, his dialogue will stop, preventing you from progressing in the sequence. The console reports a missing choreo scene `scenes\npc\sphere03\intro_ride07.wav`. All of the base game scenes are present and Valve's choreo scripts haven't been modified at all, so I'm not sure what's wrong.

**Comment by SpyceTewan** [comment]
That scene just became 10x more impactful

**Comment by CitadelCore** [comment]
Fixed.
