### ISSUE TITLE
Game does not pause server side

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#216]
Pausing only stops the client, not the server. The player will continue to move after pausing the game.

**Comment by CitadelCore** [comment]
It does pause the server side - but not fully. Everything except the player is properly paused.

**Comment by Luke18033** [comment]
Opening the console (without the pause menu) also doesn't pause audio.

**Comment by SpyceTewan** [comment]
I actually prefer it if the console doesnt pause the game as it's easier to use tools like colorcorrectionui

**Comment by Luke18033** [comment]
It does pause the game though, just not the audio.

**Comment by CitadelCore** [comment]
Fixed.

**Comment by SpyceTewan** [comment]
Sound doesn't pause

**Comment by CitadelCore** [comment]
Fixed for real this time.
