### ISSUE TITLE
Developer commentary doesn't work

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#217]
No nodes appear so scripted sequences are broken, especially for coop dev commentary maps.

**Comment by Luke18033** [comment]
The console reports a missing commentary config file. It seems the game is unable load them from mounted folders, as copying them into the `p2ce` folder fixes the issue.

**Comment by CitadelCore** [comment]
Likely it's looking for them in the main game folder - p2ce in P2CE instead of portal2.

**Comment by CitadelCore** [comment]
Seems to be fixed
