### ISSUE TITLE
Adhesion Gel does not rotate the player's camera

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#218]
When the player walks on walls or ceilings with adhesion gel, their movement and hitbox are rotated correctly, but the camera is not. On ceilings, this results in the view turning entirely black/nodraw, with only the viewmodel visibie. 

Yesterday I recorded [this video](https://www.youtube.com/watch?v=tI3b9SNbTEY) to show someone adhesion gel working on a curved surface. Near the end of the video, the camera can be seen tilting slightly, so possibly some of this code is still functional?

**Comment by CitadelCore** [comment]
This is to be expected, we've only partially reimplemented it.

**Comment by Luke18033** [comment]
Wouldn't this just be a feature request then?
