### ISSUE TITLE
Reimplement Adhesion Gel enter/leave sounds

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#219]
Sound(scripts) exist in the game files for entering and leaving Adhesion Gel, but are not used in P2CE. [You](https://tcrf.net/images/8/85/Portal2_Player_enter_stick_paint_01.ogg) [can](https://tcrf.net/images/6/6d/Portal2_Player_enter_stick_paint_02.ogg) [listen](https://tcrf.net/images/7/78/Portal2_Player_enter_stick_paint_03.ogg) [to](https://tcrf.net/images/7/73/Portal2_Player_exit_stick_paint_01.ogg) [them](https://tcrf.net/images/e/e8/Portal2_Player_exit_stick_paint_02.ogg) [here](https://tcrf.net/images/5/55/Portal2_Player_exit_stick_paint_03.ogg) (the volume is much lower in-game). These should be implemented.

**Comment by CitadelCore** [comment]
Fixed.

**Comment by Luke18033** [comment]
That was fast.
