### ISSUE TITLE
ScriptShowHudMessageAll does not work

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#222]
No errors are displayed in the console, but the message simply does not appear. The [list of CS:GO script functions](https://developer.valvesoftware.com/wiki/List_of_Counter-Strike:_Global_Offensive_Script_Functions) doesn't include this, so it could be intentional - but given that this is meant be an enhanced Portal 2 engine, it should be reimplemented for backwards-compatibility.

**Comment by Luke18033** [comment]
`game_text`s set to channels 1 and 4 (both "normal" text size) also don't work, which is probably related.

**Comment by SpyceTewan** [comment]
Portal 2's `ShowMessage` function also never worked for me. Can someone confirm?

**Comment by Luke18033** [comment]
It didn't work for me in P2CE, never tried using it in the base game.

**Comment by CitadelCore** [comment]
This, as well as game text channels 1 and 4 has been fixed.
