### ISSUE TITLE
Remove PTI leftovers

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#223]
Several (non-functional) PTI leftovers remain in P2CE, which should be removed:
- "Create Test Chambers" button on the main menu
- "Puzzlemaker Sounds" option under Audio
- "Swap Split Screen Control" keybind (this only worked in the Puzzlemaker, and is mapped to nonexistent command `swap_ss_input`)

**Comment by AddMGH** [comment]
- "Create Test Chambers" button on the main menu
Where is this?

**Comment by SpyceTewan** [comment]
_Ui will get remade anyways_

**Comment by AddMGH** [comment]
> _Ui will get remade anyways_

"Swap Split Screen Control" keybind (this only worked in the Puzzlemaker, and is mapped to nonexistent command swap_ss_input)
