### ISSUE TITLE
Chapter unlocking is broken

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#224]
After completing the game, all chapters besides The Courtesy Call remain locked
![image](https://user-images.githubusercontent.com/19228201/87505211-2c6e5180-c61d-11ea-93f4-6ce42f79dc76.png)
They are also locked in commentary mode
![image](https://user-images.githubusercontent.com/19228201/87505228-3db75e00-c61d-11ea-9c40-96f4b915edc1.png)
All Challenge Mode maps remain locked as well, in all chapters
![image](https://user-images.githubusercontent.com/19228201/87505266-4f006a80-c61d-11ea-94f5-1f4f86e3d699.png)
Setting `sv_unlockedchapters` doesn't do anything (I'm not sure if P2 even uses this anymore).

**Comment by SpyceTewan** [comment]
Ui will get remade anyway

**Comment by AddMGH** [comment]
Ah, but in that case, the new ui may still have the issue due to it having to use the same system to figure out whether chapters are complete?

**Comment by CitadelCore** [comment]
We still need to fix this as part of the base UI fixes.

**Comment by SpyceTewan** [comment]
The system would likely have to be rewritten to support things like multiple campaigns. The panorama api has to be made from scratch

**Comment by CitadelCore** [comment]
This happens because all chapters are unlocked by the "Shoot the Moon" achievement, but this doesn't exist in P2CE...

**Comment by Luke18033** [comment]
You should just make them all unlocked by default, I highly doubt anyone testing P2CE will have not played the original game. You can then later implement a redesigned, non-hardcoded chapter unlock system after the UI is redesigned.

**Comment by CitadelCore** [comment]
This has been implemented.

**Comment by Luke18033** [comment]
A proper chapter unlock system, or just making them always available like I suggested?

**Comment by CitadelCore** [comment]
The latter.
