### ISSUE TITLE
Arrival Transition Ents do not work when compiled in P2CE hammer

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#226]
![image](https://user-images.githubusercontent.com/26350889/87519291-4d649000-c679-11ea-8c1f-f6ea989920a3.png)

[p2ce_default_layout.zip](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/4923721/p2ce_default_layout.zip)

**Comment by SpyceTewan** [comment]
That has nothing to do with hammer

**Comment by distributivgesetz** [comment]
Edit suggestion: "Arrival Transition Ents do not work when compiled for P2CE"
