### ISSUE TITLE
P2CE Hammer has framerate drops when rendering refract shader

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#227]
[p2ce_default_layout.zip](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/4923738/p2ce_default_layout.zip)
Refract shader causes framerate drops due to attempt to load missing material.

**Comment by SpyceTewan** [comment]
Sure it's not the refract shader?

**Comment by AddMGH** [comment]
> Sure it's not the refract shader?
Possibly? It's also seen with the elevator fan glass model too

**Comment by CitadelCore** [comment]
Almost certainly the refract shader. For some reason the shader keeps trying to load a missing material every single frame, which causes the issue.

**Comment by TeamSpen210** [comment]
This is a CSGO regression I believe.

**Comment by CitadelCore** [comment]
Fixed.
