### ISSUE TITLE
Re-implement cut features

### ISSUE THREAD

**Issue by BlightedLight** [ChaosInitiative/Portal-2-Community-Edition#23]
- Adhesion Gel (whilst keeping Reflection Gel)
- Paint Gun
- Schrodinger Cube
- Futbol (could just be a PTI map?)
- Unused turret dialogue
- Unused PTI map track ("ctc_b1_006.wav")
- Other unlisted features

**Comment by Luke18033** [comment]
You don't need the source code to re-enable the unused turret dialogue. Just add the voicelines in `scripts/npc_sounds_turret_portal.txt` alongside the used ones. The unused PTI track should work similarly, though I've never tried to get it to play.

**Comment by SpyceTewan** [comment]
Please create individual issues for these
