### ISSUE TITLE
Dying and respawning with the paint gun causes it to get stuck lowered down

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#230]
The title says it all.
![image](https://user-images.githubusercontent.com/19228201/87595995-3be4ad80-c6a4-11ea-98c3-71ed1c15328c.png)
(Yes this is an Aperture Tag map)

**Comment by CitadelCore** [comment]
The model animations aren't set up correctly - this will be fixed when the actual paint gun is implemented.
