### ISSUE TITLE
P2CE fails to load content from single-chunk VPKs

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#237]
I decided to try mounting my custom content onto P2CE using `mounts.cfg`. The result? All VPK override content failed to load. Shown below are the crosshair, custom portal gun (the error above my head), and a fixed version of one of the tile textures on the floor in the background.
![image](https://user-images.githubusercontent.com/19228201/87715318-07cfc200-c762-11ea-9a1c-c238eed39229.png)
Wondering what could possibly be different between this and the base game content, I decided to try packing my stuff into a multi-chunk VPK. And guess what? ~Ground up moon rocks are pure poison~ The content loaded without a problem. (The portal gun model is now loading, but invisible. That seems to be an unrelated issue.)
![chaos_V3wPXkl2XW](https://user-images.githubusercontent.com/19228201/87715781-b5db6c00-c762-11ea-9937-9b26cfcd0647.png)
This seems to indicate that P2CE is incapable of properly loading content from single-chunk VPKs, despite what I was told the other day. This should be investigated and fixed.

**Comment by SpyceTewan** [comment]
Fixed
