### ISSUE TITLE
Mount content from Portal 2 workshop

### ISSUE THREAD

**Issue by BlightedLight** [ChaosInitiative/Portal-2-Community-Edition#24]
Mount maps from people's subscribed Portal 2 workshop content, so nobody should have a reason to use standard Portal 2 for anything other than the vanilla experience.

**Comment by CitadelCore** [comment]
Not yet sure if this is possible. Investigation required with Steamworks API.

**Comment by SpyceTewan** [comment]
We cant access other appids
