### ISSUE TITLE
Hammer clipping tool should always make cuts nodraw

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#240]
The fact that it takes the top face's texture every time annoys me to no end, it should always be nodraw.

**Comment by koerismo** [comment]
I think it should take the texture from the face with the closest normal from left to right

**Comment by Konclan** [comment]
It really should just be nodraw all the time, the amount of times cuts get left the wrong texture is always because I have to manually replace every single new face with nodraw. rarely am I ever thankful that it saved me 0.1 second of time by using a face's texture.

**Comment by L89David** [comment]
I totally agree. I hate when you cut brushes and the faces inside have textures... (Even if they don't get rendered in-game)

**Comment by SpyceTewan** [comment]
Done. I added it as an option under the General tab. [https://youtu.be/QYIeGU-j81E](https://youtu.be/QYIeGU-j81E)
