### ISSUE TITLE
paintallsurfaces can apply invalid gel types

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#241]
The `paintallsurfaces` command can apply any gel ID, including negative or otherwise invalid ones. These usually cause crashes when touched, and eventually it loops back around to the used gels. The command should be limited to only applying valid gel IDs (`0-5`).

**Comment by CitadelCore** [comment]
Fixed

**Comment by Luke18033** [comment]
Still allows applying negative paint types

**Comment by CitadelCore** [comment]
Oops. Fixed.
