### ISSUE TITLE
Missing textures appear pure black instead of the magenta checkerboard

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#250]
The title says it all.
![image](https://user-images.githubusercontent.com/19228201/87826006-fc959880-c82c-11ea-96b2-e8964064ac60.png)

**Comment by FrozenDragon0** [comment]
Dafuq? I thought CS:GO's engine also used the same checkerboards?

**Comment by Luke18033** [comment]
It's probably a P2CE-specific bug.

**Comment by CitadelCore** [comment]
This is not a bug, a black texture is intentionally created instead of the checkerboard in CS:GO. I've reverted this to the old way.
