### ISSUE TITLE
Add easier ways to make displacements in hammer.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#252]
Displacements in hammer right now are just really annoying to make when it comes to mountain like landscape hills cliffs etc. We should have other ways to make these more easily.

**Comment by distributivgesetz** [comment]
What do you mean, more easy? It's fine as is, at least for me...

**Comment by FrozenDragon0** [comment]
@distributivgesetz Hard to explain but say if I wanted to make a TF2 payload map for example the maps mostly use displacements due to TF2's nature however making such terrain can be quite a challenge and more tools would be nice to make it easier. I just generally hate the way displacements are made it's just really difficult to shape them into what you want it to look like and it turns out being a mess.

**Comment by distributivgesetz** [comment]
I cant really think of a case where you would want to make a level with a big landscape inside Portal 2 (except if your name were DaMaGePy)...
