### ISSUE TITLE
Walking through a fizzler switches viewmodel to the portal gun model

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#253]
If the player has portals open and a non-portalgun weapon currently equipped, walking through a fizzler will switch the viewmodel to the portalgun model.

<details>
<summary>Original content</summary>
I edited the paint gun's weapon script to replace its model with a modified version of the Tag gun:
![image](https://user-images.githubusercontent.com/19228201/87863345-07c0f500-c90f-11ea-8fa7-8d03fc4f4d31.png)
However, after walking through a fizzler, the model is forced back to a portal gun. This only happens if you have portals opened when walking through the fizzler. It still uses the selected gel's color, and otherwise functions as a paint gun:
![image](https://user-images.githubusercontent.com/19228201/87863378-4b1b6380-c90f-11ea-8461-87cdceaa66fd.png)
Notably, I wasn't able to fix the issue with my portal gun model not rendering, instead recompiling it under a different filename and editing the script to use that. The fact that the model does render in this case implies that it is actually using the specified portal gun model from its script, instead of a hardcoded model name.

**Comment by Konclan** [comment]
This issue extends to when loading a save if you are holding a weapon that isn't the portal gun, the portal gun will render until the weapon is used.

**Comment by Luke18033** [comment]
Should probably make that a separate issue
