### ISSUE TITLE
Hammer: worldtext helper does not render correctly

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#254]
The title says it all.
![image](https://user-images.githubusercontent.com/19228201/87864287-54123200-c91b-11ea-9857-e5a040e5289b.png)

**Comment by CitadelCore** [comment]
![image](https://user-images.githubusercontent.com/5567402/88714796-314efd00-d115-11ea-94ff-a8919e7ccec1.png)
Fixed.

**Comment by SpyceTewan** [comment]
Was just missing the font sheet material
