### ISSUE TITLE
P2 bug: trigger_portal_cleanser uses bounding box for portal shot blocking

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#263]
This causes diagonal or concave cleansers to block portal shots in cases where they seemingly shouldn't. Portal and object fizzling works as expected.

**Comment by L89David** [comment]
Do the scanlines look good too?

**Comment by Luke18033** [comment]
I always end up turning them off so I'm not sure, but they're probably broken as well.

**Comment by CitadelCore** [comment]
Fixed.
