### ISSUE TITLE
Fix func_precipitation

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#267]
Currently only works with snow, and not even good. If you use portals, they cause extreme visual glitches like this:
![IMG_20200723_173110](https://user-images.githubusercontent.com/48654552/88600590-e8dd0400-d06e-11ea-878e-7f832b46f02c.jpg)

**Comment by L89David** [comment]
Actually, not only func_precipitation. Seems like it also happens with func_dustclouds at far distances.

**Comment by Luke18033** [comment]
I've never had that rendering problem, might be related to `r_portal_fastpath`?

**Comment by L89David** [comment]
Iirc I had `r_portal_fastpath 0`

**Comment by Luke18033** [comment]
Huh.

**Comment by Luke18033** [comment]
Also is that a picture of your monitor...

**Comment by CitadelCore** [comment]
We will not be supporting the legacy modes of func_precipitation that simulate rain on the CPU - all types that are not particle rain. This mode is notorious for being very problematic and was only used in older versions of Source (HL2).

Instead I've made some fixes & improvements to the particle rain modes, which do work and are supported in CS:GO - you can now override the inner near, inner far, and outer particle systems, as well as the distance between the inner and outer systems, via keyvalues.

**Comment by L89David** [comment]
> Also is that a picture of your monitor...

yes, it is? I couldn't really screenshot this somehow...

Also, nice! Can't wait to try those rain particles.
