### ISSUE TITLE
Fix Conversion Gel on Hard-Light Bridges

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#27]
Allow Conversion Gel to make Hard-Light Bridges a portable surface.

**Comment by Luke18033** [comment]
I don't think it's supposed to do that? Portal shots go through light bridges in all other cases, so it doesn't make too much sense.

**Comment by ethan101au** [comment]
Yeah, but this removes potential from the gel.

**Comment by mariovct** [comment]
I see huge potential here. Because if adding Conversion Gel to Lightbridges did indeed make it a Portalable “Wall”, That would mean that it could block Funnels, Lasers, and other Lightbridges, and you would lose the ability to fire Portals through

**Comment by ozxybox** [comment]
This will not be added.
