### ISSUE TITLE
Fix "paint bomb has no model name" warnings

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#270]
If a `prop_paint_bomb` doesn't have a `model` keyvalue set, it will produce a warning in the console every time it spawns. This wouldn't normally be an issue, but with paint bombs constantly exploding and respawning, it gets irritating pretty fast. TeamSpen's addons have already worked around this by adding that keyvalue, but it'd be nice to have it fixed in the engine properly.

**Comment by SpyceTewan** [comment]
Fixed

**Comment by Luke18033** [comment]
This can also happen for cubes in some cases, might be a good idea to fix that as well.

**Comment by SpyceTewan** [comment]
If so, open a new issue for that
