### ISSUE TITLE
Reimplement trigger_portal and logic_mirror_movement

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#271]
According to the VDC, [these](https://developer.valvesoftware.com/wiki/Trigger_portal) [two](https://developer.valvesoftware.com/wiki/Logic_mirror_movement) entities are present in the code but not properly included in any games. Seems like they should be pretty simple to reimplement.

**Comment by CitadelCore** [comment]
Done.
