### ISSUE TITLE
r_drawvgui 0 should hide the playtest overlay

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#272]
As stated in the title, setting `r_drawvgui 0` should hide the playtest overlay. Since this command disables visibility of all UI, it's not realistically usable to avoid the overlay entirely, but can be used to disable it temporarily for screenshots and such.

**Comment by CitadelCore** [comment]
The playtest overlay is intentionally implemented so it cannot be disabled for security reasons.

**Comment by SpyceTewan** [comment]
That's what the overlay is kinda for isn't it? To be there at all times and never be turned off. I'd definitely make it smaller though, it's comically big

**Comment by Luke18033** [comment]
Yeah, which is why I suggested tying it to this and not drawhud or something. It hides all of the UI including the pause menu and console, making the game somewhat unplayable with it disabled. But it can be temporarily turned off for screenshots.
