### ISSUE TITLE
Add func_paint_detector

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#277]
Pretty much what the title says. Be able to detect paint in a determinated area. (I don't know if it's possible to do)

**Comment by SpyceTewan** [comment]
Duplicate of #42

**Comment by L89David** [comment]
This is actually a different thing though. Not gel flow.
I meant detecting gel that has been applied to a surface.

**Comment by Luke18033** [comment]
That would be a duplicate of #43 then.
