### ISSUE TITLE
Unhide and improve Hammer Logical View

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#278]
Hammer has a "logical" viewport mode, that shows entities as boxes with lines going between them representing I/O. The view is hidden by default, however, and can only be accessed by editing the registry. It'd be nice to have this enabled in P2CE.

**Comment by Luke18033** [comment]
Some additional improvements:
- Entities' default positions in the logical view should be based on their X/Y coordinates within the actual map, though you'd still be able to freely reposition them separately.
- Entities with iconsprites should display their sprite instead of a box (I think this is supposed to happen, but is broken)
- IIRC it only comes in a light mode variant? Add a dark version in that case.

**Comment by L89David** [comment]
Included in #47 (not the improvements)

**Comment by Luke18033** [comment]
Ah, this'll just be the improvements then.

**Comment by SpyceTewan** [comment]
Well now i know what the `logical` rendering actually does when I looked through the code

**Comment by Luke18033** [comment]
Displaying of iconsprites does work in Portal 1/Source 2013, and looks quite nice:
![image](https://user-images.githubusercontent.com/19228201/93419062-a8c12300-f860-11ea-95e0-75cd4840bd4c.png)
Another thing I forgot about, outputs marked as invalid will flash red, which is a little annoying considering that they may not actually be invalid (for things like instances or special targetnames). It'd be nice to have this removed.

**Comment by CitadelCore** [comment]
Done.

**Comment by Luke18033** [comment]
The blinking red animation is still there, and the color scheme is still bugged. Should I open separate issues for those?

**Comment by Luke18033** [comment]
Iconsprite rendering does work again, which is nice.
