### ISSUE TITLE
Fix static effect of projected textures in NVIDIA drivers

### ISSUE THREAD

**Issue by BlightedLight** [ChaosInitiative/Portal-2-Community-Edition#28]
Fix static/grain effect that happens on surfaces with nVidia graphics cards. (Only happens with projected textures...?)

![image](https://user-images.githubusercontent.com/35391144/53165453-79afe480-361e-11e9-9c30-b7e8eb919a86.png)

**Comment by CitadelCore** [comment]
Is this already fixed in the CS:GO branch?

**Comment by ethan101au** [comment]
I've never seen this happen in CSGO, so I would assume so.

**Comment by Luke18033** [comment]
Specifically, the issue is caused by a combination of projected textures, `$detailblendmode 0` and bumpmaps. It doesn't exist in any other games as far as I know.

**Comment by SpyceTewan** [comment]
Yes this is fixed in csgo

**Comment by FrozenDragon0** [comment]
Sad to see how valve hasn't even fixed this annoying bug in default P2, don't even give 2 shits about it.

**Comment by warmCabin** [comment]
How was this fixed? Can it be applied to vanilla Portal 2?

**Comment by FrozenDragon0** [comment]
@warmCabin It's because P2:CE is on the CS:GO engine which doesn't have this problem. Don't expect a fix for portal 2 as this has been known for years and valve or Nvidia has done nothing about it.

**Comment by warmCabin** [comment]
I'm all too familiar with the annoying history of this issue :(
But I was wondering if you knew what they actually did to fix it between P2 and CS:GO, and if there could be some kind of community patch/mod/janky workaround.

**Comment by CitadelCore** [comment]
This isn't relevent to P2CE, please continue discussion elsewhere
