### ISSUE TITLE
func_precipitation set to Particle Snow crashes the game

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#285]
After CitadelCore said in #267 to only use the particle modes, I decided to try switching the `func_precipitation` in my test map from Snowfall to Particle Snow. The game instantly crashed on map load. Switching the entity to another mode would stop the crash. As usual, no minidump was created.

The other particle-based modes also don't render any effects, though that's probably related to missing particle systems and not a bug in the entity itself.

**Comment by CitadelCore** [comment]
The fix is not in the current build.

**Comment by CitadelCore** [comment]
Reopen this if still broken in the next build.
