### ISSUE TITLE
Allow freely choosing func_button sounds

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#288]
`func_button` currently uses numerical IDs to select from a hardcoded list of sounds, most of which don't exist in P2. Change this to allow selecting any sound.

**Comment by SpyceTewan** [comment]
I never understood why they added it this way in the first place...

**Comment by TeamSpen210** [comment]
It's from HL1, where they probably didn't want to have long filenames in the BSP or the like or something.

**Comment by SpyceTewan** [comment]
Added the `customsound` keyvalue, which is used when the sound is set to -1
