### ISSUE TITLE
Fix env_steam hammer helper

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#297]
Currently, the shape of the steam preview in Hammer is incorrectly rotated 90 degrees more.
Would be nice if we could have the shame preview as `light_spots`... We could see the size of the steam much more easier, instead of seeing a static gray triangle.

**Comment by SpyceTewan** [comment]
that sounds like a hammer addons issue

**Comment by CitadelCore** [comment]
Please raise this as an issue on the HammerAddons repo
