### ISSUE TITLE
Add 'IES Lighting'

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#300]
![image](https://user-images.githubusercontent.com/26350889/89330428-200f6e80-d688-11ea-8d68-3a1a50aa91ae.png)

**Comment by distributivgesetz** [comment]
Duplicate of #29, please search up issues before spamming issues from the webpage, thanks.

**Comment by AddMGH** [comment]
> 
> 
> Duplicate of #29, please search up issues before spamming issues from the webpage, thanks.

I searched 'lighting', not 'ies'.
