### ISSUE TITLE
Fix 'Lightmappedreflective'

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#303]
https://i.imgur.com/oG3tEPr.png

**Comment by CitadelCore** [comment]
Please add more info. What is broken?

**Comment by Luke18033** [comment]
It "doesn't work" according to the VDC, which still isn't very descriptive...

**Comment by JJL772** [comment]
lightmappedreflective has been used in Momentum Mod maps, and even works in dx11. There's not enough info here, so going to assume it's no longer a problem (if it ever was in the first place).
