### ISSUE TITLE
Add 'Physically Based Rendering shader'

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#305]
![image](https://user-images.githubusercontent.com/26350889/89330677-885e5000-d688-11ea-8c12-3f50b30dd701.png)

**Comment by distributivgesetz** [comment]
Duplicate of #144, please search up issues before spamming issues from the webpage, thanks.

**Comment by AddMGH** [comment]
yes, because i know what pbr is
