### ISSUE TITLE
Add 'Legacy movement (Optional)'

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#309]
![image](https://user-images.githubusercontent.com/26350889/89330954-e1c67f00-d688-11ea-9b7f-a98ff560b7d2.png)

**Comment by AddMGH** [comment]
This could be solved by the proposed implementations in #99

**Comment by JJL772** [comment]
Closing in favor of more detailed game movement feature requests.
