### ISSUE TITLE
Increase entity limit

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#31]
Double it. Triple it! However high we set it, let's make it HIGHER!

**Comment by Luke18033** [comment]
Can't this not be done without breaking compatibility with older maps? That was fine for Desolation (which also did this) since it's a standalone mod, but for this we'd want to make sure people can play existing P2 maps. Maybe there could be some sort of compatibility mode implemented, or I'm just wrong about all of this.

**Comment by SpyceTewan** [comment]
P2E has no intent to be compatible with the Portal 2 engine. Alone the fact that it is going to use CS:GO as the base makes the mals completely incompatible because of BSP version differences

**Comment by Luke18033** [comment]
That conflicts with #24, which is about mounting stock P2 Workshop maps (which would require that compatibility).

**Comment by SpyceTewan** [comment]
That issue was opened 10 months ago. Back then, this place was basically a dumping ground for ideas. Priorities and plans shifted. I'm not sure if we can support Portal 2 maps because of that bsp version difference, and can't confirm or deny it. We will plan out what we can and can't do as soon as we get source code.

Even if we can't support Portal 2 BSPs, it should only require a recompile on the P2E compilers to make them work, but don't take my word for that

**Comment by Luke18033** [comment]
What exactly is the plan for this now?

**Comment by TeamSpen210** [comment]
Increasing the entity limit shouldn't cause incompatibility by itself.

**Comment by SpyceTewan** [comment]
CS:GO has already increased this to 2^14 (16 384)
