### ISSUE TITLE
Major refactor of prop_weighted_cube

### ISSUE THREAD

**Issue by CitadelCore** [ChaosInitiative/Portal-2-Community-Edition#311]
prop_weighted_cube is currently designed with a specific set of models and skins in mind. We should either refactor the existing entity to work better in this regard, or if that is not possible due to backwards compatibility concerns, create a new weighted cube entity that is more configurable.

**Comment by TeamSpen210** [comment]
We actually did the same in Desolation. You could use `NewSkins = 2` to identify this third style, if you want backwards compatibility. But what we did is make the cube type like so:
```c
CubeType(choices) : "Cube Type" : 0 : "How does the cube function?" =
	[
	0 : "Weighted Cube"
	1 : "Reflective Cube"
	2 : "Sphere"
	3 : "Schrodinger Cube"
	]
model(studio) : "Model : "models/props/new_cube_model.mdl" : "The model for the cube."
skin(choices) : "Starting paint" : 0 : "The cube starts painted with the set gel." =
	[
	0 : "None"
	1 : "Repulsion Gel"
	2 : "Propulsion Gel"
	3 : "Adhesion Gel"
	4 : "Reflection Gel"
	]
```
Then for every cube type, we recompiled the model with a layout of skins 0-4 for off gels, and 5-9 for on-gels (with duplicates for Old Aperture/Reflection cubes). That meant also that the rusty ones were a seperate model, but companion/antique and rusty versions could all be treated identically. Up to you if you want to replicate our layout.

**Comment by Luke18033** [comment]
If you want to allow gel color customization, I still think you should do something like what I suggested. I'll repost that here, for reference.
> I thought of an idea for how P2CE could handle gel-coated object textures, without having to add a bunch of additional skins to the models - a `GelOverlay` material proxy that would dynamically set `$detail` and `$detailtint` depending on whether the cube was painted, and what type it was painted with. That removes the need for the unique skins, allows adding a Conversion Gel variant (which doesn't do anything, so would otherwise be a waste of skins), and would allow easily recoloring the overlays to match selected gel colors, including for the custom gel. How feasible would this be to implement/is there a better way to handle it?

Perhaps add a few different variants of the texture, which are picked between randomly. While `rendercolor` could just be used to recolor the overlay, this would break things like colorized cubes, so it'd be better to set `$detailtint` using the proxy instead.

**Comment by CitadelCore** [comment]
Good idea. I'll see if we can implement the proxy route.

**Comment by Luke18033** [comment]
While no longer used, the original gel-coated skins should still be kept, for backwards-compatibility (with maps that have cubes specifically set to those skins).

**Comment by Luke18033** [comment]
I'd also suggest having cube type 6 use skin 0 for off and skin 1 for on, then the proxy for gel-covered variants. That removes the need for custom cubes to A. use AddOutput to switch back to a default cube type and B. use the weird skin layout of the standard cube.

**Comment by Luke18033** [comment]
Okay, but that would mean custom cubes could only behave like standard cubes. Better idea based on what TeamSpen suggested: setting `NewSkins` to 2 would make the Cube Type only determine the cube's behavior, with the model being specified in the `model` keyvalue and using skin 0 for off and 1 for on.

In Hammer, cube type 6 would be relabeled as `Legacy Custom Model`, and the new skins keyvalue would become `Model Selection Method` or something, with a choices dropdown containing the old method and the new method.

**Comment by Luke18033** [comment]
See #1068
