### ISSUE TITLE
Demo player doesn't seem to work properly (or at all)

### ISSUE THREAD

**Issue by Krzyhau** [ChaosInitiative/Portal-2-Community-Edition#312]
Recording a demo and then playing it back using `playdemo` command make the screen go black. Using Demo Playback window or `demo_resume` command doesn't help.

Additionally, it seems like after doing these, some movement related cvars (`sv_friction` for instance) are set to their previous default values (the non-P2 ones).

**Comment by CitadelCore** [comment]
Fixed.
