### ISSUE TITLE
Add a concommand for devshot cameras

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#317]
Right now, devshot cameras only take pictures when the game is loaded up into the map right away with a specific startup parameter. (So typically when started from hammer).

A console command to manually invoke the devshot screenshotting would make it more flexible.

(If this already exists, my bad, I couldnt find anything online)

**Comment by Konclan** [comment]
A function to stay on a camera or use a specific camera or something so we can take the screenshot ourselves would be nice.

**Comment by SpyceTewan** [comment]
Yeah like an option to teleport yourself straight to that camera

**Comment by SpyceTewan** [comment]
Added the TakeScreenshot input to point_devshot_camera. Decided not to implement a command to take screenshot from all cameras, since that feature already exists if you start the game with -makedevshots
