### ISSUE TITLE
Allow Hammer to read particles from VPKs

### ISSUE THREAD

**Issue by RedstoneParadox** [ChaosInitiative/Portal-2-Community-Edition#318]
~~It's currently a bit of a hassle to extract things like particles from the VPKs in order to use them in Hammer, so it would be nice if Hammer could read the VPKs directly.~~

Hammer currently cannot show packed particles in the particle browser, unlike textures and models. It's a bit of a hassle to unpack them so it would be nice if this was fixed.

**Comment by Luke18033** [comment]
Hammer can read VPKs perfactly fine, how do you think it's able to display textures and models? It's specifically the particle browser that has this problem.

**Comment by CitadelCore** [comment]
The particle browser issue has been fixed.
