### ISSUE TITLE
Contact mapbase and see if you can port some of it to p2

### ISSUE THREAD

**Issue by Fennecai** [ChaosInitiative/Portal-2-Community-Edition#32]
I have found a mod recently called mapbase that looks like it might be really useful; if it were only on portal 2's branch. funnily enough; i heard about p2 enhanced because i suggested that very thing in a discord server.

after reading through the FAQ and some other wiki pages of mapbase; i wanna suggest you work with the creator(s) of mapbase (or possibly just mapbase itself) and see what features of mapbase can be ported to p2's branch. 

https://github.com/mapbase-source/source-sdk-2013/wiki

**Comment by ethan101au** [comment]
We can port the entities and QoL changes, but it's unlikely any shader or NPC changes will make it through.

**Comment by Fennecai** [comment]
> We can port the entities and QoL changes, but it's unlikely any shader or NPC changes will make it through.

hence the "some of". :)

i mostly just think the ents and QOL stuff would be amazing to have in p2- npcs have no real place in p2's gameplay style anyhow. heh

**Comment by SpyceTewan** [comment]
This is not related to the project's content but just public relations
