### ISSUE TITLE
Bicubic Filtering for Lightmaps

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#323]
With engine access, we can add bicubic filtering for lightmaps with no extra performance cost, whereas without engine access you'd have to filter the lightmaps every frame in shaders, but we can filter the lightmaps once and save that in the texture permanently.

Here is an example of bicubic filtering for lightmaps.
![unknown](https://user-images.githubusercontent.com/35391144/90135022-5dc17500-ddb5-11ea-9da0-a29ac1a43884.png)

**Comment by BlightedLight** [comment]
Only recently had the revelation that storing it in a texture is a bad idea as it would use significantly more texture memory, so we would still have to filter per-frame, which is expensive. We may have to allow bicubic filtering to be an optional graphical setting.
