### ISSUE TITLE
Cursor doesn't always show up in the pause menu on Linux

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#324]
The cursor remains hidden on the pause menu until you click a "back" button. Every other menu works fine. 

Screenshot of the behaviour: 
![sp_a2_sphere_peek0005](https://user-images.githubusercontent.com/19717056/90209040-319af980-dd9f-11ea-9981-0ba19727ee5f.jpg)

**Comment by bltech** [comment]
This is also an issue in the Momentum Mod chaos build, there you have to click on the console or map selector panel to make it appear again.

**Comment by JJL772** [comment]
Fixed
