### ISSUE TITLE
Paints don't actually paint stuff on Linux

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#325]
Another Linux issue! Paints dont paint the surfaces they touch, including the player.

Example:
![sp_a3_speed_flings0007](https://user-images.githubusercontent.com/19717056/90209201-8fc7dc80-dd9f-11ea-9fc2-0898d68066d3.jpg)

**Comment by BlightedLight** [comment]
Probably related to the LightmappedPaint shader, which we may have converted to Shader Model 3.

**Comment by JJL772** [comment]
I suspect it's the shader too, but there appears to be another issue internally. The surface properties are not modified whatsoever on surfaces that should be painted. In addition, the player doesn't have any post-processing effects applied to the screen when they get hit by the paint.
This particular issue was the main motivating factor behind the dxvk port.

**Comment by BlightedLight** [comment]
If it's not modifying the paint power, then I believe it's likely a user-messages/protobufs issue. As we can see the 'splash' particles are being created, so I believe it's _trying_ to paint the surface.

**Comment by JJL772** [comment]
So I assume the paint is only simulated client-side then?

**Comment by JJL772** [comment]
Fixed
