### ISSUE TITLE
Linux uses incorrect menu font

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#326]
I think this issue is specific to Linux too, but I could be wrong.  Image of the problem:
![Snapshot0003](https://user-images.githubusercontent.com/19717056/90209399-344a1e80-dda0-11ea-84bc-caf46625da8a.jpg)

**Comment by SpyceTewan** [comment]
The font in general is way too large

**Comment by JJL772** [comment]
@SpyceTewan Is this an issue on the windows builds too?

**Comment by CitadelCore** [comment]
It isn't

**Comment by Luke18033** [comment]
The entire UI is going to be rebuilt in Panorama, so does this really matter?

**Comment by CitadelCore** [comment]
The Panorama port is a long term project, won't be done for a few months yet at the least. Best to get the original UI working fully first.

**Comment by JJL772** [comment]
> The entire UI is going to be rebuilt in Panorama, so does this really matter?
I doubt this will take long to fix anyways.

**Comment by SpyceTewan** [comment]
Yeah looks like a missing font to me which is why it defaults to one that's bigger

**Comment by BlightedLight** [comment]
Open vanilla Portal 2 in Linux and compare the fonts. The font scaling for Linux may be broken or like Tewan suggested, is just defaulting to a larger font, which happens in the ClientScheme or SourceScheme I believe?

**Comment by JJL772** [comment]
Done in 0.5.7
