### ISSUE TITLE
Prevent laser emitters/catchers/relays from being painted

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#330]
Laser emitters, catchers, and relays can be coated in gel. This sets the model to that gel's color, overwriting a custom color if one is set. While this is purely visual, it can lead to confusion. For example, this seemingly uncolored laser catcher will not accept a blue laser, as it is actually a red catcher that was hit with Cleansing Gel.
![image](https://user-images.githubusercontent.com/19228201/90347131-2e904b00-dfe3-11ea-86e3-858d3706331f.png)
Being able to paint laser items never really made sense, and I don't know of any (good) maps that use it, so it should probably just be removed.

**Comment by FrozenDragon0** [comment]
Painting entities like this in general shouldn't have been a thing in the first place, I mean painting doors just looks really wrong.

**Comment by CitadelCore** [comment]
Fixed
