### ISSUE TITLE
Add stuff from Half-Life 2

### ISSUE THREAD

**Issue by URAKOLOUY5** [ChaosInitiative/Portal-2-Community-Edition#334]
It would be okay if Portal 2 had Half-Life 2 entities (It's mostly NPC and logic entities).

**Comment by distributivgesetz** [comment]
There will be a scripted NPC system available for mappers to make their own npcs, the Half Life 2 NPCs however won't be available natively (maybe as an example).
Plus, what do you mean with logic entities? Which ones won't be available inside the port to CS:GO?

**Comment by URAKOLOUY5** [comment]
e.g ai_ entities

**Comment by CitadelCore** [comment]
ai_ entities will be re-added, at least the ones that are not specific to HL2.

**Comment by SpyceTewan** [comment]
"Add stuff" is not a task we can complete. Stop spamming our issues with general suggestions
