### ISSUE TITLE
fix underwater windows rendering

### ISSUE THREAD

**Issue by Fennecai** [ChaosInitiative/Portal-2-Community-Edition#353]
I don't know if it's fully possible; but something that'd be great is if glass brushes that are submerged in a water brush on one side, would render it better from the other side instead of being weird like it currently is.

useful for making maps that take place in underwater cities, have aquariums, or anything else where water is on one side of a glass window and you're on the other side looking at it.

I know for a fact that there is a least one csgo map that has an area that does something like this, but i don't know how it does it- I think its de_zoo maybe?

**Comment by BlightedLight** [comment]
Provide examples of what you want and what currently happens, saying it's 'weird' isn't particularly useful information.

**Comment by Fennecai** [comment]
sure. heres a super-duper bare-bones vmf made specifically to demonstrate 2 examples: 
[devtest.zip](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/5191974/devtest.zip)

and a couple screenshots of it rendering badly in-game:

![portal2 9-8-2020 6-45-23 PM-218](https://user-images.githubusercontent.com/10889213/92541708-07085900-f204-11ea-89f6-32205615c464.png)
![portal2 9-8-2020 6-45-53 PM-759](https://user-images.githubusercontent.com/10889213/92541711-08d21c80-f204-11ea-9ac3-0a8e838468e2.png)


and an example of what i wish it did (not sure why you need this too, as my explanation/examples above are fairly straight-forward):
![image](https://user-images.githubusercontent.com/10889213/92541743-230bfa80-f204-11ea-8dae-3b485bc173f5.png)

**Comment by CitadelCore** [comment]
This may be a stupid question, but... does the water actually have textures on its sides?

**Comment by Fennecai** [comment]
nope. its nodraw. but i could probably test if it works with using the water texture or some other texture- i have my doubts though; since the problem mainly happens due to the culling effect of nodraw rather than just nodraw itself; and that happens whenever 2 solid faces face each other. that said- will water even work at all if the sides arent nodraw? I've always nodrawed it because that's what i was told to do back when i was a hammer newbie

**Comment by BlightedLight** [comment]
So you expect to see water through a face that you marked NODRAW...?

**Comment by Fennecai** [comment]
of course. not like water works properly with any other texture applied. :P

**Comment by Luke18033** [comment]
What happens if you also texture the sides with the water texture?

**Comment by CitadelCore** [comment]
![image](https://user-images.githubusercontent.com/5567402/92984887-ab5cfa80-f4a5-11ea-8077-6228b8e0a41f.png)

I decided to investigate; water does indeed not draw on sides that are touching transparent brushes.

**Comment by CitadelCore** [comment]
didn't mean to close

**Comment by Fennecai** [comment]
i mean- even if it doesn't render that face when its touching transparent textures (which is good cause water doesnt show up against glass irl either)- it'd still be nice if you saw particles and fog so the water looks like its not just a hollow cube with weird vertical water textures on its sides. lol

**Comment by SpyceTewan** [comment]
The way you want this implemented doesnt work. If you were to add some kind of materials to the side of the glass, you'd be able to see through it. You can already do this easily by just adding a separate animated texture material on the glass

**Comment by Fennecai** [comment]
why would i add an animated texture on the glass? that makes no sense. i don't want a weird water effect against the glass. i want it basically to render as if you were actually under the water; but like...only stencilled or whatever to render on the part of the screen that the water is actually visible through the window; if that makes sense? i understand why this'd be pretty difficult to implement though.
