### ISSUE TITLE
automatically "pbr-ize" materials if they arent already compatible with the pbr rendering

### ISSUE THREAD

**Issue by Fennecai** [ChaosInitiative/Portal-2-Community-Edition#354]
there should either be a utility that comes with the sdk, or have it somehow built into the engine itself, where- essentially- missing texture maps would be automatically derived from available ones where most suitable, in order to make materials look better when using the pbr shaders.

for example: if a material only has the diffuse texture, derive the normalmap from the diffuse the way photoshop plugins do- then after that's done, it derives heightmap from that. meanwhile also derives the specular, metallic, etc. from grayscaled/color-masked versions of the diffuse, all of which were in turn generated from specific parameters with the diffuse.

or another example: diffuse and normalmap are available but nothing else. the procedure is the same, except without the un-needed step of deriving the normalmap from diffuse, since we already have that.

another: somehow sombody's hard drive got corrupt and they only managed to save the normalmap. the engine (or tool) will just use a copy of the normalmap as it's diffuse texture (and warn the user about the diffuse being unavailable), then it'll do everything else in example 1- except, again, not the un-needed step of generating the normalmap from diffuse, since we have the normalmap anyways.

essentially this means that even if its not actually accurate (or for that matter, even nice looking sometimes), at least all materials have the option to look more finished and realistic rather than being simple flat textures with no other bump/shiny/etc. info attached

**Comment by TeamSpen210** [comment]
This isn't really possible, because PBR is a fundamentally different kind of rendering. The important ones are the metallic and roughness maps, which are entirely different maps that you can't get from anything else. It also needs the AO baked into a separate texture, not embedded in the diffuse.

The metallic map is a map which indicates for each pixel if the surface is a metal (reflecting light back like a mirror does), or a dialectic which diffuses it. The roughness map indicates how smooth/rough the surface is.

**Comment by BlightedLight** [comment]
On top of that, the idea itself would potentially break compatibility with vanilla textures. We will likely create a guide to authoring PBR materials at some point.

**Comment by Fennecai** [comment]
"impossible" ....even though i have literally done this quite a few times myself. i can even prove it if you'd like. I'm not gonna waste my time unless asked to though.

i work with substance suite; i know what maps do what, you dont need to explain it to me.

**Comment by BlightedLight** [comment]
If anything, it is more likely that the textures will look worse undergoing an automatic 'PBR' conversion. As this may create rendering artifacts or other problems, this won't be added.

**Comment by Fennecai** [comment]
it wont look worse. yits fine, it doesn't need to be added- i just dont like people saying things are impossible when i factually know otherwise. i edited my comment now to replace my un-necessary mean-ness with something possibly more useful.

**Comment by JJL772** [comment]
There are tools out there that accomplish this to an extent (MindTex is one that comes to mind, I've used it in the past and it works quite well). I don't see why we need to be the ones to implement this. It's not *too* difficult to port standard source textures to a PBR workflow either, it might take some time to do so manually, but you'll still need to check the converted textures before using them. 

Anyway, there are existing tools that sorta do this, and we don't want to spend time on this.
