### ISSUE TITLE
Port texture streaming from TF2

### ISSUE THREAD

**Issue by ghost** [ChaosInitiative/Portal-2-Community-Edition#355]
TF2 uses texture streaming to load weapon skins without precaching as to not make the game stutter. We could use this on all surface materials in a map as a means to speed up load times.

**Comment by JJL772** [comment]
Will this have any positive impact on performance though? Apparently CSGO's texture streaming doesn't actually improve game performance much at all, and I doubt Portal 2's environments are complex enough to actually benefit from texture streaming.

Regardless, it would be a cool feature to have for modders.

**Comment by BlightedLight** [comment]
I kinda find that hard to believe, surely it would create a positive perf impact?

**Comment by JJL772** [comment]
3kliksphilip did a benchmark on it: https://youtu.be/Ubdyf1LZBxo?t=252
Basically, the only map to see a significant performance improvement was de_dust2 (which had an improvement of 40fps). On other maps, the option had no effect. I'm not sure what's so different about dust2 compared to the other maps though.

**Comment by BlightedLight** [comment]
So he didn't compare load times? I can't watch the video right now.

**Comment by JJL772** [comment]
No he didn't. I might take a look at the internal filesystem implementation to determine if this feature would actually improve load times or not.

**Comment by JJL772** [comment]
Reddit thread about increased load times due to texture streaming: https://www.reddit.com/r/GlobalOffensive/comments/gke006/csgos_new_texture_streaming_setting_causes_slow/
This isn't an official benchmark or anything, so take it with a grain of salt. (Also note that the poster has CSGO installed on a normal HDD, so it's possible that texture streaming works better with SSDs)

**Comment by JJL772** [comment]
We are porting it from csgo now
