### ISSUE TITLE
Faster movement in P2CE than Portal 2.

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#356]
Here is a video that shows how you can somehow move faster in P2CE than vanilla Portal 2... Seems like you don't really lose velocity in P2CE... (left: Portal 2, right: P2CE)

https://youtu.be/6aw5BuQdqoU

**Comment by CitadelCore** [comment]
Can't reproduce on the latest version, so I'm closing this. Note that the fluctuations in Portal 2's velocity counter is because Portal 2 takes the jump velocity into account when calculating the length in cl_showpos, while CS:GO does not.
