### ISSUE TITLE
Weird behavior of falling physboxes on sp_a2_trust_fling

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#358]
Seems like the hinges are not breaking correctly? I looked at them with `ent_messages_draw 1` and it looks like they break... Maybe it's a problem with the entity that it has to constrain?

https://streamable.com/q3w0if

**Comment by L89David** [comment]
**UPDATE:** Seems like this entities are breaking after loading a save on that map. This means that they work perfectly fine if you play the map as normally, but if you do a quick save after entering the chamber and then load, you'll see the problem.

**Comment by CitadelCore** [comment]
Fixed.
