### ISSUE TITLE
Add math_calculator

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#361]
Add a logic entity that can perform basic 2 parameter math operations like
* Add
* Subtract
* Multiply
* Divide
* Modulo
* Power

and also single operator math operations like
* Root
* Absolute

and any others I forgot. 

Similar to logic_gate #265

**Comment by TeamSpen210** [comment]
Isn't this just `math_counter`?

**Comment by BlightedLight** [comment]
It seems so, wanna elaborate @SpyceTewan?

**Comment by SpyceTewan** [comment]
Not really. math_counter only stores 1 value, which is supposed to be incrementes or decremented. math_calculator has 2 inputs. A and B. Both can be changed whenever you want and the logic_calculator can output a value every time it changes. math_counter is really just for counting, math_calculator for any type of number calculation you may need

**Comment by TeamSpen210** [comment]
No, `math_counter` can do addition, subtraction, multiplication and division. You'd store the second value in another counter, and feed it to the first.

**Comment by RedstoneParadox** [comment]
Yeah, but performing an operation on the first `math_counter` changes the stored value, which means you need to reset it before performing a new calculation, then feed it the second number, and finally poll the first counter, which is 4 inputs and 2 entities. The proposed `math_calculator` does it with 1-2 inputs - depending on whether or not you're changing both values or just one - and 1 entity, making it simpler to set up.

**Comment by TeamSpen210** [comment]
Might just want to add MapBase's `math_counter_advanced`:
<https://github.com/mapbase-source/source-sdk-2013/blob/master/sp/src/game/server/logicentities.cpp#L2076>
It solves that with a `PreserveValue` key, which causes it to never alter the value set internally.

**Comment by SpyceTewan** [comment]
I already implemented it yesterday btw

**Comment by BlightedLight** [comment]
I agree, I think we should use Mapbase entities if they already exist, as some people may already be familiar with them.

**Comment by CitadelCore** [comment]
Let's try to integrate Mapbase where we can...

**Comment by Luke18033** [comment]
So what exactly is happening with this?

**Comment by CitadelCore** [comment]
Mapbase's version will be added
