### ISSUE TITLE
Error when save/loading while holding an object

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#365]
**(P2:CE)** I'll explain what i'm doing in video, so you can understand what i'm doing exactly. The steps here are corresponding to the timestamps in the video:

**1:** Here i'm placing a portal in that position at the ground, the second one doesn't really matter.
**2:** Now, I take the cube, and I position myself so the cube is on top of the first portal. Right next, I make a save, and then I load it.
**3:** I just move a bit to the right so the cube is not on top of the portal anymore. Right next, again, I make a save, and then I load it.
**4:** Now, I just move the cube away from the portals and I repeat the same process, save, and load.
**5:** Lastly, I just do the same thing, but while getting launched thanks to the faith plate.

https://youtu.be/ETcXO_prchE

**Comment by CitadelCore** [comment]
Should now be fixed
