### ISSUE TITLE
Faster movement while crouching in P2:CE

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#368]
This is is probably related to #356. Seems like in P2:CE you get more acceleration than in Portal 2. I made a map that lets you test it quickly by just typing `jesas_maria` in the console. [(test.zip)](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/5205660/test.zip)

Here's the video: https://youtu.be/Efx1liiQm9U (first one is Portal 2, second one is P2:CE)

**Comment by CitadelCore** [comment]
Seems like in P2 you take some time to come up to speed, but in P2CE it's instant.

**Comment by CitadelCore** [comment]
Fixed.
