### ISSUE TITLE
Feature: Improvements to the traceline API for vscript

### ISSUE THREAD

**Issue by LordVonAdel** [ChaosInitiative/Portal-2-Community-Edition#37]
Some ideas on how to improve the `TraceLine` function in vscript:
- Make it return the object that was hit
- Be able to specify collision masks
- Get information about the "hit point" like angle or position

**Comment by EchoesForeAndAft** [comment]
Tiny issue, should added to an over-arching "Improve VScript" issue that lists a bunch of functions that should be bound, like UTIL_TraceLine.
