### ISSUE TITLE
VRAD differences between p2ce and portal 2

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#372]
P2CE vrad compiles light far dimmer than Portal 2 does, which is a big issue since it makes maps that were mapped for portal 2 significantly darker

**Comment by L89David** [comment]
Very noticeable here for example: #277

**Comment by SpyceTewan** [comment]
No this has nothing to do with it. Also turns out i'm just dumb and didnt compile with hdr...
