### ISSUE TITLE
Starting a map twice crashes the game with volumetric projected textures

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#377]
If you are in a map with volumetric projected textures and load the map again or type restart, the game crashes

**Comment by BlightedLight** [comment]
I doubt these issues are related, I'd keep testing.

**Comment by Luke18033** [comment]
I also experienced a crash after the double-reload in Prototype's Adhesion maps. No idea if that's related, or if it would still happen in current builds.

**Comment by Luke18033** [comment]
That crash does still happen.

**Comment by CitadelCore** [comment]
Is this still an issue? I can't reproduce it.

**Comment by CitadelCore** [comment]
Closing, if you can reproduce it directly please re-open.
