### ISSUE TITLE
Wind in sp maps does not work

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#378]
The wind on the leaves does not work on any map of Portal 2. I don't know if it's a problem with `env_wind` or with the material flag.

**Comment by SpyceTewan** [comment]
Can you try running Enable on the env_wind?

**Comment by CitadelCore** [comment]
Fixed. Tewan's wind change added an "Enabled by default" spawnflag. This has been reverted to "Disabled by default".

**Comment by SpyceTewan** [comment]
Playing with wind can sometimes cause some slight hickups :)
