### ISSUE TITLE
Different model fade distance.

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#379]
Example taken in `sp_a1_intro1` Notice how a lot of models dissapear at the distance sooner in P2CE.

**Portal 2:**
![20200913202938_1](https://user-images.githubusercontent.com/48654552/93025693-639eb600-f600-11ea-9a34-f86a54621913.jpg)

**P2CE:**
![20200913203155_1](https://user-images.githubusercontent.com/48654552/93025698-6e594b00-f600-11ea-935c-cddbe09e1a6f.jpg)

Also note how the lighting is more dummier in P2CE.

**Comment by CitadelCore** [comment]
This isn't a problem, CS:GO disables LOD and fade at the highest GPU levels. Open another ticket for the lighting issues.
