### ISSUE TITLE
Weird shadows on water in sp_a1_wakeup

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#380]
This is probably caused in more maps with this water material. As you can see, the shadows of the nearby props are behaving weirdly:

**Portal 2:**
![20200913204746_1](https://user-images.githubusercontent.com/48654552/93025962-a6618d80-f602-11ea-8169-f63c1181baeb.jpg)

**P2CE:**
![20200913204642_1](https://user-images.githubusercontent.com/48654552/93025973-b7aa9a00-f602-11ea-8242-603a7e12a576.jpg)

**Comment by CitadelCore** [comment]
write depth to dest alpha on the phong shader being disabled likely breaks this

**Comment by SpyceTewan** [comment]
That water looked weird in a custom map of mine too, can confirm.

**Comment by CitadelCore** [comment]
Fixed.
