### ISSUE TITLE
Add a warning message before using carve in hammer

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#382]
About the carve tool. I've seen a lot of new mappers using it without knowing all the problems it does currently have. To be honest, I don't know how complex it would be to maybe add a warning message if you want to carve using complex shapes... Or just completelly remove it.

**Comment by Luke18033** [comment]
Maybe show a warning message if you try to carve with a solid that has more than 6 faces or something?

**Comment by SpyceTewan** [comment]
That sounds good

**Comment by SpyceTewan** [comment]
![image](https://user-images.githubusercontent.com/31664665/105638234-d868e300-5e71-11eb-887d-d896b34fc979.png)

**Comment by SpyceTewan** [comment]
You can disable this in the options!
