### ISSUE TITLE
Fixes for the radius culling option

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#383]
* It would be appreciated if you could fix the insane amount of lag that this option brings with it.
* Make it so this tool only hides objects from the viewports, but don't completely hide them from the map (causing possible leaks)
* Do we really need a hotkey for this option? I've seen a lot of people struggling when activating it accidentally.

**Comment by SpyceTewan** [comment]
Radius culling will be removed. It doesnt have any advantages and only slows down hammer
