### ISSUE TITLE
Path Tool

### ISSUE THREAD

**Issue by DarviL82** [ChaosInitiative/Portal-2-Community-Edition#384]
In the Half-Life SDK, we had the Path Tool, a tool that allows to create paths easily, by just drawing in the 2D viewports our lines. What if we had this tool again? It would be nice if it could be improved to be able to make curves automatically.

![image](https://user-images.githubusercontent.com/48654552/93120717-0e2bdd00-f6c4-11ea-8801-b69622e8e713.png)

**Comment by AWildErin** [comment]
Superseded by https://github.com/ChaosInitiative/Chaos-Source/issues/467
