### ISSUE TITLE
Enable the unused "Entity Logical View" viewport

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#386]
Currently, we can only access to this viewport by modifying the config (possible with VIDE too)... Just adding it in the viewport selection dropdown would do the work.

**Comment by Luke18033** [comment]
Basically a duplicate of #278 (I made this suggestion to add it, was told it was a duplicate so I changed it to just the improvements, then the original issue was closed)

**Comment by L89David** [comment]
Alright, closing it 👌
