### ISSUE TITLE
Bug: Hammer shows instance IO as errors

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#390]
What I mean by doing this, is mostly some kind of way to prevent hammer to show our instance I/O as incorrect when setting it up. So hammer could detect if the Outputs will work correctly inside the instance by checking the `func_instance_io_proxy` in it.

**Comment by Luke18033** [comment]
Hammer clearly already knows about these since it's able to auto-complete them, so I can't imagine it would be too difficult to make them show up as valid?

**Comment by SpyceTewan** [comment]
Fixed https://youtu.be/HYR4UBtIdDk
