### ISSUE TITLE
Disable laser collision keyvalue breaks after redirection

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#392]
If a laser's collision is forced off using the keyvalue, the collision will still be enabled after the laser is redirected using a cube. Passing through portals works fine. I haven't tested Reflection Gel.

**Comment by SpyceTewan** [comment]
Seems like the value doesnt get carried over to the new laser. Easy fix.

**Comment by SpyceTewan** [comment]
Fixed
