### ISSUE TITLE
Hammer Icons Are Tiny In 4k

### ISSUE THREAD

**Issue by Mystical-Ace** [ChaosInitiative/Portal-2-Community-Edition#393]
Only affects P2:CE Hammer, Portal 2 and CS:GO Hammer are normal. 

![image](https://user-images.githubusercontent.com/44247063/93517851-406a5400-f8e9-11ea-9ffd-166ed8652f13.png)
How it should look

![image](https://user-images.githubusercontent.com/44247063/93517933-5aa43200-f8e9-11ea-819a-cadfb9470432.png)
How it looks 

![image](https://user-images.githubusercontent.com/44247063/93518054-8a533a00-f8e9-11ea-9c35-34221a8330f1.png)
Scaling Factor

**Comment by SpyceTewan** [comment]
Fixed
