### ISSUE TITLE
Loading a save in a workshop map kicks you to the menu

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#394]
The title says it all. In Double Decker Laser, the console reports this error:
```
CModelLoader::Map_IsValid:  No such map 'maps\workshop\1636452068648517094\sp.bsp'
Map 'workshop/1636452068648517094/sp' missing or invalid
Save file SAVE\76561198067086340\quick1.sav is not valid
```
It seems like map names are now being limited to 32 characters in length, which is not the case in the base game. Workshop maps usually have longer names than that as a result of being placed in a randomly-numbered folder.

**Comment by CitadelCore** [comment]
Fixed.
