### ISSUE TITLE
Add the "env_terrainmorph" entity

### ISSUE THREAD

**Issue by DarviL82** [ChaosInitiative/Portal-2-Community-Edition#395]
I only saw this entity working on that Half-Life 2 demo a long time ago... I got really impressed when I saw it for the first time... Would be possible to have it in Portal 2?

* **VDC Page: https://developer.valvesoftware.com/wiki/Env_terrainmorph**

* **Demo Video (timed): https://youtu.be/4ddJ1OKV63Q?t=107**

**Comment by TeamSpen210** [comment]
The code in the engine half of the game for it got ripped out/broke a long time ago, I don't think it's that workable. Especially note how there's no collisions.

**Comment by SpyceTewan** [comment]
The collision hull bug has already been fixed by people and documented [here](https://developer.valvesoftware.com/wiki/Morphing_Terrain_Issues)

This is possible to implement, but not a priority at the moment.

**Comment by JJL772** [comment]
The code for deformable displacements is broken, and it's done in a naive way afaik (recreating the entire displacement each frame). So this is a wontfix.
