### ISSUE TITLE
Fizzling a reflection cube that is reflecting a laser crashes the game

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#397]
The title says it all.

**Comment by Luke18033** [comment]
Here's the minidump.
[crash_chaos.exe_20200918205956_1.zip](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/5249104/crash_chaos.exe_20200918205956_1.zip)

**Comment by CitadelCore** [comment]
Fixed.
