### ISSUE TITLE
Add a "Reset to Default" button on the Properties Window

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#398]
Basically, a button that if you press, it'll reset all the keyvalues of the selected entity to the default values. Would be nice that if you press it while being on the keyvalues page, reset the keyvalues. If you are on the flags page, only reset the flags. (Same with the rest pages). Consider adding a warning dialog box asking if the user really wants to reset to default (in case someone presses it accidentally)

**Comment by SpyceTewan** [comment]
Done.
