### ISSUE TITLE
Implement parallax mapping

### ISSUE THREAD

**Issue by MisterDigitalGuy** [ChaosInitiative/Portal-2-Community-Edition#399]
yeah

**Comment by SpyceTewan** [comment]
please give more info than "yeah" and stop spamming our issues with useless info

**Comment by Luke18033** [comment]
According to the VDC, unfinished parallax mapping support already exists in the engine, which you might want to look into. A search for `parallax` turns up a few useful results.

**Comment by SpyceTewan** [comment]
We expect issue writers to put _some_ kind of effort into their descriptions. If you can edit your comment and give more info on _what_ you want implemented and _how_, this issue will be reopened

**Comment by Luke18033** [comment]
My comment, or the original post?

**Comment by SpyceTewan** [comment]
I'm referring to the issue author
