### ISSUE TITLE
prop_vehicle_choreo_generic - teleporttoeyes input

### ISSUE THREAD

**Issue by Valla-Chan** [ChaosInitiative/Portal-2-Community-Edition#404]
Add the input “TeleportToEyes” to prop_vehicle_choreo_generic, that would would work similarly to how the output does on a point_viewcontrol. (exits the camera/vehicle and immediately puts the player’s eyes and body in the same position, rather than interpolating)

**Comment by CitadelCore** [comment]
Implemented this as a spawnflag "Keep Player Position".
