### ISSUE TITLE
view height cvars

### ISSUE THREAD

**Issue by Valla-Chan** [ChaosInitiative/Portal-2-Community-Edition#405]
add 2 cvars to specify the height the camera is at when the player stands or crouches.

**Comment by CitadelCore** [comment]
I've added v_view_height, v_view_height_ducked, and v_view_height_dead, defaulting to 64, 28, and 14, respectively. Note these currently need to be set before map load (or map reloaded between changes) to take effect, and they work for singleplayer only.
