### ISSUE TITLE
Tewan does NOT have games on his phone

### ISSUE THREAD

**Issue by Joshua-Ashton** [ChaosInitiative/Portal-2-Community-Edition#408]
Please fix this. I want to play games on his phone.

**Comment by Luke18033** [comment]
???

**Comment by FrozenDragon0** [comment]
Is this a joke? Because it's a pretty shitty joke.

**Comment by Luke18033** [comment]
I'm not sure what the "joke" even is.

**Comment by NoNameToPut** [comment]
Check #off-topic

**Comment by CitadelCore** [comment]
This conversation doesn't need to continue. Locking.
