### ISSUE TITLE
Reintroduce weapon_cubemap

### ISSUE THREAD

**Issue by kittymatthew** [ChaosInitiative/Portal-2-Community-Edition#411]
I'm not sure how hard it will be, but it has been very useful in past engine branches for assessing the cubemap situations. Unfortunately, it's not implemented in P2, CS:GO, and some other newer branches. Reintroducing this would make cubemap testing much easier.

**Comment by Luke18033** [comment]
It is implemented, I have used it before in both P2 and P2CE. You need to port the model and materials though.

**Comment by kittymatthew** [comment]
Oh that’s awesome that it’s already implemented - thanks for letting me know!

**Comment by EchoesForeAndAft** [comment]
@CitadelCore Let's make sure we ship the models and materials for this in the next update.

**Comment by CitadelCore** [comment]
Done.
