### ISSUE TITLE
Fix cubemap compilation

### ISSUE THREAD

**Issue by kittymatthew** [ChaosInitiative/Portal-2-Community-Edition#412]
Currently(in Portal 2, at least), you need to compile cubemaps with the map in portal2_dlc2/maps.
Running buildcubemaps when it's in portal2/maps crashes the game. It would be useful to all cubemaps to be built inside of the portal2/maps folder. I've had some headaches trying to find the latest version of my map, seeing if it was in dlc2 or portal2.

**Comment by SpyceTewan** [comment]
P2ce isnt portal 2

**Comment by kittymatthew** [comment]
Doesn't the issue still happen within mods though?

**Comment by SpyceTewan** [comment]
This isnt an issue in p2ce

**Comment by kittymatthew** [comment]
Ah okay, I wasn't aware of that.

**Comment by SpyceTewan** [comment]
Please dont just assume that p2ce has a bug and always discuss issues in #suggestion-discussion on discord first

**Comment by kittymatthew** [comment]
Alright, sorry
