### ISSUE TITLE
Game crashes while shooting second portal (by seocnd I mean I already shooted one) (Windows 7)

### ISSUE THREAD

**Issue by Paladiumer** [ChaosInitiative/Portal-2-Community-Edition#416]
No matter which level I'm in, when I shoot a second portal the game crashes (and even at the beginning when the announcer opens the portals it crashes too). I am running Windows 7 and I don't plan to upgrade to Windows 8 or 10 because my computer is a bit too old.

**Comment by CitadelCore** [comment]
I have never experienced this issue in the base game. I would advise verifying the game cache or upgrading your OS. This is something that would be impossible to debug, so I am closing it.

**Comment by Luke18033** [comment]
Try messing with your graphics settings maybe? I remember someone had a crash with portals when on low shader detail. Worst case scenario, setting `r_portal_stencil_depth 0` will disable seeing through portals entirely - it won't look very good, but should at least fix the crash.

**Comment by Paladiumer** [comment]
Actually disabling the "see through portals" thing worked, so thanks

**Comment by SpyceTewan** [comment]
Windows 7 isn't supported my microsoft any more so neither should we
