### ISSUE TITLE
script command is not a cheat

### ISSUE THREAD

**Issue by DrMeepster** [ChaosInitiative/Portal-2-Community-Edition#418]
The `script` command should be a cheat. It lets you do a very large amount of cheaty things

**Comment by Luke18033** [comment]
What does it do?

**Comment by DrMeepster** [comment]
`script` lest you execute arbitrary vscript. Ex: `script printl("hoho")`. Also I forgot to mention, `script_execute` should also be a cheat. It lets you run script files.

**Comment by Luke18033** [comment]
Oh yeah that should definitely be a cheat. Couldn't you do `script SendToConsole("some_other_command")` to execute other cheat commands as well?

**Comment by DrMeepster** [comment]
No, `script SendToConsole("noclip")` gives an error with cheats off

**Comment by EchoesForeAndAft** [comment]
Many commands should be cheats and are not, and sv_cheats can be quite annoying. Maybe we could could allow sv_cheats to be implicitly set when executing cheat commands?

**Comment by Valla-Chan** [comment]
Um, no, this isn't a bug. I use this extensively in Valhalla and "fixing" this to be a cheat would be a huge nuisance. This is like forcing ent_fire to be a cheat in single player, it would break basically any complex hammer maps that use it, just to gatekeep achievements.

**Comment by CitadelCore** [comment]
SendToConsole respects sv_cheats. Closing.
