### ISSUE TITLE
p2 bug: portalgun's holding sounds stop unexpectedly when holding object with drop disabled

### ISSUE THREAD

**Issue by Fennecai** [ChaosInitiative/Portal-2-Community-Edition#420]
When holding a personality sphere with the portalgun, if the sphere has disabled the ability to drop it, the gun's looping sounds will stop when pressing the USE key as if you had actually dropped the sphere- even though the animations still loop and particles still play as expected.

**Comment by CitadelCore** [comment]
Fixed
