### ISSUE TITLE
Water screen overlay appears on respawn after death in water

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#423]
If you die in water and respawn, a water overlay animation appears on screen.

This issue exists in csgo as well

**Comment by Luke18033** [comment]
Duplicate of #183 (in which I stated in a comment that the bug was still present, and was ignored)

**Comment by CitadelCore** [comment]
This is fixed for good now. Cvars have been un-marked as cheat.
