### ISSUE TITLE
play soundscapes from within hammer

### ISSUE THREAD

**Issue by Fennecai** [ChaosInitiative/Portal-2-Community-Edition#428]
soundscapes (and by extent, soundscripts) should be made to preview properly in hammer, rather than only playing the first sound or not at all.

it would be great instead of having to use an [external soundscape player](https://github.com/HUNcamper/soundscape_player) or having to use ``playsoundscape`` a bunch in-game to find that perfect ambience.

**Comment by distributivgesetz** [comment]
Merging this issue to ChaosInitiative/Chaos-Source#187.
