### ISSUE TITLE
Add point_gel_sensor entity

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#43]
This would be able to detect specific types of gel applied to surfaces. It could either detect the gel on any surface within a radius around the entity, or detect it on specific brush faces. See #42 for detecting gel flow.

TeamSpen even made an iconsprite for this already.
![point_gel_sensor](https://user-images.githubusercontent.com/19228201/84316039-5795ea80-ab1f-11ea-87f7-a60eb63e31f9.png)

**Comment by CitadelCore** [comment]
I've implemented this, with a search radius, target entity and support for a filter - however I haven't implement target brush face selection yet as there isn't a clear correlation between the brush face IDs in Hammer and the ones in-engine. I'll look at this as a seperate issue later; but for now hopefully the radius should be enough to get by.
