### ISSUE TITLE
The restart_level command

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#430]
Currently, there is an undocumented console command called `restart_level` that well... It restarts the level. However, if you use it, there is no autocompletion (so its like the command does not exists) and after pressing enter, the console prints that the command does not exist, but it gets executed anyways... In vanilla Portal 2, `restart` caused some problems, so maybe that's why this command exists?
So, maybe consider mixing `restart_level` into `restart`?

**Comment by TeamSpen210** [comment]
The puzzlemaker actually uses it to restart the level when reaching the exit corridor, in preview mode.

**Comment by CitadelCore** [comment]
Yeah it's used in multiple places internally.
