### ISSUE TITLE
Port improvements from SCell555/sdk-2013-hammer

### ISSUE THREAD

**Issue by EchoesForeAndAft** [ChaosInitiative/Portal-2-Community-Edition#432]
Currently looking at moving improvements from specific commits in SCell555's branch of Hammer into ours.

Specifically, these:
https://github.com/SCell555/sdk-2013-hammer/commit/242926f7e44d0404307aebad0624898a7e9ebff5
https://github.com/SCell555/sdk-2013-hammer/commit/d6b2ad86abb538ee41cb810e67f225e032d6dfd3
https://github.com/SCell555/sdk-2013-hammer/commit/32bb0d7fc04ec10cb8734a5a8d4ae325d1cf2873
https://github.com/SCell555/sdk-2013-hammer/commit/3a33bea55922ea08f6cb298ba9d50cb26fc0bf75

**Comment by SpyceTewan** [comment]
Done
