### ISSUE TITLE
[Hammer] Instance boundary extends to fit sprites

### ISSUE THREAD

**Issue by koerismo** [ChaosInitiative/Portal-2-Community-Edition#437]
Instance boundaries will extend to fit scaled sprites, making the 3d viewport very crowded

**Comment by SpyceTewan** [comment]
That's what a bounding box is for though

**Comment by koerismo** [comment]
I don't believe that sprites should be counted as a solid object though, besides the sprite origin

**Comment by SpyceTewan** [comment]
No reason why there should be a special case for this
