### ISSUE TITLE
Custom Loading Screens for Workshop Maps

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#44]
Currently there are only the options of `sp_a1`, `sp_a2`, `sp_a3` and `sp_a4` for workshop maps, and being able to add some kind of similar preview would be pretty nice.

**Comment by ENDERZOMBI102** [comment]
Can be used with [this](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/53)

**Comment by ozxybox** [comment]
Superseded by https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/928.
