### ISSUE TITLE
[Hammer] vgui_movie_display uses .bik presets

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#440]
With Smart Edit on, when selecting our movie to display in the `Movie to display` keyvalue, the preset options will point to the respective `.bik `files, instead of the recently implemented `.webm` videos.

**Comment by SpyceTewan** [comment]
Wrong repo https://github.com/ChaosInitiative/P2CE-FGD

**Comment by L89David** [comment]
I can't submit issues to that fork, and if I do to TeamSpen's repo wouldn't make too much sense because he is developing it for Portal 2, not p2ce right? Sorry if I'm misunderstanding.

**Comment by CitadelCore** [comment]
You should be able to create issues now.

**Comment by L89David** [comment]
Thank you 👌
