### ISSUE TITLE
Trigger_teleport breaks player hitboxes

### ISSUE THREAD

**Issue by Nidboj132** [ChaosInitiative/Portal-2-Community-Edition#446]
When player gets teleported by trigger_teleport the player bounding box gets separated from camera box depending on the angle where the player was looking while getting teleported, separated hitbox has extremely unnatural behavior on other props or even walls, save loading, going through portal and crouching can reset hitboxes back to normal.
Video: https://cdn.discordapp.com/attachments/771063726555660312/771335808165609492/2020-10-29_12-27-10-1.mp4

**Comment by CitadelCore** [comment]
Fixed.
