### ISSUE TITLE
Feature: Restored Hover Turret NPC

### ISSUE THREAD

**Issue by Wolfcl0ck** [ChaosInitiative/Portal-2-Community-Edition#451]
## Which component should be improved?
Gameplay

## Describe your suggestion
The Hover Turret (also called lazer turret) was a cut npc from Portal 2 and is theorized to have been a progression of the rocket turret. It came with two separate entities, the main npc itself (npc_hover_turret) and some sort of tether that the turret would have hung off of (ent_hover_turret_tether.) Neither of these entities have any FGD information in the final game, but some information is known about each:

(The following block of information is explicitly for if the development team of P2CE does not have repository access and cannot acquire the original Hover Turret model, so as to be able to remake it)
The hover turret used a model called models/npcs/hover_turret.mdl
The hover turret's model was that of the Portal 1 core
The hover turret included four different Skins, each corresponding to a different core from Portal 1
The skins were as follows: Skin 1 - Morality, Skin 2 - Curiosity, Skin 3 - Anger, Skin 4 - Intelligence

Gameplay:
The Majority of the hover turret's gameplay is still functional if a modded model is used, however here are a number of issues that need to be fixed:

The Hover turret's laser goes invisible when firing at the player (in its leftover screenshot in the final hours of Portal 2, the hover turrets firing on the player still have visible lasers. In the final game, the laser is visible when searching for the player, but disappears when actually firing.)

When picked up by the player, the turret's eye glow turns purple, implying that it should be switching to skin 1. However, it switches to skin 3 instead. It's known that skin 1 is absolutely morality and skin 3 is absolutely anger, because the turret will sometimes go into frenzies, shaking violently on the ground and being unable to be picked up, and this gameplay sets the turret's eye glow to red *and* sets the skin to skin 3. This may be because the turret is supposed to have a "melee attack" when the player is too close, which may be overriding the proper behavior.

The dedicated tether entity (ent_hover_turret_tether) is unusable simply because it is unknown what would have been included in its fgd. When a hover turret is tethered to a ceiling with a regular rope entity, it appears to not function as expected, which implies that ent_hover_turret_tether would have done something in order to keep the turret balanced and able to focus on the player. If the code for this entity can be found, this FGD info can be engineered from it.

Portal 2 includes a soundscript file for the Hover Turret. Every single sound in this sound script is missing, unfortunately. However, if the P2CE team has repository access, they may have access to these sounds and can reimplement them. If not, I may have found a very small handful of sounds that the hover turrets had used by going through a number of different CSGO builds. [Here](https://www.youtube.com/watch?v=DjnBDIvkhFA) is a video I had made showcasing the 3 sounds I had found for the hover turret. In addition, I also made [this](https://www.youtube.com/watch?v=4SlsOCirXyI) video detailing my discoveries concerning the hover turret's various skins.

## Expected result
The hover turret is restored and functions as it would have, had it been implemented in Portal 2, as opposed to being scrapped. Its two entities should be available in the FGD for map makers to use.

Additional notes: I have recreated the hover turret's model, complete with its 4 different skins and its acts, based off of a previous attempt at recreating it done by some other users. If the P2CE devs can't get the original model, [here](http://www.mediafire.com/file/ntjvlwqje5lub1r/Hoverturretfixv2.zip/file) is the fix I had made, which theoretically should work exactly as intended.

![justiceforhoverturrets](https://user-images.githubusercontent.com/16748747/98642043-5ba67e00-22f2-11eb-9a3d-17b3a17abd86.png)

**Comment by JJL772** [comment]
This might be possible to implement using only vscript. We might need to expose APIs for firing projectiles or something though.

**Comment by SpyceTewan** [comment]
We told you before that we won't do this

**Comment by Wolfcl0ck** [comment]
And here I had my hopes so high. In the least, can you tell me if the tether entity inherits off of another entity so I can make an fgd entry for it to see it ingame?
Also, I'm not sure who it was you told that you wouldn't do this, but it wasn't me, I looked around to see if anyone had made any mention of this before and I couldn't find anything.

**Comment by Wolfcl0ck** [comment]
And here I had my hopes so high. In the least, can you tell me if the tether entity inherits off of another entity so I can make an fgd entry for it to see it ingame?
Also, I'm not sure who it was you told that you wouldn't do this, but it wasn't me, I looked around to see if anyone had made any mention of this before and I couldn't find anything.
