### ISSUE TITLE
Logical View background color is bugged

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#457]
### Describe the bug
The color scheme in the logical view is bugged, appearing as a weird grey color when first enabled before changing to the selected 2D view color when resizing the grid.

### To Reproduce
1. Open map
2. Switch to the logical view
3. Observe that the background color is grey
4. Resize the grid with `[]`
5. Observe that the background color is now black or white, depending on the selected 2D view color scheme

### Expected behavior
The logical view background should default to the 2D view background color.

**Comment by Luke18033** [comment]
Actually, instance I/O getting marked as invalid would probably be a bug itself.

**Comment by SpyceTewan** [comment]
Fixed
