### ISSUE TITLE
Bug: Some videos on vgui screens around elevators are stretched

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#460]
### Describe the bug
Some videos on the elevator VGUI screens are stretched severely. See sp_a2_intro for an example of this.

### To Reproduce
1. Open sp_a2_intro
2. go to the elevator at the end

### Expected behavior
Elevator videos shouldn't be stretched

### Operating System (Optional: Only if OS Specific)
 - OS: Linux, probably others, but only tested on Linux.

![sp_a2_intro0002](https://user-images.githubusercontent.com/19717056/99154881-035fdb00-2668-11eb-902b-1caa9d7011e5.jpg)
![sp_a2_intro0001](https://user-images.githubusercontent.com/19717056/99154882-04910800-2668-11eb-95bc-3db2c21d4886.jpg)

**Comment by SpyceTewan** [comment]
That's interesting. Seems like a videosplitter bug. Any vscript errors in console?

**Comment by JJL772** [comment]
Not that I am aware of. I will take a closer look at this soon, but I've got some other bugs to tackle first.

**Comment by TeamSpen210** [comment]
This is intentional, there's various randomised splitting options available. For Overgrown several additional "broken" ones are added to the mix.

**Comment by CitadelCore** [comment]
Since this is intentional I'm closing the issue.

**Comment by SpyceTewan** [comment]
Yeah there are splitting options that stretch it like this, but those shouldn't play in clean chambers? Which map is that?
