### ISSUE TITLE
vgui_movie_display fails to play videos with audio

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#464]
### Describe the bug
WEBMs with audio fail to play from `vgui_movie_display`. They work fine as fullscreen videos.

### To Reproduce
1. Place `vgui_movie_display`
2. Set video to `media/attract_panels.webm` (or any other video with sound)
3. Compile the map and activate the movie display

### Expected behavior
In base P2, the video will play normally, with the audio heard everywhere in the map. Alternatively, it might be better to just disable the audio entirely, or make it toggleable with a flag.

Ideally, the sound would properly emit from the movie display, but I'd imagine there's some technical reason why that isn't done.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows

**Comment by SpyceTewan** [comment]
Fixed
