### ISSUE TITLE
P2 bug: vgui_movie_display videos restart when unpausing the game

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#465]
### Describe the bug
The title says it all. Combined with #464, this makes it impossible to practically display videos with sound in the world, as pausing the game will cause the video to become desynced from an ambient_generic playing the audio.

### To Reproduce
1. Play any video on a vgui_movie_display (elevator videos work for this but it's more noticeable with longer videos)
2. Pause the game
3. Unpause the game
4. Video restarts

### Expected behavior
The video should resume from where it was when the game was paused.

**Comment by SpyceTewan** [comment]
Can confirm I've experienced this before

**Comment by SpyceTewan** [comment]
Fixed
