### ISSUE TITLE
Hammer Improvements/Fixes

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#47]
_I think you have this planned. Tell me if you need me to be more specific on something..._

> * Fix Carve Tool.
> * Fix the Radius Culling Tool.
> * Bring the Path Tool back again.
> * Make the `Create new Instance from Selection` dialog to work.
> * Entity logical view viewport mode.
> * Similar Lighting preview viewport mode. (Fix the included one)
> * Keymap editor (be able to change keybinds)
> * Language selector (I can help with Spanish :D)
> * Theme selector, be able to make your own themes.
> * Bring `Show Walkable Surfaces` button from csgo sdk.
> * Make instances to show as normal, instead of tinted by default.
> * Save 3D viewport camera FOV user config.
> * Don't show instance IO/attachment points as incorrect in hammer.
> * Movement preview for brush entities. (Maybe showing a bounding box moving with the speed set?)
> * Fix the print tool.
> * Be able to preview voice lines, depending on your game language.
> * Make the publisher be part of hammer.
> * Be able to change `modelscale` not only on `$staticprop` models. Generate a preview in hammer of the new scale.

**Comment by SpyceTewan** [comment]
Hammer will either be scrapped or remade from scratch. We can't stand hammer's ancient code

**Comment by L89David** [comment]
Oof. Alright got it.

**Comment by Luke18033** [comment]
I'd say the same about a Puzzlemaker rewrite. It'd be better to make it a standalone open-source application, rather than hardcoding it into the engine.

**Comment by SpyceTewan** [comment]
Hammer or puzzlemaker rewrites would probably be done in panorama

**Comment by AddMGH** [comment]
I would be 100% happy with a hammer rewrite, as long as it functions the same and has some of the features seen in Source 2, such as the in-game lighting, but not with the faces system, as that goes too far.

**Comment by BlightedLight** [comment]
Hammer will probably receive minimal new features, as Tewan said we can't stand Hammer's ancient code. Prepare for some kind of new mapping tool probably, hopefully. Some improvements you can expect in Hammer is multi-sample anti-aliasing and DPI scaling (fixes blurriness on higher-resolution monitors) and maybe transformation gizmos.

**Comment by SpyceTewan** [comment]
Make these individual issues
