### ISSUE TITLE
Feature: Integrate the Source Shader Editor

### ISSUE THREAD

**Issue by TeamSpen210** [ChaosInitiative/Portal-2-Community-Edition#472]
## Which component should be improved?
Render

## Describe your suggestion
The [Source Shader Editor](https://github.com/Biohazard90/source-shader-editor) is an addon that provides node-based shader creation for users, without requiring them to have code access. See also the [VDC](https://developer.valvesoftware.com/wiki/Category:SourceShaderEditor) pages. There's instructions there on how to patch it in, though you'll have to tweak that to accommodate for the closed-source engine changes.

## Expected result
Users would then be able to develop their own simple shaders to implement specific situations that can't be done by the normal generic shaders.

**Comment by JJL772** [comment]
This is cool in theory, but not so much in practice, at least for the people who have to implement it :P 

I've only worked with SSE briefly, but I can see that it'd need some refactoring to work with our shadercompile and shader model 5 (dx11) shaders. If we had a huge team and more time, we would totally fork and maintain SSE, but vgui is deprecated at this point, and we don't have the time to update and maintain an editor last touched in 2015. 

I'd also like to note that we *do* have improvements planned for the shader system in the future. We want to allow for custom HLSL shaders to be loaded by the engine and backed by rendering code written in C#, but that's a long way off.
