### ISSUE TITLE
Feature: Add Sixense support from the MotionPack/Perceptual Pack

### ISSUE THREAD

**Issue by Nanoman2525** [ChaosInitiative/Portal-2-Community-Edition#474]
## Which component should be improved?
Gameplay, Razer Hydra/VR controller support, features for mouse/keyboard.

## Describe your suggestion
I feel like adding Sixense support to P2CE can be a good thing, since it natively provides full support for motion controllers. This can pave way into making VR support in the later future. Not only this, but mouse/keyboard integration could also be added to increase availability to all players.

I also think that when creating the workshop for this game, there could be a different category for Sixense maps that make use of the features.

## Expected result
If the support is implemented, there could be options in the menus that allow you to toggle Sixense features on or off. The unique mechanics offered in the Sixense content could be more enjoyable for all players, and make the game a lot more fun.

**Comment by SpyceTewan** [comment]
We don't have sixense code

**Comment by JJL772** [comment]
@SpyceTewan The Sixense SDK on steam contains all the headers and DLLs required to support the Razer Hydra.

**Comment by JJL772** [comment]
Oh, I see what you mean. Hm, yea this would be a lot of work since we'd need to re-implement the advanced portal gun and all of those extra gameplay mechanics. 
Think it's fair to leave this as wontfix. We lack the manpower to allocate resources to re-implement a bunch of mechanics for a relatively niche controller.

**Comment by SpyceTewan** [comment]
Yeah. I think you can't even buy that thing any more so spending all that work on a nieche feature just doesn't fit into our time budget.
