### ISSUE TITLE
Bug: Game crashes when loading new map (Linux) [Updated]

### ISSUE THREAD

**Issue by Paladiumer** [ChaosInitiative/Portal-2-Community-Edition#477]
NOTE: this issue got updated after I got my new computer

Game crashes when trying to load a new level (didn't have time to confirm it yet)

To reproduce:
launch any map
Complete a level
the game crashes when loading next map

Expected behavior:
Doesn't crash and the player can continue 

Operating System:
Linux (Ubuntu 20.04 with stock kernel)

Part for JJI77 on Discord (he told me to create this issue and mention him so the issue doesn't get closed):

PC Config: Macbook Pro 15inch mid-2015 Intel Core I7 4980HQ 2.8GHz (turbo 4GHz), 16GB 1600MHz RAM, AMD R9 M370X, screen 2880x1800

**Comment by JJL772** [comment]
[glxinfo.txt](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/5654438/glxinfo.txt)

(Went ahead and uploaded glxinfo as a file)

**Comment by JJL772** [comment]
Closing this issue since the person who opened it no longer owns the problematic system, so we can't debug it. For anyone who may be having a similar issue: please open a new issue or comment on this one.
