### ISSUE TITLE
Feature: TWTM Esc Recording Mechanics

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#479]
## Which component should be improved?
A recording mechanic similar to TWTM but with mechanical and technical improvements

## Describe your suggestion
I've talked to many people who like the idea of TWTM but can't make maps for the mod because the mechanics are logically inconsistent and the stability of the mod itself is pretty flimsy. Having a hardcoded version of the TWTM clipboard with a more clear ruleset that isn't broken half the time would allow for people to make pretty interesting puzzles

The problems with TWTM:
Without talking too much into how there is a chance the mod will just crash you when loading a save, the mechanics of TWTM don't always function as intended and even when they do its not consistent with other mechanics. Examples of this would be that objects carried by the recording are not physical and will pass through the world including fizzlers. This however can be avoided if the cube is carried through the fizzler while the fizzler was turned off at the time of recording. This feature isn't consistent and sometimes objects will go through barriers when it should seem like they should not. Also objects picked up by a recorded player that are standing on the other side of a fizzler will be teleported to the other side thus allowing people to bypass fizzlers entirely.

My suggestions:
Through discussing different alternatives with others, here is the ruleset I've come up with to make designing puzzles with this mechanic way better. The recorded player should not be able to be interacted with the world. This means if you record yourself floating in a funnel and then play the recording when the funnel is then off, the recorded player will float as if the funnel was there. Any objects held by the recorded player should still behave like objects in the world. That means if the recorded player goes through a wall while holding an object, the object will be dropped. Also fizzlers will fizzle held objects. Portal management is in a grey area but I think when consistent will make sense. The recorded player will not be affected by fizzlers in real time but the recording will remember when the real time player walks through an active fizzler and fizzle the portals. Lastly the way TWTM handles the use input should just be redone so that its a generic action that can do anything the use key can. In TWTM the use key records the specific action that was done in real-time so picking up a cube would only be picking up a cube in the recording and not other use actions.

As an added thing, there should be a way to control recordings through hammer inputs and outputs. Events such as starting a recording, stopping a recording, starting playback, stopping playback, deleting a playback. Most likely should have an entity that handles all this, this way we can both force these actions in hammer but also detect them if we need to for some reason. Also make sure that the recorded player itself can be detected with triggers and is able to be filtered properly.

## Expected result
A stable and more functionally consistent version of TWTM that has clear defined rules, more diversity in both puzzle design and map design.

**Comment by Luke18033** [comment]
I'd imagine this is the kind of thing you'd use ChaosScript for, once that's implemented.

**Comment by koerismo** [comment]
This is one of those things that I would hope to be possible to make with ChaosScript.

**Comment by Konclan** [comment]
I think this is one of those mechanics that would be best implemented through hard code. While I understand that ChaosScript should be possible but I would be happier with a hardcoded version that is provided by the game for everyone to use right away. I think there would be edge cases were the script can't handle interactions super well and those fears while small are the reason why I would be more comfortable with this mechanic being implemented into the engine itself. You could make the argument for "well make it yourself" which I don't think is fair considering sometimes making a custom mechanic in scripting is not only time consuming and sometimes just outright frustrating. There is also the fact that maps that have a version of the script that has flaws will have flaws until both the map and the script is updated.

**Comment by Konclan** [comment]
Oh I didn't even consider how it should handle the paint gun and other custom weapons. Those interactions should be possible but I don't know how the game would handle them.

**Comment by Luke18033** [comment]
As I said in #85:
> It'd be better to expand VScript to make things like this possible/easier, instead of implementing every possible custom test element in code.

ChaosScript is now going to fulfill this purpose of "expanding VScript", and while this mechanic may have been done in a Portal mod before, it is still custom and this does still apply. If it's not possible to implement TWTM's mechanics using ChaosScript in a reliable way, then ChaosScript should be updated to fix that, rather than just hardcoding the mechanic.

As for your concerns about having to manually download it and update it per-map, the workshop should take care of that. You'd just upload "TWTM scripts" or whatever as a workshop item, then maps that wanted to use it would add that as a required item, rather than packing the scripts directly into the map. That would mean if the original was updated, those changes would apply to all maps immediately, with no additional action required from the map creators.

**Comment by SpyceTewan** [comment]
I think this would be a good benchmark for chaosscript
