### ISSUE TITLE
Bug: Control key does NOT work in game (Linux)

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#482]
### Describe the bug

Pressing the control key does nothing.

### To Reproduce
1. Start the game
2. Press the control key (right or left)
3. Observe that it does nothing

### Expected behavior

The control key should work. 

### Operating System (Optional: Only if OS Specific)
 - OS: Linux

**Comment by SpyceTewan** [comment]
Works fine for me on Kubuntu 20.10

**Comment by JJL772** [comment]
Going to close this for now. Seems to be an issue with only my system. The other Linux testers have confirmed that it does not affect them.

I'll probably try to debug this more at some point though.
