### ISSUE TITLE
Fix: Make hammer not delete empty visgroups

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#488]
## Which component should be improved?
Hammer visgroups

## Describe your suggestion
Visgroups are automatically removed if they have no objects in them. There should be a way to protect a visgroup so it doesn't get automatically removed. My idea was fake users like in blender.

## Expected result
Visgroups with a fake user won't be automatically removed when empty

**Comment by SpyceTewan** [comment]
I think this would only be confusing and not add anything. Visgroups dont store extra information like blender materials, they're just a name. If you accidentally delete it, just recreate it

**Comment by SpyceTewan** [comment]
I seem to have understood this incorrectly. Hammer removes empty visgroups when saving/loading a map. I will make it so it doesn't do that

**Comment by Konclan** [comment]
Here is a video showing the issue I'm describing
https://user-images.githubusercontent.com/16567080/106395523-43616f00-63c8-11eb-8aa7-e9e15f74a157.mp4

**Comment by Konclan** [comment]
Here is some other strangeness with visgroups, I'm not able to change parenting in anything other than the window on the right of hammer. Doing so causes strangeness with 'ghost visgroups' in the properties menu.
https://user-images.githubusercontent.com/16567080/106395747-87a13f00-63c9-11eb-8773-e7b945a95f45.mp4

**Comment by SpyceTewan** [comment]
Added a checkbox to enable/disable automatic empty visgroup deletion to Options -> General
