### ISSUE TITLE
Feature: Quick add and remove button for visgroups

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#493]
## Which component should be improved?
Visgroups

## Describe your suggestion
Buttons to quickly add or remove selected objects to a visgroup. This would add for fast visgroup managament without needing to go into the visgroup properties menu every time.

## Expected result
Selected objects should be added to a selected visgroup.

**Comment by SpyceTewan** [comment]
Already exists
