### ISSUE TITLE
P2 Bug: Workshop soundscript <map_name>_level_sounds.txt doesn't load

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#497]
### Describe the bug
Because the workshop changes the bsp name for a map, soundscripts that have the level name in them that the game usually specially loads when loading the map don't get loaded.

### To Reproduce
Pack a <map_name>_level_sounds.txt into a map and upload it to the workshop for instant dissapointment after loading the map

### Expected behavior
The game should load the level soundscript for workshop maps

**Comment by TeamSpen210** [comment]
It's specifically that the soundscript check uses the full map path, so subfolders are included unlike all other checks. That means packing one and then moving the map into a subfolder breaks it.

**Comment by SpyceTewan** [comment]
Our workshop system will be different to portal 2's
