### ISSUE TITLE
Configure energy pellet damage

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#50]
A way to turn Pellets into how Energy Balls act in HL2:EP1, that don’t kill the player but rather will explode on player contact and knock them back.

**Comment by SpyceTewan** [comment]
Related to #52

**Comment by quat1024** [comment]
Would also be great (better?) to have the option to make pellets simply ignore players.

IIRC this was something Mevious was discussing for Rexaura but could not implement without the source.

**Comment by SpyceTewan** [comment]
Added "balldamage" keyvalue https://youtu.be/BYPs4Ifr4do

**Comment by SpyceTewan** [comment]
Added `sv_energy_ball_push_multiplier` for pushback

**Comment by SpyceTewan** [comment]
- Kockback is now a keyvalue
- Added material override
- Added way to disable player collision
