### ISSUE TITLE
Feature: See portalable surfaces in hammer 3D View

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#507]
## Which component should be improved?
Hammer

## Describe your suggestion
The ability to visualize which surfaces are portalable can help massively to debug the map

## Expected result
Variant 1: Create a new viewport similar to 3D smoothing group that colors portalable surfaces differently to non-portalable ones
Variant 2: Add a button for that in the toolbar

**Comment by Konclan** [comment]
To build on this idea, it would probably be nicer to be able to visual any material property like grating, nonpaintable, etc

**Comment by SpyceTewan** [comment]
I added a new 3d viewport that shows portalable surfaces in white and non-portalable ones in dark-gray.

I like the idea of showing grates and other surface types, but I will leave it at portalability for this issue
