### ISSUE TITLE
Bug: Files saving in the wrong directory when started with modwrapper

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#514]
### Describe the bug

Instead of saving in the mod directory, files will save in the p2ce directory regardless of the `-game` parameter. 

### To Reproduce
1. Launch your mod (e.g. -game revolution)
2. Open a map
3. Run buildcubemaps
4. Observe that the BSP is saved in p2ce/maps instead of revolution/maps

### Expected behavior

Should be saving in the mod's directory

**Comment by SpyceTewan** [comment]
This isn't caused by -game, but modwrapper. Modwrapper starts p2ce with -mountmod `your mod path`

**Comment by JJL772** [comment]
Ah my mistake, thanks

**Comment by JJL772** [comment]
Fixed :trollface:
