### ISSUE TITLE
Feature: Flag to enable/disable laser color filtering

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#518]
## Which component should be improved?
Lasers

## Describe your suggestion
Lasers can be colored and redirection cubes, laser relays and laser catchers can add a filter to only work for that one specific color.
Mappers don't want to filter colors all the time, so there should be an option to turn this filter off

## Expected result
Add a keyvalue "enable color filter" to turn color filtering on or off

**Comment by Luke18033** [comment]
Setting it to `255 255 255` turns off the filter, unless that broke. But it'd probably be better to have a separate toggle for it, it's clearer how it works and would allow you to filter pure white lasers (for DDL I made the white laser actually `254 254 254` to allow filtering the catcher).

**Comment by SpyceTewan** [comment]
Done
