### ISSUE TITLE
Implement Pellet launcher and catcher entities 

### ISSUE THREAD

**Issue by Nuclear-Adakam** [ChaosInitiative/Portal-2-Community-Edition#52]
Pellet launcher and catcher entities to speed up workflow in a similar vein to buttons and doors.
The default pellet entity should remain though in case people want custom effects on the launchers and catchers.

**Comment by Luke18033** [comment]
This would maybe be better to implement as a `comp_` entity in the postcompiler?

**Comment by SpyceTewan** [comment]
Yep. That sounds like a postcompiler task. Please open the issue there
