### ISSUE TITLE
Bug: Launching Hammer is broken on latest update as well as clean install

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#520]
### Describe the bug
cmdseqdefault.wc, hammerkeyconfig_default.cfg, and p2ce.fgd has been packed into pak01.vpk\cfg inside the hammer folder instead of being left out in hammer\cfg

Also, default config for Hammer has incorrect file paths, all of them leading into the hammer folder

Finally, postcompiler.exe is missing from bin\win64\postcompiler

### To Reproduce
Either install P2:CE from scratch or install the latest update for P2:CE. Run hammer.exe in bin\win64

Hammer will mention about having no configuration available and will not save the configuration if you happen to set up one yourself

If all the files are back in the correct place, Hammer will complain that the file paths given from the default config are incorrect

### Expected behavior
Hammer should launch normally and you should be able to compile your map with the PostCompiler

### Operating System
Windows

**Comment by JJL772** [comment]
Fixed quite a while ago, forgot to close this guy
