### ISSUE TITLE
All vehicle entities are missing

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#524]
### Describe the bug
As the title says, all vehicle entities are missing from the game. While this isn't really a bug for the HL2 vehicles since they weren't implemented to begin with, the generic entities `prop_vehicle`, `prop_vehicle_drivable`, and `prop_vehicle_choreo_generic` were also removed with the latest version.

The latter entity is used in Finale 4 right before the moon shot, to lock the player's camera angles. Without it, that cutscene is extremely broken, though the game can still be completed.

### To Reproduce
1. Open map `sp_a4_finale4`
2. Open console, look through the errors. `Attempted to create unknown entity type prop_vehicle_choreo_generic` appears.
3. Continue to Wheatley's Lair and noclip through the wall where the stalemate button is
4. The end sequence is triggered but the player remains in full control of movement.

### Expected behavior
`prop_vehicle`, `prop_vehicle_drivable`, and `prop_vehicle_choreo_generic` should be implemented and functional.

**Comment by CitadelCore** [comment]
This is definitely a regression.
