### ISSUE TITLE
Map Transitions will Crash the Game

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#525]
### Describe the bug:
When transitioning from one map to another in any means, the game will instantly crash.

### To Reproduce:
Any map will work, but:
1. Open sp_a1_intro2
2. Play the map and enter the elevator to transition to sp_a1_intro3
3. Observe as the game suddenly crashes.

### Expected behavior:
The map should transition to the next.

**Comment by SpyceTewan** [comment]
I can't reproduce this

**Comment by JJL772** [comment]
Apparently this happens due to the instances folder :trollface: (See #583)

**Comment by JJL772** [comment]
This issue has been superseded by #583 (Not fixed as of 0.5.7)
I want to consolidate issues a bit more. All further discussion should take place on #583
