### ISSUE TITLE
VBSP does not know how to handle instances and collapses them at the world origin

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#526]
### Describe the bug:

Any instance that is placed into a hammer map can be moved around and act normal, but when compiling the map, VBSP will collapse the instance at the world origin.
![315D0C25-BE4C-41FE-8AD0-922525E9E5AB](https://user-images.githubusercontent.com/47882150/109233512-1d3fbb00-781e-11eb-97b6-eb01593ab2a3.jpeg)
Pictured: zoo_mechanics compiled, all the instances have appeared at the world origin rather than their intended locations, taken by Konclan.

### To Reproduce:

1. Make a VMF in hammer, and create a room
2. Place a func_instance with any instance of your choice.
3. Move the instance anywhere away from the origin.
4. Compile the map and observe the results, the instance will have generated at the world origin.

### Expected behavior

The instance should’ve been created at where it was placed in Hammer.

**Comment by Luke18033** [comment]
This is caused by VBSP not loading the FGD correctly. The `GameData` key in `gameinfo.txt` is used for that, you probably need to update it to point to the new location of the FGD. Or put a copy in the old location.

**Comment by DrMeepster** [comment]
Setting `GameData` to "..\hammer\cfg\p2ce.fgd"` worked

**Comment by JJL772** [comment]
Done in 0.5.7
