### ISSUE TITLE
sp_a3_01 Elevator doesn’t dangle, but rather sinks into the floor

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#527]
### Describe the bug
The elevator in sp_a3_01 will sink in a random direction into the floor.
![BBBCEDF4-A41F-4F36-AEA3-2FC6CCB0D249](https://user-images.githubusercontent.com/47882150/109233888-c981a180-781e-11eb-82fe-bcb145699299.jpeg)

### To Reproduce
1. Load up sp_a3_01
2. Watch the elevator that’s meant to dangle from wires above lower itself downwards.

### Expected behavior
The elevator should be dangling from
the wires, not lower itself into the ground.

**Comment by JJL772** [comment]
https://user-images.githubusercontent.com/19717056/109738217-4644b080-7b7c-11eb-9c06-c86a5576b97c.mp4

**Comment by JJL772** [comment]
There's a weird physbox entity that the elevator is supposed to be attached to, but it's not implemented (I don't know all the details). 

View control is also busted here so you're completely frozen, not even noclip can save you from watching the elevator yeet itself into the void.

**Comment by SpyceTewan** [comment]
Found the cause for this, will fix
