### ISSUE TITLE
sp_a3_01 - Player spawns at map origin

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#528]
### Describe the bug
The viewcontrol animation in sp_a3_01 doesn’t end properly and causes the player to be stuck.

### To Reproduce
1. Open sp_a3_01
2. Observe as you cannot move once the animation of getting up is finished.

### Expected behavior
You should be able to move around once the animation of getting up has played.

**Comment by SpyceTewan** [comment]
Seems to be fixed now

**Comment by FrozenDragon0** [comment]
Not fixed. Seems to still be an issue.
