### ISSUE TITLE
Carrying an object with the Gravity Gun through a Portal crashes the game.

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#529]
### Describe the bug
Self explanatory.

### To Reproduce
1. Load into any map and place two portals.
2. Equip a weapon_physcannon.
3. Spawn a Cube
4. Pick up the cube and bring it through the portal
5. Observe the crash

### Expected behavior
The gravity gun should be able to carry the cube through the portal no problem, it works in Portal 1 perfectly fine.

**Comment by JJL772** [comment]
Fixed in 0.5.6 (next update)

**Comment by Luke18033** [comment]
This still happens

**Comment by JJL772** [comment]
Apparently that PR wasn't ever reviewed and merged, until 2 days ago. 

This is one of the issues I was having with certain developers on p2ce- they'd just open their own PR and expect me or someone else to review and merge it. Gocnak reviewed it 2 days ago, but it's literally out of the scope of momentum, so he shouldn't have had to.

**Comment by JJL772** [comment]
So yeah, it'll be in the next update, sorry. I shouldn't have assumed 24 days was long enough to review a stupid 20 line fix.
