### ISSUE TITLE
VPK Workshop Uploads

### ISSUE THREAD

**Issue by ENDERZOMBI102** [ChaosInitiative/Portal-2-Community-Edition#53]
Instead of loading everything within only the .bsp, load assets and stuff from a zip too (7zip best)
doing so can:
- make map/assets size a bit less by zipping it
- load more stuff than the bsp limit permits
the zip could be used to store assets for the map(s), vscript files, libraries for vscript files (look foward what people might do) and other customizations

**Comment by SpyceTewan** [comment]
We thought about this too. Uploading proper "sourcemods" instead of just maps like in HL:A

**Comment by AddMGH** [comment]
I'd love to see this feature, maybe even a section for mod-like uploads, and then just plain uploads.

**Comment by ENDERZOMBI102** [comment]
another thing that could be in the zip/additional data is a "config file" that tells everything about the map, like previus map, next map, series name, icon (why not?), author and other informations

**Comment by ENDERZOMBI102** [comment]
some details about this are in [this](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/57) other issue by Fennecai

**Comment by ENDERZOMBI102** [comment]
More details on folder structure
legend
- type; name; description
folder; series name - random5chars; used for organization
|- folder; maps; folder that contains all the .bsp files
|   |-example; map01.bsp
|- folder; assets; folder that contains shared assets for all maps (this

**Comment by JJL772** [comment]
In reference to changes to [this issue](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/884):

We're no longer going to be using VPKs for workshop uploads. Instead, we'll be uploading directories directly. Details of *why* this is the case are in a comment on #884. I'll be closing this
