### ISSUE TITLE
valve.rc is missing

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#530]
### Describe the bug
The `valve.rc` file is missing from `p2ce/cfg/`. Because CFG files are no longer run from mounted games, this results in the file never being run, breaking autoexecs and a few other things.

### To Reproduce
1. Start P2CE
2. Console reports that it's unable to execute `valve.rc`

### Expected behavior
`valve.rc` should be included in the `p2ce/cfg/` folder.

**Comment by JJL772** [comment]
Added it back in 0.5.6
