### ISSUE TITLE
\r\n.bsp

### ISSUE THREAD

**Issue by DrMeepster** [ChaosInitiative/Portal-2-Community-Edition#534]
### Describe the bug
A clear description of what the bug is. Feel free to add pictures or videos (They really help!)

### To Reproduce
1. Open map ...
2. Do ...
3. See error

### Operating System (Optional: Only if OS Specific)
 - OS: Linux, Windows, MacOS

**Comment by Luke18033** [comment]
What? This is just an unedited issue template.

**Comment by hexaflexahexagon** [comment]
https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/535#issuecomment-796282709
should be closed

**Comment by DrMeepster** [comment]
What the fuck did i make 2 issues

fml
