### ISSUE TITLE
Feature: A Portal_Emitter entity

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#538]
## Which component should be improved?
Entity, Gameplay

## Describe your suggestion
A custom entity that allows you to trigger a portal shot of any ID, prop_portal exists, but it's limited to the wall(s) it's placed on, and although a weapon_portalgun could be used, it's impractical, as as a physics object it's flawed: having trouble being parented, could react badly to fizzlers, has no option to turn invisible (without softhacking it's parameters). makes noise (no silent portal opening) and is bound to portal gun rules (it's portalling speed, it's projectile delay etc). 

## Expected result
A entity that allows you to shoot portals without the need for either prop_portal or weapon_portalgun, allowing for more versatile portal placement without the limitations of the previously mentioned entities.

**Comment by SpyceTewan** [comment]
What is the problem with prop_portal now?

**Comment by Trico-Everfire** [comment]
> What is the problem with prop_portal now?

there isn't really a problem, prop_portal is a placable, you usually set it on a wall, what this new entity would do is like weapon_portalgun without it having so many strings attached, the ability to fire a portal (either with or without sound), the main problems I have with the weapon_portalgun is: it's a physics object, parenting it to grabbable physics objects (like cubes) messes with their ability to be picked up, causing you to drop the object after a second or 2. when parented, it can straight up ignore it's flag of "can't be picked up by player", allowing the player to pick it up anyway. it cannot be (natively) turned invisible, NOR it's shadow turned off. the conlcusion is that the portalgun was never designed to be parented to stuff (other than the portal gun receptacle). I feel like having a (preferably invisible) dedicated entity for parenting and shooting portals to be more suitable.

**Comment by SpyceTewan** [comment]
Why do you even need to shoot portals like that to place a portal?

Also it would make more sense to fix weapon_portalgun instead of adding another entity that does the same thing
