### ISSUE TITLE
multiple map entrances/exits

### ISSUE THREAD

**Issue by ENDERZOMBI102** [ChaosInitiative/Portal-2-Community-Edition#54]
Basically, what hl1/2 implements for map translition

**Comment by SpyceTewan** [comment]
you can.. already do that?

**Comment by Luke18033** [comment]
In my testing, transitioning back into the previous map would cause everything to reset its state. Other than that the original system is still fully implemented, I'm not sure why people think it isn't.

**Comment by SpyceTewan** [comment]
#56
