### ISSUE TITLE
P2CE taskbar icon is wrong again

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#541]
### Describe the bug
P2CE has reverted to using the Chaos Initiative logo as its taskbar icon (though it is now the new one). For the previous few versions before the latest, the P2CE logo was used as expected.

### To Reproduce
Just open P2CE in windowed or borderless mode and look at the taskbar icon.

### Expected behavior
P2CE should use the P2CE icon on the taskbar.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows, probably others?

**Comment by braem** [comment]
This had to do with the filesystem changes we were doing and should be fixed in p2ce's next push.

**Comment by JJL772** [comment]
as @braem said, this will be fixed in the next p2ce update
