### ISSUE TITLE
Bug: Portal 1 crosshair overrides partner's portals when looking at them

### ISSUE THREAD

**Issue by SpyceTewan** [ChaosInitiative/Portal-2-Community-Edition#544]
### Describe the bug
I caused this bug, I know where it is, I will fix it.

It's an issue with the portal testing code. The portal 1 crosshair tests if a portal can be placed and that "fake portal" seems to replace the coop partner's portals when looking at it.

### To Reproduce
1. Open a coop map
2. Use portal 1 style crosshair
3. One player shoots a portal
4. Other player looks at that portal
5. The portal closes

### Expected behavior
The portal shouldn't close

**Comment by DanielBatesJ** [comment]
Adding to this issues, from our testing in Online Coop, the portal fizzling is *not* dependent on the Portal 1 Style Crosshair.

**Comment by SpyceTewan** [comment]
Yeah it comes from the portal placement test functions i added _for_ the portal 1 crosshair, which is run every frame even when not using the p1 crosshair

**Comment by SpyceTewan** [comment]
Fixed
