### ISSUE TITLE
Add Start Open keyvalue to prop_testchamber_door

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#545]
## Which component should be improved?
Entity

## Describe your suggestion
`prop_testchamber_doors` currently have no option to start open. This isn't something that's needed often, but there are certain situations when it would be nice.

## Expected result
`prop_testchamber_door` should have a Start Open keyvalue which makes the door start open.

**Comment by SpyceTewan** [comment]
Done. Added `open` and `locked` keyvalues
