### ISSUE TITLE
Bug: Portals can only be placed on surfaces parallel to the opposite portal in some maps

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#546]
### Describe the bug

I don't actually know the cause of this, but it seems like portals can only be placed on surfaces parallel to the opposite portal. (This was described to me by @mlugg, he did more digging into the issue).

Here's an example video of the problem:
https://youtu.be/zZ_FFtf6AV8

### To Reproduce
1. Open a map (Which maps have this problem??)
2. Try to shoot portals on surfaces that are not parallel to each other

### Expected behavior

Portals should be placeable on any portal-able surface.

**Comment by EchoesForeAndAft** [comment]
Fixed.
