### ISSUE TITLE
Bug: Respawn Entities Deletes Challenge Mode Flags

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#547]
### Describe the bug
Flags are not in the map after after `repsawn_entities` is used

### To Reproduce
1. Use the `repsawn_entities` command while in Challenge Mode.
2. Get to the end there are no flags

### Expected behavior
Flags should stay in the same position

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by SpyceTewan** [comment]
Is this a portal 2 or p2ce bug?

**Comment by betsruner** [comment]
> 
> 
> Is this a portal 2 or p2ce bug?

It's in both right now

**Comment by SpyceTewan** [comment]
Fixed
