### ISSUE TITLE
Bug: Laser Cube particles Broken

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#549]
### Describe the bug
Laser cube particles breaks when stacking more than one

### To Reproduce
1. Place a laser cube to intersect with one laser 
2. Take a second laser cube and use it to block the laser that the original cube is being affected by 
3. [Image Reference](https://imgur.com/a/P7D1eWJ)

### Expected behavior
The particle should remain consistent with the cube receiving the laser

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by mlugg** [comment]
Fixed
