### ISSUE TITLE
Bug: Crouching Animation Speed is Inconsistent with Original Portal 2

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#550]
### Describe the bug
Crouching animation seems to more closely emulate the speed of crouching in CSGO vs Portal 2, which impacts certain specific aspects of Portal 2 gameplay.

### To Reproduce
1. Crouch on any map

### What this impacts
This impacts one major Portal 2 Speedrun Tick specifically, commonly called "Dane Skip" Where you clip through the bottom of the Elevator on Column Blocker. [Here](https://youtu.be/6zeK_7ELuVo?t=1187) is Dane Skip being done in a normal run, [here ](https://www.twitch.tv/videos/955638019?t=00h42m31s)is the same runner attempting to do the trick on P2CE. It's assumed these two issues are related.

### Expected behavior
A slower more similar to regular Portal 2 Crouching animation speed

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows.

**Comment by SpyceTewan** [comment]
Mlugg or blender fixed that
