### ISSUE TITLE
Bug: `portalgun_fire_delay` is not Cheat Protected

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#551]
### Describe the bug
The console command `portalgun_fire_delay` is not Cheat Protected

### To Reproduce
1. Open developer console
2. Type `portalgun_fire_delay <value>` and it will let you change the cvar's value.

### Expected behavior
The command should be cheat protected, and `sv_cheats` must be set to `1` to alter this value.

### Operating System (Optional: Only if OS Specific)
 - OS: All

**Comment by SpyceTewan** [comment]
It is already set as a cheat
