### ISSUE TITLE
Bug: `demoui` emulates CS:GO's demo viewer

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#554]
### Describe the bug
P2CE uses the CS:GO `demoui` which shows CS:GO specific information such as "rounds" and "deaths"

### To Reproduce
1. Press `Shift + F2` while watching a demo playback, or type `demoui` in developer console.

### Expected behavior
`demoui` should resemble Portal 2's `demoui`.
- `demoui` in [Portal 2](https://i.imgur.com/bnWPLDw.png)
- `demoui` in [P2CE](https://i.imgur.com/1U1Fnoq.png)

### Operating System (Optional: Only if OS Specific)
 - OS: Only tested on Windows

**Comment by JJL772** [comment]
Fixed in 0.5.6 (next update)
