### ISSUE TITLE
Bug: Demoui sounds missing

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#555]
### Describe the bug
Moving backwards in a demo using the `<` to rewind by a tick in `demoui` will trigger a Half-Life 2 voice line “Oh Fiddlesticks, what now”.

### To Reproduce
1. Start playback of a demo
2. Press `Shift + F2` or type `demoui` in console
3. Press the `<` arrow next the to the "Pause/Resume" button, and resume demo playback.

### Expected behavior
A voice line is not meant to be played.

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows

**Comment by SpyceTewan** [comment]
That line plays when a sound file isn't found. Can you say which one it's looking for?

**Comment by DanielBatesJ** [comment]
It seems to happen anywhere on the map, regardless of map or location. Mlugg believes it could be a CS:GO Reload sound

**Comment by Blenderiste09** [comment]
Fixed issue
