### ISSUE TITLE
Bug: Turret Damage Noises are not the same as in Original Portal 2

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#556]
### Describe the bug
Getting shot with a turret does not make the same noise as in original Portal 2. Seems to emulate Half-Life sounds instead?

### To Reproduce
1. Get shot by a turret or [check reference video from P2CE](https://youtu.be/XxOklAIEf3s)

### Expected behavior
[The original damage sound from Portal 2 ](https://www.youtube.com/watch?v=l2cdUAiAjoE)

**Comment by RandomCatDude** [comment]
The proper bullet shot does appear to play now. but the old bullet ricochet noise still plays, too.

**Comment by RandomCatDude** [comment]
will test mounting HL2 now, per craftablescience's request on Discord. see how that affects this

**Comment by RandomCatDude** [comment]
yup, that's the problem. mounting HL2 overrides the stabby P2 bullet shot sound

**Comment by RandomCatDude** [comment]
hmm, no. that doesn't appear to affect this

**Comment by Luke18033** [comment]
Still an issue
