### ISSUE TITLE
Feature: Rocket Turret “ForceFire” Input

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#560]
## Which component should be improved?
npc_rocket_turret Entity

## Describe your suggestion
In prop_rocket_tripwire, there exists a “ForceFire” input that can be done to the Tripwire Turret that causes it to fire it’s rocket on input, considering how similar Rocket Turrets and Tripwire Turrets are (e.g. the Tripwire Mode in npc_rocket_turret that’s currently broken), it feels reasonable to have this for normal Rocket Turrets.

## Expected result
When a ForceFire input is fired, the targetted Rocket Turret should instantly fire it’s rocket, no matter the direction it’s facing.

**Comment by TeamSpen210** [comment]
Since regular rocket turrets aim, the input wouldn't be that useful if it just shot in whatever direction it happened to be pointing. I reckon just using an `ai_relationship` + `npc_bullseye` would be better, combined with an `OnFired` output that'd let you do a single shot nicely.

**Comment by OssyFlawol** [comment]
I think there is something like this for Tripwire Turrets that exists where you can set a target for it to aim at, I haven’t gotten a chance to test it though. Either way, the `ForceFire` input would be use to port over anyways for Tripwire Mode.

**Comment by Trico-Everfire** [comment]
Works As Intended
