### ISSUE TITLE
Bug: Chamber Select VGUI Screens are Drawn Through Walls

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#563]
### Describe the bug
Chamber select VGUI screens are drawn through walls

### To Reproduce
1. Load into Cooperative Lobby
2. Look at chamber select VGUI while it is closed

### Expected behavior
The VGUI should not be seen

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows

![](https://i.imgur.com/R7bw2h4.png)

**Comment by EchoesForeAndAft** [comment]
Online session? Split-screen/local? `mp_coop_lobby_2` or `mp_coop_lobby_3`?

**Comment by EchoesForeAndAft** [comment]
Unable to reproduce in split-screen.

**Comment by Luke18033** [comment]
Seems to be fixed, I haven't been able to test it in actual multiplayer but I don't know why it would render differently there.
![image](https://user-images.githubusercontent.com/19228201/143729725-343a308e-1d2c-4096-82d8-10b7c4529c1f.png)

**Comment by Luke18033** [comment]
Yep, this appears to now be fixed:
![image](https://user-images.githubusercontent.com/19228201/144765407-eb880b75-3adf-4124-8374-b1f4a7e96ce9.png)
