### ISSUE TITLE
Bug: Inconsistent Viewmodel Lighting

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#566]
### Describe the bug
In certain lighting conditions, the viewmodel does not respond as expected to light sources.
![image](https://user-images.githubusercontent.com/36864021/114473343-a8e88d80-9bb9-11eb-953a-8a7436ee0dee.png)

### To Reproduce
Steps to reproduce the behavior: Easiest example is in Turret Factory, using Wheatley's flashlight.
1. Load into Turret Factory `sp_a2_bts3`
2. Trigger the cutscene where lights are turned off.
3. Position your character under Wheatley's flashlight.

### Graphics Settings
![image](https://user-images.githubusercontent.com/36864021/114473515-0086f900-9bba-11eb-8f0e-2beca104b3dd.png)

### Expected behavior
These specific lights should work as intended.

### Operating System (Optional: Only if OS Specific)
 - OS: Tested only on Windows

**Comment by Luke18033** [comment]
The viewmodel isn't affected by projected textures. Portal 2 just fixed this in one of the recent updates, I'd imagine P2CE just needs to port over that code.

**Comment by SpyceTewan** [comment]
Have fixed that already
