### ISSUE TITLE
Bug: Stalemate Room in `sp_a4_finale4` Does Not Work as Intended

### ISSUE THREAD

**Issue by DanielBatesJ** [ChaosInitiative/Portal-2-Community-Edition#570]
### To Reproduce
1. Enter `sp_a4_finale_4`.
2. Finish the boss fight.
3. Place a portal above the stalemate room.
4. Enter the floor portal while holding forward through the portal, in the direction away from the button.

### Expected behavior:
You should be blown out of the room shortly after entering.

### Demo:
[Demo file](https://drive.google.com/file/d/1VSZgJtLGkoePyF8Wmw-ZygBkDWI0xW8b/view) showing the issue.

Operating System (Optional: Only if OS Specific):
- Windows

**Comment by Luke18033** [comment]
This would be a duplicate of #524, the camera animation doesn't work at all.

**Comment by JJL772** [comment]
It is indeed a duplicate of #524 
This was a release packaging error on our part (USE_VEHICLES was not defined when the release was built).
