### ISSUE TITLE
Bug: A npc_zombie hit with a flung Weighted Cube will split the zombie in half, kill it, and set it on fire

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#572]
### Describe the bug
Honestly it's pretty self explanatory from the title alone, Here's a video of this bug in action:
https://cdn.discordapp.com/attachments/727657351800160287/831717369742098442/how.mp4

### To Reproduce
1. Open any map
2. Spawn a npc_zombie and a Cube
3. Let the zombie begin to throw the cube at you.
4. Spawn another zombie infront of the cube, and observe as it suddenly is set on fire, splits in half and dies.

### Expected behavior
The zombie should just die normally as if its hit by a large physics object ala Half Life 2.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows

### Additional Content (Uploaded from the above discord link for visibility)

https://user-images.githubusercontent.com/19717056/114646180-a193b380-9c8f-11eb-9356-87cc5fbc485a.mp4

**Comment by SpyceTewan** [comment]
Ok this is fucking funny

**Comment by craftablescience** [comment]
Closing in favor of #712
