### ISSUE TITLE
Allow local changes in gravity 

### ISSUE THREAD

**Issue by mariovct** [ChaosInitiative/Portal-2-Community-Edition#58]

**Comment by mariovct** [comment]
Ignore this it was by accident

**Comment by Luke18033** [comment]
Why? This would be a useful feature.

**Comment by mariovct** [comment]
You could already do this with a Trigger_push right?

**Comment by Luke18033** [comment]
I was thinking you meant a way to fully shift the player's gravity direction, including rotating them (so "down" visibly changes). This would already be needed for Adhesion Gel, so I can't imagine it would be too hard to make a trigger for it as well.

**Comment by mariovct** [comment]
That’s not really what I had in mind; but i will make a separate issue for that.

**Comment by SpyceTewan** [comment]
Please don't rename issues to "delete this"
