### ISSUE TITLE
Feature: Set default skybox to sky_black

### ISSUE THREAD

**Issue by DrMeepster** [ChaosInitiative/Portal-2-Community-Edition#582]
## Which component should be improved?
FGD

## Describe your suggestion
The default skybox in hammer should be `sky_black` instead of `sky_day01_01`. That skybox is not present unless HL2 is mounted, while `sky_black` is present in Portal 2.

## Expected result
The default skybox when creating a new map is `sky_black`.

**Comment by Luke18033** [comment]
It's `sky_black_nofog` in P2's default FGD as well as TeamSpen's addons, it's possible P2CE's FGDs were built with the wrong tags and so that resulted in HL2's default setting being used instead? Not sure. But FGD issues should go on https://github.com/ChaosInitiative/Chaos-FGD.

**Comment by DrMeepster** [comment]
ah, okay ill put it there

**Comment by DrMeepster** [comment]
Oh, it looks like its already fixed in the repo, I guess it'll be there in the next version
