### ISSUE TITLE
Bug: P2CE instances break level transitions

### ISSUE THREAD

**Issue by AWildErin** [ChaosInitiative/Portal-2-Community-Edition#583]
### Describe the bug
Currently, I have the P2CE instances from the repo in my `Portal 2 Community Edition\sdk_content\maps\instances` folder which causes the game to crash when it loads to the next level. Renaming the folder to anything else does not crash the game, which leads me to believe it's the instances causing the issue. (note, this crash happens even if you rename your folder to `instances*`, * being any additional text)

My theory is probably it's to do with the differences of the instances but I don't really know, I've not touched either Portal 2 or P2CE's instances.

### To Reproduce
1. clone or download P2CE instances into into `Portal 2 Community Edition\sdk_content\maps\instances`
2. load P2CE and load a Portal 2 level like normal
3. Complete the level
4. Your game crashes after loading into the next level

### Expected behavior
To not have a crash

### Operating System (Optional: Only if OS Specific)
 - OS: Linux, Windows, MacOS

**Comment by Luke18033** [comment]
That's weird, instances are collapsed into compiled maps, they aren't referenced or used by the game in any way. Maybe it's some stray Puzzlemaker code or something?

**Comment by AWildErin** [comment]
Yeah, that's what's confusing by it. All I know is that, for some reason, it crashes when it's in that folder, I don't know what fully crashes it either as the console logs are not exactly informative. It is always just after you load the next level aswell

**Comment by AWildErin** [comment]
Narrowed it down a bit more deleting `Portal 2 Community Edition\sdk_content\maps\instances\transition\transition_global_ents.vmf` seems to fix this issue, I don't know *why* this causes a problem as, as you said, they get collapsed and compiled. It's most likely down to Source's weirdness as per usual.

**Comment by AWildErin** [comment]
So I just did a bit more testing, this seems to happen only if you launch P2CE, play a Portal 2 campaign map and have `-dev` enabled, so far this is making very little sense and making me doubt instances are the issue but each time I try it, it convinces me more and more that they are the issue. I'm not sure if it's some sort of Source spaghetti or what, but without `-dev` you won't experience this at all

**Comment by JJL772** [comment]
This is related to #525 

A temporary workaround is to set `r_sequence_old_order` to 0, but this will cause snappy animations.

**Comment by CitadelCore** [comment]
Should be fixed now
