### ISSUE TITLE
Bug: Hammer crashes upon load

### ISSUE THREAD

**Issue by IdontKnowNothin** [ChaosInitiative/Portal-2-Community-Edition#585]
### Describe the bug
Upon starting up Hammer I see it pop up, everything seems normal, and after a second or so it crashes.

https://user-images.githubusercontent.com/73007406/117009198-28b6d300-acf4-11eb-91b0-7f5fdb9d5632.mp4

Despite my efforts the error continues to happen, no dumps come out of it either.

### To Reproduce
No idea what actually causes it, so for now I'd consider it not reproduceable.

### Expected behavior
Expected Hammer to load up as normal.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows 10

**Comment by braem** [comment]
You might need to delete your gameconfig in `hammer/cfg` and have hammer autogenerate it from the default again.

**Comment by SCell555** [comment]
Is discord running while the crash happens? Currently there is a bug with hammer discord integration causing it to crash if discord is unavailable.

**Comment by TERRORcows** [comment]
This happens to me as well, deleting the gameconfig doesn't effect it, and neither does discord

**Comment by FrozenDragon0** [comment]
Can confirm this also happens to me.

**Comment by Luke18033** [comment]
If you have the Discord app running or you disabled Discord integration in the settings, then it works correctly.

**Comment by JJL772** [comment]
Done in 0.5.7
