### ISSUE TITLE
Bug: MainMenuController Panorama script

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#586]
## Which component should be improved?
`MainMenuController` in Panorama.

## Describe your suggestion
~~In this script, `this` is used in a static context, instead of `MainMenuController`. I replaced all the `this`es with `MainMenuController` and it had less error messages. Everything still works as it did before.~~ Nevermind, my changes weren't being loaded. The issue where the script errors out still stands.

Additionally, clicking Quit repeatedly produces infinite dialogs.

---
![image](https://user-images.githubusercontent.com/26600014/117015630-ea072580-acbf-11eb-9ff5-7a80df6fffdf.png)

## Expected result
There should be no errors popping up in the main menu, and pressing Quit should only produce one dialog.

**Comment by JJL772** [comment]
> In this script, this is used in a static context, instead of MainMenuController. I replaced all the thises with MainMenuController and it had less error messages. Everything still works as it did before.

You can use `this` in a static context in JS, it's functionally identical to using the class name in place of `this`

The main menu is still very much WIP, so I'm going to close this issue.
