### ISSUE TITLE
Bug: Command Portals_ResizeAll crashes game on values less than 1

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#587]
### Describe the bug
Running the command `Portals_ResizeAll [number1] [number2]` where either number1 or number2 is a number lower than 1 crashes the game.

### To Reproduce
1. Load any map
2. Run `Portals_ResizeAll 0.5 0.5` in the console
3. Observe a dialog box popping up, containing VPhysics' complaints

### Expected behavior
The number inputs should be clamped at or above 1.

### Operating System
Confirmed on Windows 10.

**Comment by JJL772** [comment]
We also have a crash when the portals are resized to be larger than like 1000 x 1000. vphysics related, so probably not fixable. will probably end up clamping the values to sane amounts to prevent dumb crashes
