### ISSUE TITLE
Bug: Panorama main menu broken without background map set

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#588]
### Describe the bug
If you run `map_background <any map name>` and restart the game, the panorama main menu renders. This currently only affects DX9.

### To Reproduce
1. Load P2CE in panorama mode from the Steam branch, observe the menu renders for a split second then disappears
2. Run `map_background sp_a2_triplelaser`
3. Restart P2CE, observe menu consistently renders

### Expected behavior
You do not need to call `map_background` to get the menu to render.
(That, or bring back map backgrounds for Chaos Source.)

### Operating System
Reported on Windows 10.

#### The menu loads.
![image](https://user-images.githubusercontent.com/26600014/117065629-bc3cd380-acf5-11eb-8eb9-903e2761b41d.png)

#### The loading screen also loads before the map to load is initialized (ignore the smiley face I added)
![image](https://user-images.githubusercontent.com/26600014/117065709-d1196700-acf5-11eb-8592-0a28a763c853.png)

**Comment by JJL772** [comment]
Done in 0.5.7
