### ISSUE TITLE
Bug: Panorama pause menu does not render without the portal gun

### ISSUE THREAD

**Issue by AWildErin** [ChaosInitiative/Portal-2-Community-Edition#589]
### Describe the bug
With panorama, if you press escape to load the pause menu it does not render unless you have the portal gun.

Without the portal gun, note that that `SC Mode GameControls -> MenuControls` is in the top left corner indicating I have the pause menu open:
![image](https://user-images.githubusercontent.com/28122025/117068779-a0502680-ad23-11eb-88af-da03f7b721b6.png)

With the portal gun, again note that line in the console:
![image](https://user-images.githubusercontent.com/28122025/117069056-f1601a80-ad23-11eb-9a71-374075780173.png)

### To Reproduce
1. Open a map that starts without the portal gun
2. Open the pause menu and observe there is no pause menu
3. Open the console, type `give_portalgun` and close the pause menu
4. Re-open the pause menu and observe the pause menu magically appear

### Expected behaviour
The pause menu should exist

### Operating System (Optional: Only if OS Specific)
 - OS: Linux, Windows, MacOS

**Comment by JJL772** [comment]
Fixed in 0.5.7
