### ISSUE TITLE
Add weapon_flashlight

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#59]
The flashlight in Portal 2 is accessible only through console commands and `sv_cheats`, and would be a nice feature to have.

**Comment by Luke18033** [comment]
In HL2, all the flashlight actually is is just a key bound to `impulse 100` (so the same as P2). It doesn't require sv_cheats though, no idea why they changed that.

**Comment by AddMGH** [comment]
It also plays a sound, so even so, it's different to P2's implementation

**Comment by BlightedLight** [comment]
This is a highly-redundant thing to be implemented and would be better off being implemented via VScript. Should we close this issue @SpyceTewan?

**Comment by Luke18033** [comment]
I'd say just make the flashlight command not require sv_cheats, then people can use it in maps or bind it to a key if they want.

**Comment by SpyceTewan** [comment]
Having the flashlight always in any map would just break the game as neither Portal 1 nor 2 have it

**Comment by AddMGH** [comment]
> This is a highly-redundant thing to be implemented and would be better off being implemented via VScript. Should we close this issue @SpyceTewan?
I don't think vscript is the holy grail of mapping but go off.




> Having the flashlight always in any map would just break the game as neither Portal 1 nor 2 have it
It shouldn't exactly be hard to introduce the flashlight as an obtainable weapon, kinda like HL:A. Though honestly, just having the ability for a map to use flashlight like HL2 would be nice, no matter what restrictions it'd have

**Comment by SpyceTewan** [comment]
A flashlight weapon sounds like a cool idea that could be used in exploring and infra-style maps

**Comment by SpyceTewan** [comment]
Can do that in chaosscript yourself
