### ISSUE TITLE
Bug: All loading screens resized as if 4:3 on 16:9 resolution

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#591]
### Describe the bug
Note: this usually happens with `-legacyui` enabled, but it happens in Panorama as well.
This one is best described in picture form:

![image](https://user-images.githubusercontent.com/26600014/117070343-99adb900-acfb-11eb-9b15-e8d49c7fe8e7.png)
![image](https://user-images.githubusercontent.com/26600014/117070355-a03c3080-acfb-11eb-9f60-78c67c987c4f.png)

I believe it's using the 4:3 background and then stretching it to match the 16:9 resolution.

### To Reproduce
1. Load the game with a 16:9 resolution
2. Look at the loading image
3. This happens entering a co-op game as well

### Expected behavior
The image shouldn't be stretched.

### Operating System
Reported on Windows 10.

**Comment by JJL772** [comment]
Looks good on Linux. @EchoesForeAndAft can you repro on windows?

**Comment by EchoesForeAndAft** [comment]
DX11-specific bug. Is fixed now.
