### ISSUE TITLE
Bug: Turrets still not colliding with clips.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#594]
### Describe the bug
In sp_a2_turret_intro turrets still do not collide with clips.

### To Reproduce
1. Open map sp_a2_turret_intro
2. When the door opens pick up the first turret.
3. If you try to put the turret on the broken floor at the start of the chamber it doesn't collide with the clips.

### Expected behavior
Turrets should be colliding with clips as this was mentioned in a recent update?

### Operating System (Optional: Only if OS Specific)
 - OS: Only tested on Windows

**Comment by PortalRex** [comment]
#548

**Comment by JJL772** [comment]
FIxed
