### ISSUE TITLE
Don't reset portal color cvars when changing maps

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#595]
## Which component should be improved?
Entity?

## Describe your suggestion
The portal color cvars currently reset when loading into a new map. This was implemented to allow maps to set custom portal colors and not have them carry over into later maps, which is a good idea, but it's not the reason people wanted custom portal colors: they wanted to be able to customize their own portal colors for personal use, not change them in a specific map for everyone who plays it.

Considering that P2CE plans to implement a per-map cvar system, it seems rather pointless to add in a specific portal color system for that beforehand, especially if said system almost entirely breaks the actual thing people wanted to use the cvars for.

If people *really* want per-map portal color changing this early on, then it should be implemented in a way that doesn't interfere with personal portal colors. ~~For example maybe add corresponding inputs to `logic_playerproxy`, which would override the color specified in the commands and only persist for the duration of the map.~~ See better suggestion below.

## Expected result
The portal color commands should not reset when changing maps

**Comment by JJL772** [comment]
I think we can add inputs to `logic_playerproxy` for this. 

The cvars should just be archived and not reset.

**Comment by Luke18033** [comment]
The cvars are also currently set as singleplayer-only, which means they can't be changed in multiplayer (and is the cause of #593). This should be removed, in multiplayer they'd just have no effect.

**Comment by Luke18033** [comment]
Another idea I saw for per-map portal colors is having it as a keyvalue on `prop_portal`. If unset it'd default to the color specified in the corresponding cvar, but would override that if set. So then maps that wanted to have specific portal colors would include two preplaced `prop_portals` set to the desired colors.

Perhaps add a `SetColor` input as well to change them mid-map.

**Comment by ashifolfi** [comment]
Swapping between maps with custom portal colors seems to work.

My primary portal does indeed stay set to `255 0 0` after loading into a different map

**Comment by verygladen** [comment]
Tested on latest Nightly, custom colors are the same.
