### ISSUE TITLE
Change cap of env_projectedtexures to a limit of 4

### ISSUE THREAD

**Issue by distributivgesetz** [ChaosInitiative/Portal-2-Community-Edition#60]
Pretty self-explanatory, it would be pretty nice to have multiple entities like this at once enabled instead of switching between them. Instead, one could implement a warning from the engine that you are running too many projected textures and that performance will be at cost.

**Comment by Luke18033** [comment]
There's already a plugin that does this, can't be too hard.

**Comment by SpyceTewan** [comment]
I can't believe we don't already have an issue for this.

**Comment by SpyceTewan** [comment]
We will increase the limit, but to a reasonable amount
