### ISSUE TITLE
Bug: Coop P-body's portals crash the game.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#601]
### Describe the bug
When your playing with a guest in coop mode their game will crash if they attempt to go through their pair of portals.

### To Reproduce
1. Open the coop calibration course intro level, mp_coop_start
2. Obtain the portal gun from GLaDOS.
3. Head into the next room as P-Body and place a pair of portals and attempt to go through them, you'll notice the game crashes for some unexplained reason. This does not happen to the host player.

### Expected behavior
You should beable to freely attempt to walk through the portals without the game crashing.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows

This issue does not occur on Splitscreen, only online coop.

**Comment by craftablescience** [comment]
Just gonna note that I played online co-op yesterday as P-Body and this didn't happen to me, so could be related to some other issue.

**Comment by PortalRex** [comment]
This also didn't happen to me while playtesting coop.

**Comment by FrozenDragon0** [comment]
@PortalRex Were you doing online?

**Comment by PortalRex** [comment]
Yes unless specified in the issue I always test in normal coop never split screen.

**Comment by FrozenDragon0** [comment]
Strange.

**Comment by EchoesForeAndAft** [comment]
Cannot reproduce in split-screen.

**Comment by JJL772** [comment]
Fixed in next update
