### ISSUE TITLE
Bug: Light bridge inconsistently renders one face

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#606]
### Describe the bug
If the player has no weapon, then one face on a light bridge will not render. If a Panorama screen is open, the same issue will occur.

![image](https://user-images.githubusercontent.com/26600014/117328221-6b49ee00-ae61-11eb-9c2c-3a58962f24bd.png)

### To Reproduce
1. Build + run [https://cdn.discordapp.com/attachments/771063726555660312/839891341097828422/zoo_mechanics.vmf](zoo_mechanics.vmf). It relies on Portal 2 instances, so you can copy those from Portal 2 as needed.
2. Observe the light bridge to the right is broke on the side facing the player.
3. Run `give_paintgun` in the console.
4. The light bridge is fixed.
5. Pause the game, and observe that when the Panorama pause menu is active the light bridge is borked again.

### Expected behavior
The light bridge renders properly at all times.

### Operating System
Reported on Windows 10.

**Comment by JJL772** [comment]
This might be related to the culling bug in shaderapi that only showed itself when pandx was removed. We've fixed that culling bug (which also broke the main menu, hence the boot to black screen), but we'll need to see if that fixes it.

**Comment by JJL772** [comment]
Done in 0.5.7!
