### ISSUE TITLE
Bug: Paint/Gel bugged in P2:CE compiled maps.

### ISSUE THREAD

**Issue by DeliWasTaken** [ChaosInitiative/Portal-2-Community-Edition#609]
### Describe the bug
In any map compiled in P2:CE, gel will be extremely choppy and overall unusable.

### To Reproduce
1. Open P2:CE hammer
2. Create map, Enable gel, add paint sprayer, (or use paint gun) compile map
3. Run map, gel is bugged.

### Expected behavior
Gel works normally.

### Operating System (Optional: Only if OS Specific)
 - Non OS specific

**Comment by FrozenDragon0** [comment]
This doesn't seem to be a issue for me, gel functions fine.

**Comment by DeliWasTaken** [comment]
Multiple beta testers including myself have experienced this bug, will upload a video shortly.

**Comment by DeliWasTaken** [comment]
https://user-images.githubusercontent.com/71228050/117465833-b32b4c80-af17-11eb-87c7-e974f9307477.mp4

**Comment by FrozenDragon0** [comment]
That is very strange. Does the same thing happen if paintallsurfaces is used?

**Comment by DeliWasTaken** [comment]
It does. The surfaces get painted, but you can still see that it's still incredibly choppy.
![image](https://user-images.githubusercontent.com/71228050/117553654-68ddc480-b018-11eb-8f18-6da2c76bf150.png)

**Comment by DeliWasTaken** [comment]
FIX: Lightmap scale now defaults to 128. Setting it to a lower value (such as the original default, 16) will fix issue.
