### ISSUE TITLE
Add saving of Gel on light bridges

### ISSUE THREAD

**Issue by ACBob** [ChaosInitiative/Portal-2-Community-Edition#61]
In portal 2, if gel is applied to a light bridge, it isn't saved along with the game.
This isn't an issue for the only Use-case in the base game, COOP, but it is an issue in single-player.

**Comment by BlightedLight** [comment]
Are you talking about when loading a save file? If so that's to do with the Save/Restore system and this should hopefully be an easy fix.

**Comment by ACBob** [comment]
Yeah, pretty much.

**Comment by CitadelCore** [comment]
Fixed.
