### ISSUE TITLE
Bug: First Turret in Turret intro starts knocked over

### ISSUE THREAD

**Issue by Amtyi** [ChaosInitiative/Portal-2-Community-Edition#611]
### Describe the bug
In `sp_a2_turret_intro`, the first turret starts knocked over instead of standing up
https://user-images.githubusercontent.com/77759899/117451615-118f1400-af86-11eb-8a54-40e09f107979.mp4

### To Reproduce
1. do `load sp_a2_turret_intro` in console
2. Walk through doors into the test chamber

### Expected behavior
The turret is meant to be standing up in the middle, as per what happens in regular Portal 2

### Operating System (Optional: Only if OS Specific)
 - OS: Windows

**Comment by PortalRex** [comment]
#548 #594

**Comment by JJL772** [comment]
Fixed in 0.6.11
