### ISSUE TITLE
Bug: Load Tool Module window is broken

### ISSUE THREAD

**Issue by kittymatthew** [ChaosInitiative/Portal-2-Community-Edition#613]
### Describe the bug
The load tool module window in -tools mode is non-functional, brings up a window labelled 'Untitled' with the only option being able to close it. 

![image](https://user-images.githubusercontent.com/21313894/117457993-cccc9400-af17-11eb-8be9-2b6674ba95e6.png)

### To Reproduce
1. Launch P2CE with -tools
2. Select Tools -> Load tool module...

### Expected behavior
Either there should probably be a window to open a tool that defaults in the tools/ directory, or it can be removed altogether.

**Comment by AWildErin** [comment]
Duplicate of https://github.com/ChaosInitiative/Chaos-Source/issues/377
