### ISSUE TITLE
Map-triggered gestures disconnect players in coop

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#623]
### Describe the bug
When completing the calibration course a automatic High Five is usually performed when both players are at the end of the level at the exit door. This is not the case in P2:CE however and when this occurs the session will immediately cut out.

### To Reproduce
1. Start the calibration course in online coop.
2. Play through it normally until you get to the end in which the automatic High Five is initiated.
3. When the HighFive is initiated you will immediately get disconnected.

### Expected behavior
The Gesture should proceed as normal and not disconnect you from the session.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows

EDIT: This seems to happen in any level in which a gesture is initiated by the map itself. A example of this is present on Course 3's ending level mp_coop_wall_5

**Comment by EchoesForeAndAft** [comment]
Unable to reproduce in split-screen.

**Comment by FrozenDragon0** [comment]
@EchoesForeAndAft It only happens during online sessions.

**Comment by Luke18033** [comment]
When we were playing MP, team gestures would sometimes cause one or both players to get disconnected with an error like "too many commands" or something, map-triggered non-team gestures like the wave in the calibration course seemed to work fine though

**Comment by Luke18033** [comment]
Right I forgot the gesture at the end of the calibration course is the high five, either way I don't remember it disconnecting though, I'll need to check

**Comment by FrozenDragon0** [comment]
After testing this issue on all maps that initiate a auto-gesture with @Luke18033 it would appear that this has fixed itself, can't be 100% certain if it still exists though.

**Comment by Luke18033** [comment]
Seems fixed
