### ISSUE TITLE
Setting prop_button timer delay to -1 should make it infinite

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#624]
## Which component should be improved?
Entity

## Describe your suggestion
`prop_button`s have no way to be made infinite, instead you just have to set the delay to an extremely high value. While this isn't really a problem, it would be nice to have a way to make the button truly infinite, especially considering that this functionality is already present on other button entities.

## Expected result
Setting the timer delay on a `prop_button` to -1 should make it infinite. The timer sound and fast reset keyvalues would still work as normal, though you'd usually keep both off.

**Comment by JJL772** [comment]
Completed by @Blenderiste09
