### ISSUE TITLE
Bug: Glass func_breakable does not render when game is paused in Panorama (DX9 only)

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#627]
### Describe the bug
Adding CS:GO style glass to Triple Laser, I noticed it would not render on one side when I launched the game using DX9. DX11 renders fine however. I'm not sure if this is related to the bug where the light bridge would only render on one side, but it seems like too big of a coincidence.

![image](https://user-images.githubusercontent.com/26600014/118009897-7e0a6a00-b31c-11eb-9f57-a3ca7ebe0434.png)
![image](https://user-images.githubusercontent.com/26600014/118009799-6501b900-b31c-11eb-98af-6de570848197.png)

### To Reproduce
1. Download this file and rename it to a VMF: [triple_laser_glass.log](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/6467517/triple_laser_glass.log)
2. Compile + run it, it should have the right launch arguments with Hammer's default
3. Enter the test chamber and pause the game, the glass will disappear
4. Use `noclip` to go around the glass
5. Pause the game, the glass will not disappear

### Expected behavior
The glass always renders.

### Operating System
Reported on Windows 10.

**Comment by Luke18033** [comment]
Is this a `func_breakable_surf`? If so then this would be a duplicate of #606 (Panorama forcing backface culling).

**Comment by craftablescience** [comment]
It's just a `func_breakable`, but I think it's still a part of that overall issue.

**Comment by Luke18033** [comment]
Does that texture render its backface, or does the brush have separate textures on each side?

**Comment by craftablescience** [comment]
You're probably right that this is a duplicate, it only has one textured side and breaks on the backface. Closing in favor of #606
