### ISSUE TITLE
Pedestal Button Glowing Orange When Pressed (from portal reloaded)

### ISSUE THREAD

**Issue by Bloodstrike2003** [ChaosInitiative/Portal-2-Community-Edition#628]
So.. in Portal Reloaded there is a pedestal button where if you press it, it glows orange. Unlike the others that don't glow orange.
![orange pedestal button](https://user-images.githubusercontent.com/78393178/118301297-bf735480-b497-11eb-8596-b439217eafb3.jpg)

So... yeah. Just thought it would be a nice feature to have.

**Comment by RandomCatDude** [comment]
I think this would be easily doable with a custom model that has a second skin for that, and some outputs on the prop_button to set its own skin. So I'm not sure it'd be necessary to have it implemented in P2:CE.

**Comment by Luke18033** [comment]
Indeed, that model has been around since long before Reloaded, and it doesn't require code access to use. The main improvement P2CE could make here is to allow changing `prop_button`'s model without `RunScriptCode`, but there's already #130 for that.
