### ISSUE TITLE
Bug: Crashes due to r_sequence_old_order

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#629]
### Describe the bug

With r_sequence_old_order set to 1, players will crash when loading into a coop match, and on level transition when instances are in the sdk_content folder. This cvar was introduced as a fix for animation snapping (See #352).

### To Reproduce
1. Join coop
2. crash

### Expected behavior

Should not crash.

**Comment by CitadelCore** [comment]
Fixed by Internal !586
