### ISSUE TITLE
Allow rotational changes in gravity 

### ISSUE THREAD

**Issue by mariovct** [ChaosInitiative/Portal-2-Community-Edition#63]
Add the ability to rotate gravity. Basically having the same effect as rotating the map, but without the buggy and unreliableness of it.

**Comment by BlightedLight** [comment]
There will be no need to rotate the map, this can be implemented properly.

**Comment by Luke18033** [comment]
That's exactly what this issue was suggesting.

**Comment by BlightedLight** [comment]
It wasn't worded very well.

**Comment by ozxybox** [comment]
Superseded by https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/293.
