### ISSUE TITLE
Bug: Reflector cube physics broken when reflecting laser

### ISSUE THREAD

**Issue by Montydog9** [ChaosInitiative/Portal-2-Community-Edition#633]
### Describe the bug
When a reflector cube is place on top of another physics object (e.g. a cube) and wait for its physics to be disabled while its reflecting a laser it will no longer respond to other physics object and therefore its physics will not reactivate causing it to hover in the air.

> ![image](https://user-images.githubusercontent.com/44322659/118381575-15eda980-b5e4-11eb-9957-3a039a2355c8.png)

### To Reproduce
Steps to reproduce the behaviour:
1. Open map with laser and reflector cube
2. Place reflector cube on top of another physics object with a laser going into the reflector cube
3. wait for motion to pause on both objects
4. remove physics object from underneath the reflector cube
3. Physics will give up and the cube will float

### Expected behaviour
The reflector cube should fall when the object underneath it is removed and not float.

**Comment by JJL772** [comment]
I think this is a bug in vanilla portal 2? We could definitely look into fixing it, but it might cause other unintended issues in custom maps or in the campaign. They disable physics on those to prevent them from moving while you're solving other parts of the puzzle that may be dependent on the laser.

**Comment by Montydog9** [comment]
maybe you could have a hit detection system that enables physics on sleeping objects if another object that is touching the sleeping object is awaken, that could possibly work but I'm not familiar with this sort of thing so I'm just shooting an idea into space.

**Comment by mlugg** [comment]
Fixed for next release - the fix is behind a cvar reflector_cube_freeze_fix, enabled by default, since speedrunners use this glitch.

**Comment by DarviL82** [comment]
Enabled by default? I thought all bugs and glitches of this game would be fixed, and then you could enable them again at any point optionally. I remember Citadel saying that a cfg would be provided to run all the commands/cvars related to speedrunning.
I just think it makes more sense to have a bug like this fixed by default, since there are way more casual players. (Don't get me wrong, I love the speedrunning community)

**Comment by Luke18033** [comment]
Enabling the cvar fixes the bug.

**Comment by mlugg** [comment]
What Luke18033 said - sorry, should have made that clearer

**Comment by DarviL82** [comment]
Oh, I'm sorry haha
