### ISSUE TITLE
Bug: VScript GetOrigin does not function properly.

### ISSUE THREAD

**Issue by koerismo** [ChaosInitiative/Portal-2-Community-Edition#641]
### Describe the bug
`GetOrigin`, `GetCenter`, and other position-related getter functions return completely inaccurate vectors.

These usually consist of `0`, `nan`, and `24482254884451565827612219321352192`.

### To Reproduce
1. Create script that utilizes `GetPlayer().GetOrigin()`
2. Witness terribleness.

### Expected behavior
Functions return garbage numbers.

**Comment by DrMeepster** [comment]
Duplicate of ChaosInitiative/Chaos-Source#50

**Comment by JJL772** [comment]
Duplicate as mentioned above, but thanks for the bug report
