### ISSUE TITLE
Bug: Co-op gesture and ping menus highly broken

### ISSUE THREAD

**Issue by EchoesForeAndAft** [ChaosInitiative/Portal-2-Community-Edition#658]
The gesture and ping menus in co-op always render very brokenly. No steps required to reproduce, it is always broken. Only tested on Windows. Unlikely to be OS-specific.

This is what they look like:
![image](https://user-images.githubusercontent.com/71880558/123737237-f2599680-d8e5-11eb-94ce-e6881a47cbc6.png)
![image](https://user-images.githubusercontent.com/71880558/123737301-0b624780-d8e6-11eb-9c81-44540d010a6c.png)

**Comment by ashifolfi** [comment]
Did a quick test in nightly branch:

https://user-images.githubusercontent.com/29577987/180835293-8a49e7a7-961c-474a-af9e-19125678d9ee.mp4

It works fine now! Video proof provided

**Comment by AWildErin** [comment]
Thanks for testing!
