### ISSUE TITLE
Bug: Third-person player animations have no interpolation

### ISSUE THREAD

**Issue by EchoesForeAndAft** [ChaosInitiative/Portal-2-Community-Edition#659]
All third-person player animations don't interpolate between their frames. Instead they just snap, leading to what looks like very bad stop motion animation.

Footage:
https://user-images.githubusercontent.com/71880558/123740187-5e8ac900-d8eb-11eb-8f01-8e595f5201bc.mp4
https://user-images.githubusercontent.com/71880558/123740634-1a4bf880-d8ec-11eb-8a41-8216c4e49e4b.mp4

**Comment by FrozenDragon0** [comment]
I'm pretty sure I remember telling @JJL772 the animation issue in coop in thirdperson when I did a session with him. Wasn't aware of the Singleplayer one.

**Comment by JJL772** [comment]
It exists in SP too, but not that noticeable since you only ever see yourself through portals
