### ISSUE TITLE
fix fizzler sounds always playing.

### ISSUE THREAD

**Issue by Fennecai** [ChaosInitiative/Portal-2-Community-Edition#66]
the fizzler sounds are super broken in portal 2. when a fizzler turns off; there are still a lot of times where it's sound can still be heard looping- likewise, even fizzlers that are set to be invisible, also have looping sounds still audible.

It would be great if the fizzler sounds were more reliable and they really were based on the visibility and active state of the fizzler, instead of whatever wacky garbage it does now.

**Comment by SpyceTewan** [comment]
Definitely fixed them playing when invisible; The other issue is difficult to reproduce, I put some extra code in place that should always stop and replay the sounds properly, so let's just see
