### ISSUE TITLE
Add windows 7 support

### ISSUE THREAD

**Issue by Godohwar** [ChaosInitiative/Portal-2-Community-Edition#662]
Windows 7 support

The latest python doesn't support win7 meaning maps do not compile right with win7. Some people still use this OS and having it so they can't use p2ce isn't right. Having a separate branch of p2ce that uses python 3.8 instead of 3.9 would fix this

**Comment by ENDERZOMBI102** [comment]
iirc the postcompiler uses some 39 features

**Comment by JJL772** [comment]
Not going to fix this. Windows 7 is EOL, and we're not going to be forking postcompiler to fix this.

**Comment by CitadelCore** [comment]
FYI, the only version of Windows we officially support is Windows 10.
