### ISSUE TITLE
Bug: Hammer cannot mount games unless they are on C drive

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#666]
### Describe the bug
First, a bit of backstory:

I have all my video games stored on an external drive D. Portal 2, P2:CE, you name it. Recently I wiped my main drive and put a fresh install of Windows on it. The next time I launched P2:CE's Hammer, I got a message saying this:
![image](https://user-images.githubusercontent.com/26600014/125709280-82181977-3f9a-4967-9202-f4a628144fb2.png)
Other people are reporting similar behavior with different causes, like Trico.

### To Reproduce
1. Honestly I have no idea.

### Expected behavior
Hammer launches reliably with Source games on an external drive.

### Operating System
Reported on Windows 10.

**Comment by JJL772** [comment]
As was discussed in the discord:
1. p2ce is still mounting games properly
2. hammer will mount games on the C: drive, but nowhere else
This is related to hammer init code

**Comment by craftablescience** [comment]
> 
> 
> As was discussed in the discord:
> 
>     1. p2ce is still mounting games properly
> 
>     2. hammer will mount games on the C: drive, but nowhere else
>        This is related to hammer init code

Woops sorry,  forgot to specify! Thanks

**Comment by Luke18033** [comment]
I have all of my games on a secondary drive and this works fine?

**Comment by craftablescience** [comment]
It did for me as well -- until I reset my OS

**Comment by Trico-Everfire** [comment]
i have this problem too :(

**Comment by JJL772** [comment]
It's an odd bug lol.

**Comment by craftablescience** [comment]
Likely superseded by https://github.com/ChaosInitiative/Chaos-Source/issues/192
