### ISSUE TITLE
Bug: HL2 Jalopy and Jeep cannot activate turbo mode

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#681]
### Describe the bug
The Jalopy and Jeep do not receive a speed boost when pressing the LShift key. I believe this is because there is no sprint key.

### To Reproduce
1. Run `map d2_coast_03` with HL2 mounted
2. Drive the jeep, and observe you cannot activate the speed boost
3. Bind a key to `+speed`
4. Observe pressing that key activates the speed boost

### Expected behavior
The jeep and jalopy go faster when you press LShift.

### Operating System
Reported on Windows 10.

**Comment by Luke18033** [comment]
Does binding a key to `+speed` allow the boost to activate when that key is held? (Make sure you don't have that command aliased to host_timescale which a lot of people do.)

**Comment by craftablescience** [comment]
The keybind works, so it looks like it's indeed because there is no sprint key in P2:CE.

**Comment by Luke18033** [comment]
Then I would consider this to be working as intended, normal Portal maps don't really need a sprint key. The [custom keybind system](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/282) could be used to set one if you needed that.
