### ISSUE TITLE
Feature: prop_under_door and prop_portal_door

### ISSUE THREAD

**Issue by KaziPlays** [ChaosInitiative/Portal-2-Community-Edition#690]
### Which component should be improved?

Entity

### Describe your suggestion

```markdown
These entities would work as prop_testchamber_door, but with different models.

prop_under_door is an Old Aperture door.

prop_portal_door is a P1 Door
```

### Expected result

```markdown
The entities work like prop_testchamber_door.

However, I want prop_portal_door to have a skin option to select between 3 options: Clean, Overgrown, F-Stop.

The Clean skin is normal, the Overgrown skin is in some beta screenshots, it's a turned off version of the P1 door, and If I recall correctly, the door model in P2 has skins and the second skin is the unused overgrown door.

The F-Stop skin is the P1 door with the F-Stop color pallete.

Images of the Overgrown and F-Stop skin  are going to be sent by me
```

**Comment by KaziPlays** [comment]
Overgrown skin:

![Wheatley_floor_Test_Chamber_08](https://user-images.githubusercontent.com/72144613/129619674-75a9aed1-7c90-412b-8e5b-bb08da9e727f.jpg)

F-Stop skin:

![images (54)](https://user-images.githubusercontent.com/72144613/129619694-6d7835c0-0937-42c2-9919-d77c3b85d88d.jpeg)

**Comment by Konclan** [comment]
Wouldn’t it just be easier if prop_testchamber_door had a model option instead of adding new entities. Which is already a suggestion I believe.

**Comment by KaziPlays** [comment]
You are the ones that choose so... Id

**Comment by Konclan** [comment]
#130, also Im not a dev

**Comment by Luke18033** [comment]
Indeed, we'll just want to add model and sound customization for the existing entity.
