### ISSUE TITLE
Feature: Face Edit Texture: Replace Texture Properties

### ISSUE THREAD

**Issue by kittymatthew** [ChaosInitiative/Portal-2-Community-Edition#691]
### Which component should be improved?

Other

### Describe your suggestion

Currently, the Replace Texture dialog in the FES is limited to only being able to replace the textures and not properties of that texture such as lightmap scale. Being able to have an option to replace the properties of the selected texture would be extremely useful, such as setting all faces using material X to have a lightmap scale of 4.

### Expected result

On the face-edit dialog, there should be a check-box that enables options found in the FES, such as lightmap scale and texture alignment. Once these fields are set, and 'Replace' is pressed, the options should be applied to all textures as if they were applied individually.

**Comment by hexaflexahexagon** [comment]
You can already select "Mark but do not replace", then open the face edit sheet and make changes to all instances of that texture in the map. This would save a click but I'm not sure how necessary it is since it's already possible

**Comment by kittymatthew** [comment]
That is completely my fault that I never noticed that. In that case, this feature wouldn't really be necessary then. Sorry!
