### ISSUE TITLE
Bug: Turrets breaking a Func_Breakable crashes game.

### ISSUE THREAD

**Issue by OssyFlawol** [ChaosInitiative/Portal-2-Community-Edition#695]
### Describe the bug

Self explanatory, if a Turret fires at a func_breakable entity it will crash the game, interestingly does not occur with func_breakable_surf

### To Reproduce

1. Open/make a map with a func_breakable
2. Spawn a turret
3. By tipping turret over or standing infront of turret, let turret shoot at the func_breakable entity
4. Game should crash

### Expected Behavior

func_breakable should break as expected and not crash the game.

**Comment by JJL772** [comment]
Fixed
