### ISSUE TITLE
Feature: Add more console commands

### ISSUE THREAD

**Issue by KaziPlays** [ChaosInitiative/Portal-2-Community-Edition#697]
### Which component should be improved?

Other

### Describe your suggestion

Portal 2 already has their own console commands, but P2:CE should add more commands.

Here are some commands:

ent_create_paint_bomb_stick - spawns an Adhesion Gel bomb;

ent_create_paint_bomb_reflect - spawns a Reflection Gel bomb;

ent_create_p2ce_shrodinger_cube - spawns a Shrodinger's cube; 

ent_create npc_hover_turret - spawns a Hover Turret;

ent_create npc_rocket_turret - spawns a Rocket Turret;

ent_create prop_glados_core - spawns a P1 core;

impulse 101 should give you the portal gun and the paint gun.

Guns: (use with give or ent_create)

weapon_paintgun - spawns a Paint Gun;

weapon_crowbar;

weapon_physcannon;

weapon_stunstick;

weapon_pistol;

weapon_357;

weapon_alyxgun;

weapon_smg1;

weapon_ar2;

weapon_shotgun;

weapon_crossbow;

weapon_frag;

weapon_rpg;

weapon_hopwire;

weapon_striderbuster;

weapon_bugbait;

weapon_annabelle;

weapon_citizensuitcase;

weapon_citizenpackage;

weapon_oldmanharpoon;

weapon_cubemap;

Other unlisted commands include: Other HL2 commands.

Another addition I would like to ask of is adding custom console commands for Chaosscript entities.

### Expected result

You open the console and type the command.

**Comment by OssyFlawol** [comment]
...Most of these already exist.

**Comment by Luke18033** [comment]
Do you understand how these commands actually work? `ent_create` can spawn any entity, it's not tied to specific ones. The other commands you listed already exist.
