### ISSUE TITLE
Bug: Wheeled vehicles crash on linux

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#707]
### Describe the bug

Wheeled vehicles crash when spawned. Only happens on Linux. 
Airboat is fine but is still buggy. 

### To Reproduce

1. Run ch_createjeep on linux 
2. crash

### Expected Behavior

bug should not happen

### Operating System

Linux

**Comment by Luke18033** [comment]
Fixed now?

**Comment by JJL772** [comment]
yep, forgot to close this
