### ISSUE TITLE
Fizzling vehicles the player is in crashes the game

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#708]
### Describe the bug

The title says it all. This happens because the player is parented to the vehicle, so fizzling it deletes the player.

### To Reproduce

1. Open `sp_a2_fizzler_intro`
2. Spawn a drivable vehicle
3. Drive it into the fizzler
4. Game crashes

### Expected Behavior

Players should be kicked out of vehicles and be unable to re-enter them when they're being fizzled.

### Operating System

Tested on Windows 10

**Comment by Trico-Everfire** [comment]
this happened to me too, i was fucking around with the vehicles in a random map, got flung across the room, hit a fizzler and it crashed my game. i guess the game isn't expecting the vehicle to just dissapear out of nowhere.

**Comment by Trico-Everfire** [comment]
An unexpected side effect of this bug is that if you were to be flying in the void while this happens (when fizzling, you exponentially rotate around the vehicle while flying away, causing you to phase through walls as you do) The game will not crash, rather, cause you to be softlocked in the void, the console can be accessed and you can quit out of the map or reload it.

**Comment by Luke18033** [comment]
It is deleting the player because they're parented to the vehicle, if you `ClearParent` on the player before the vehicle fully fizzles it won't crash. Since fizzling objects become nonsolid `simple_physics_props` it becomes impossible to enter/exit the vehicle and you become detached from it, allowing you to noclip freely (although still parented to the vehicle's movement). If you happen to be out of bounds when the player is deleted it won't crash, which seems to just be a general thing (running `ent_remove_all player` while out of bounds also won't crash), no idea what's up with that.

So the solution seems to be to just force the player to dismount vehicles before they start dissolving.

**Comment by Trico-Everfire** [comment]
yes. or to not run delete on the player if they're in it. making exceptions for both players and NPCs.

**Comment by Luke18033** [comment]
No the player needs to just be dismounted, even if you didn't delete them there are still other buggy behaviors that would result like getting stuck in noclip

**Comment by JJL772** [comment]
Will be fixed in next update. The player just gets ejected in place without exit anims or anything. Easiest solution and the most correct looking.

**Comment by Luke18033** [comment]
Fixed on bsp limits branch
