### ISSUE TITLE
dynlights for tractor beams, lasers emitters and light bridges

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#71]
Portals already have dynamic lights via a console command, however light bridges, funnels and lasers all don't have dynlights and it would make sense for them to emit light. This is partially already possible but I'm not totally sure how mappers do it in Hammer, but it'd be nice for it to be a default feature.

**Comment by AddMGH** [comment]
Also the portals should have a dynlight by default, possibly another gfx option for dynlighting for things such as these?

**Comment by BlightedLight** [comment]
This is possible to implement by enabling a static light's lightmaps whenever a given element turns on. This would be super unconventional to implement as it would require an array of dlights being spawned along the paths of the laser/bridge/funnel. Closing this issue.
