### ISSUE TITLE
Feature: Panorama Settings Menu

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#710]
### Which component should be improved?

UI/UX

### Describe your suggestion

We need a settings menu with the following tabs (in no particular order): 
1. Game options (Global options, portal colors?, weird preferences that don't affect gameplay)
2. Audio Options (Volume, device selection, whatever)
3. Input Bindings
4. Controller Options (Choose controllers to enable, idk)
5. Graphics Options

We still need to decide on a design.

### Expected result

Panorama settings menu :trollface:

**Comment by craftablescience** [comment]
Closing this as superseded by #745
