### ISSUE TITLE
Bug: monitor textures offset camera

### ISSUE THREAD

**Issue by Gravy59** [ChaosInitiative/Portal-2-Community-Edition#715]
### Describe the bug

Using the func_monitor with a camera, if you use certain textures you will offset the camera to the right or the left. This does not happen when you use `monitornoise`

### To Reproduce

1. Create map file
2. Add `func_monitor` with a texture other than `monitornoise`
3. Add camera (center it on something to see better)
4. Compile map
5. See the error
~~6. Scream~~

### Expected Behavior

Camera shouldn't be offset when using `func_monitor`

**Comment by Luke18033** [comment]
This is a little vague, can you attach a screenshot?

**Comment by Gravy59** [comment]
![image](https://user-images.githubusercontent.com/58180094/133481627-ea435e09-ee6d-4221-8437-5c68e4c52cf7.png)
This is the camera, it should be centered in the map
![image](https://user-images.githubusercontent.com/58180094/133481804-4fc5b031-f294-4dfb-bc21-a4111070dfec.png)
This is the monitor, it uses `dev_tvmonitor1a`

![image](https://user-images.githubusercontent.com/58180094/133482609-6f4872be-e4f1-450c-8950-7ea46992c8f1.png)
The camera should be centered, but it is offset to the right.

**Comment by Luke18033** [comment]
The texture is scaled wrong, you need to fit it to the monitor screen.

**Comment by Gravy59** [comment]
Interesting. Human error then. Sorry!

**Comment by Gravy59** [comment]
![image](https://user-images.githubusercontent.com/58180094/133495691-4115d1ad-c545-4955-88cb-11c7c6e10f2b.png)
Actually, that didn't fix the issue
![image](https://user-images.githubusercontent.com/58180094/133495804-e3b904ae-b32e-4323-b8b6-ab865c396487.png)

**Comment by Luke18033** [comment]
I'm not sure what's going on, maybe try adjusting the texture alignment/scale manually? This definitely works, that material is used for all of Wheatley's monitors.

**Comment by Gravy59** [comment]
It could be because I'm on a pre-p2 branch

**Comment by Gravy59** [comment]
> 
> 
> I'm not sure what's going on, maybe try adjusting the texture alignment/scale manually? This definitely works, that material is used for all of Wheatley's monitors.

FIXED! HA! Thank you!

**Comment by Luke18033** [comment]
Ah, I'd assume it's some bug with Hammer's texture alignment buttons then. If it still happens in P2CE Hammer, open a new issue for it on [Chaos-Source](https://github.com/ChaosInitiative/Chaos-Source/issues).
