### ISSUE TITLE
Bug: Panorama debugger crashes game

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#719]
### Describe the bug

When I open the Panorama debugger, it crashes.

### To Reproduce

1. Open game with `-dev`
2. Close the console
3. Press F6
4. Observe window frame flicker then crash

### Expected Behavior

The debugger should not crash the game.

### Operating System

Reported on Windows 10.

**Comment by JJL772** [comment]
Closed in favor of https://github.com/ChaosInitiative/Chaos-Source/issues/202
