### ISSUE TITLE
Bug: Quicksaving and Quickloading in certain maps will halt progression.

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#720]
### Describe the bug

In certain maps while playing p2ce (currently only know 1 so far, but am going to test all maps) will halt progression, in sp_a2_core example quicksaving and quickloading before the drop into glados's trap will cause the door that normally falls down upon clicking to no longer fall down, never triggering glados's speech and preventing progression.

~~(Speculation.)
it's known that VPhysics in the past caused issues with P2CE loading maps, maybe certain triggers get confused/destroyed upon quick saving/loading.~~

### To Reproduce

1: Open map: sp_a2_core.
2: quicksave and quickload anywhere between the starting point of the map and the trap glados set up.
3: fall into her trap and open the door. the handle will go down but the door never falls.

### Expected Behavior

quicksaving and quickloading not preventing game progression.

**Comment by Trico-Everfire** [comment]
it happens on sp_a1_wakeup too, with wheatley, quick saving and loading causes wheatley to "dissapear" but you can still hear him at the point you start the map.

**Comment by JJL772** [comment]
Wheatley falls through the map in that instance. He is a physics object, more specifically a sphere. It either has collisions disabled or just doesn't get added back to the grab controller.

**Comment by Trico-Everfire** [comment]
> Wheatley falls through the map in that instance. He is a physics object, more specifically a sphere. It either has collisions disabled or just doesn't get added back to the grab controller.

that'd make sense, but that's strange that it only happens on reload, i feel like physics objects in general are a bit messed up, first the funnel frankencubes (which were fixed by forcing them to stay cubes, something that doesn't happen in P2), the glados trap door, and now wheatley's grab controller. i feel like this is a bug with vphys itself.

**Comment by JJL772** [comment]
Can this be re-tested? I'm pretty sure this was fixed

**Comment by JJL772** [comment]
Neither of these things happen in our dev build, I'm just going to assume it's the same case for the steam build, as we specifically fixed these problems in December.
