### ISSUE TITLE
Replace Bink

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#73]
bink bad less bink

**Comment by SpyceTewan** [comment]
Stop spamming our issues

**Comment by CitadelCore** [comment]
We won't replace it, but we could consider adding an alternative. It won't be a priority though.

**Comment by AddMGH** [comment]
was referring to https://discordapp.com/channels/663715905267564564/720250912781893674/720911331020242975
