### ISSUE TITLE
Bug: Func_breakable_surf crashes the game when broken.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#734]
### Describe the bug

Self explanatory pretty similar to this bug: https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/695 just on different entity.

### To Reproduce

1. Open a map that contains a func_breakable_surf such as escape_01 from Portal 1.
2. Spawn either a turret or rocket turret to shoot at the entity or throw a physics object such as a chair with extreme force at the entity to break it.
3. Game should crash upon the entity being broken.

### Expected Behavior

Game should not be crashing the func_breakable_surf should be breaking as expected.

### Operating System

N.A

**Comment by craftablescience** [comment]
Not sure when this was fixed, but I don't get this problem anymore. Can you test it again?
