### ISSUE TITLE
Bug: Saves crashing on DX11

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#736]
### Describe the bug

Running the game in dx11 mode causes saves to crash

### To Reproduce

1. Open p2ce in dx11 
2. open map
3. Type `save idkbruh` or press F6
4. crash

### Expected Behavior

It should not crash!!

**Comment by Trico-Everfire** [comment]
saves have been bugging a lot actually. not just dx11, #720 explains some bugs also happening with saving and loading in general.

**Comment by JJL772** [comment]
Fixed in dev, will be in next release
