### ISSUE TITLE
Portal Stories: Mel Bug: Softlock in sp_a2_garden_de.

### ISSUE THREAD

**Issue by KaziPlays** [ChaosInitiative/Portal-2-Community-Edition#738]
### Describe the bug

![Screenshot_20211006-150246](https://user-images.githubusercontent.com/72144613/136258841-a68386a2-97b2-4549-8b53-1a4dca2c3d89.png)

You can jump through this railing and get softlocked on the other side.

### To Reproduce

1- Get to that part;

2- Go to the top of the stairs;

3- Jump through the railing.

### Expected Behavior

I expected there to be a playerclip but there was not.

**Comment by JJL772** [comment]
Is there a clip there? If not, it's a map issue and we're obviously not fixing that

**Comment by JJL772** [comment]
Wait, you're not a playtester

this isn't an issue tracker for PSMel lol

**Comment by Mystical-Ace** [comment]
lol this is an issue tracker for P2:CE, not PS:M. We can't fix anything from that mod.

**Comment by KaziPlays** [comment]
What about #232?

**Comment by kittymatthew** [comment]
> What about #232?

That’s an issue with the renderer: similar models with the same characteristics as the tunnel model with Mel won’t render. It’s not a PS:M issue, it’s an issue related to CE’s renderer, with a Mel model bringing it to the dev’s attention.
