### ISSUE TITLE
Bug: Grouping fizzlers causes strange flying line as well as large fizzler volume

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#739]
### Describe the bug

when creating trigger_portal_cleansers i grouped 2 together, 2 fizzlers on other sides of the room, when i compiled the map (no need for vvis or vrad) i noticed a strange flying line, normally seen on the fizzlers as a visual effect ( a small line slowly going down, like a scanline on an old tv slowed down), i didn't think much of it, however, when i started shooting with the portal gun, I noticed that the volume in between the fizzlers had become part of the cleansers as well, disallowing me to shoot within the volume.

### To Reproduce

1: Create map with 2 fizzlers, a good few feet apart from each other.
2: make them both trigger_portal_cleansers.
3: group them.
4: give player portal gun.
5: compile.
6: shoot within the volume, or try to shoot through the volume. unable to shoot through them, also notice the flying line.

### Expected Behavior

grouping fizzlers no longer causes the flying line nor the volume.

**Comment by Luke18033** [comment]
You're not supposed to tie multiple fizzlers to the same entity, this is sort of intentional...
