### ISSUE TITLE
Easier ways to rotate objects (Hammer)

### ISSUE THREAD

**Issue by DarviL82** [ChaosInitiative/Portal-2-Community-Edition#74]
Instead of using skip brushes to rotate things with different offsets, be able to change the rotation type to for example:
* The center of the selected object.
* The center of another object.
* The center of the world.
* Or from a 3D Cursor, like the one from blender.

Talking about the 3D Cursor, I think it would be a good idea, to be able to enable/disable it, for some special cases. Note the possibilities with a 3D cursor, like for example put it at the center of a surface.

**Comment by SpyceTewan** [comment]
We have not decided yet whether to remake hammer in panorama or not

**Comment by L89David** [comment]
Yeah I know, this is just an idea at any case :)

**Comment by ozxybox** [comment]
Superseded by https://github.com/ChaosInitiative/Chaos-Source/issues/209.
