### ISSUE TITLE
Fix "catapult can't hit target" console spam

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#751]
### Describe the bug

When developer mode is on and a `trigger_catapult` has its `ent_text` visible, the console will be spammed with `Catpult can't hit target, add more speed!`, regardless of whether the catapult can actually hit its target. It can be filtered out using `con_text_filter_out`, but I'm not sure if this warning is really needed in the first place; if a catapult ever *actually* couldn't hit its target, it would be rather obvious when you tried to use it.

### To Reproduce

1. Open any map with `trigger_catapult`s
2. Turn on `developer 1`
3. Run `ent_text trigger_catapult`
4. Spam

### Expected Behavior

The warning should not appear.

### Operating System

Tested on Windows 10

**Comment by ENDERZOMBI102** [comment]
tested, didn't happen on new update

**Comment by JJL772** [comment]
Thanks for verifying a fix!
