### ISSUE TITLE
Fix "weighted cube has no model name" warnings

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#752]
### Describe the bug

Spawning a cube without a `model` keyvalue set produces a warning message in the console. TeamSpen's addons fix this by adding that keyvalue (which is used to set the Hammer model display), but the warning still appears when spawning cubes from the console or from maps compiled without the addons, so it'd be nice to have it fixed properly.

Related to #270 (the same bug for paint bombs).

### To Reproduce

1. Open any map
2. Run `ent_create prop_weighted_cube`
3. The warning message appears

### Expected Behavior

The warning message should not appear.

### Operating System

Tested on Windows 10

**Comment by ENDERZOMBI102** [comment]
tested, didn't happen on new update
