### ISSUE TITLE
Bug: scripts/game_sounds_world.txt from Portal 2 is missing in manifest

### ISSUE THREAD

**Issue by TheEnderek0** [ChaosInitiative/Portal-2-Community-Edition#753]
### Describe the bug

"precache_file"		"scripts/game_sounds_world.txt"

is missing in game_sound_manifest.txt

that means that some props are missing sounds, and many usable sounds from Portal 2 are missing.

### To Reproduce

1. Go to Portal 2 Community Edition\p2ce\scripts
2. Open game_sounds_manifest.txt
3. There's no 
	"precache_file"		"scripts/bms/game_sounds_world.txt"
line.

### Expected Behavior

All sounds from Portal 2 should be ported into P2CE

**Comment by JJL772** [comment]
This file exists in our game_sounds_manifest.txt. Do you mean a different file?

**Comment by JJL772** [comment]
It's definitely not missing that line, it's under `// HL2 World, Ambient Generic, Items, Physics, Vehicles`
