### ISSUE TITLE
Unhide mp_dev_wait_for_other_player

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#756]
### Which component should be improved?

Other

### Describe your suggestion

Disabling this cvar allows loading coop maps with only one person, but it's set as dev-only for some reason. When enabled in base P2 using the cvar unhider plugin, it works without any issues, so I see no reason why it should be hidden.

### Expected result

The cvar should not be dev-only.

(Additionally can we please have ChaosInitiative/Chaos-Source#20 soon?)

**Comment by AWildErin** [comment]
Done as of 0.7.0
