### ISSUE TITLE
Splitscreen coop causes a crash

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#757]
### Describe the bug

Loading any map in splitscreen coop causes an instant crash. Possibly specific to the developer branch.

### To Reproduce

1. Run `ss_map mp_coop_lobby_3`
2. Loading screen appears, then it crashes.

### Expected Behavior

It should not crash.

### Operating System

Tested on Windows 10

**Comment by FrozenDragon0** [comment]
Can confirm that this is a issue, tested on dev branch myself and got a crash after the loading screen finished.

**Comment by Luke18033** [comment]
You don't have access to the `developer` branch, that means it must happen on `playtest_beta` as well (or you got the `developer` branch password somehow?)

**Comment by FrozenDragon0** [comment]
Oh 2 branches? Wasn't aware, well I did test this on the playtest_beta and still crashed.

**Comment by JJL772** [comment]
This'll be fixed in the next update. `gl_clear_randomcolor` was also crashing due to the same issue

**Comment by JJL772** [comment]
Can you confirm a fix?

**Comment by Luke18033** [comment]
Yep
