### ISSUE TITLE
gl_clear turns Atlas' view black in splitscreen

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#767]
### Describe the bug

When `gl_clear` is enabled, Atlas' view turns black in splitscreen. This is an issue in P2 for `gl_clear_randomcolor`, but now happens with regular `gl_clear` in P2CE as well.

Not sure what would happen here if more than 2 players were present. Probably all of them except the last would end up with black screens.

### To Reproduce

1. Run `ss_map mp_coop_lobby_3`
2. Atlas can see
3. Run `gl_clear 1`
4. Atlas has gone blind

### Expected Behavior

It should not turn Atlas' view black.

### Operating System

Tested on Windows 10

**Comment by JJL772** [comment]
Changed some "pointless" behavior with gl_clear...apparently it wasn't pointless afterall!

**Comment by JJL772** [comment]
I've fixed this, so yeah. Coop is broken in other ways now, unrelated to this.
