### ISSUE TITLE
Fix players getting pushed diagonally while standing still underwater

### ISSUE THREAD

**Issue by ErinRoseWebs** [ChaosInitiative/Portal-2-Community-Edition#768]
### Which component should be improved?

Gameplay

### Describe your suggestion

Replace the default flowmap with one that doesn't affect entities, so that way players aren't pushed around underwater. This shouldn't affect liquids that have a specified flowmap. 

### Expected result

With the replaced flowmap, the player should be able to stand completely still underwater without being pushed around.

**Comment by Luke18033** [comment]
Flowmaps are just a material effect, they have nothing to do with players getting pushed underwater. That would be good to fix though.

**Comment by ErinRoseWebs** [comment]
ahhh ightyy

**Comment by JJL772** [comment]
> Flowmaps are just a material effect, they have nothing to do with players getting pushed underwater. That would be good to fix though.

I always figured this was intentional. Looking into it now

**Comment by JJL772** [comment]
It was a typo in valve's code. Will be fixed in the next update

**Comment by ErinRoseWebs** [comment]
pog, thanks yall!
