### ISSUE TITLE
Bug: EmitLaser issues

### ISSUE THREAD

**Issue by TheEnderek0** [ChaosInitiative/Portal-2-Community-Edition#769]
### Describe the bug

EmitLasers has several issues:

EmitLaser 1 can be executed multiple times, causing the cube to emit multiple lasers at the same time, lagging the game and breaking the reflection mechanic.
Also if you do EmitLaser 1 more than one time, you can't disable it via EmitLaser 0
![image](https://user-images.githubusercontent.com/67070613/145581688-341acee5-3cbe-4d20-a525-09ad3e7feb53.png)

EmitLaser 0 crashes the game when laser isn't emitted from the cube.
If EmitLaser 1 wasn't previosuly called when EmitLaser 0 is called, it will result in an instant crash of the game.

### To Reproduce

-

### Expected Behavior

EmitLaser 1 should check if there is already a laser emitted
EmitLaser 0 shouldn't crash the game / check if there is no laser

**Comment by craftablescience** [comment]
Tested by someone else and resolved
