### ISSUE TITLE
Bug: Custom Model cube type property crashes the game

### ISSUE THREAD

**Issue by TheEnderek0** [ChaosInitiative/Portal-2-Community-Edition#770]
### Describe the bug

Selecting 6th option (custom model) in cube type keyvalue in prop_weighted_cube causes the game to crash on map load.
This isn't dependent on model you put as the model keyvalue it seems.

I think it might be relevant to #752 

### To Reproduce

1. Open hammer.
2. Make a simple map contaning 6 walls, just so you can fit a info_player_start and a prop_weighted_cube.
3. Place the prop_weighted cube and info_player_start.
4. In prop_weighted_cube select Custom Model as a Cube Type keyvalue.
5. Try to compile the map.
6. Game instantly crashes when loading the map.

### Expected Behavior

It shouldn't crash.

**Comment by craftablescience** [comment]
You're right, this was caused by #752, sorry about that. Should be fixed in the next build hopefully

**Comment by Luke18033** [comment]
On a related note, it'd probably be good to officially support setting custom cube models this way, currently it's basically just an undefined behavior that happens to do something useful.

**Comment by craftablescience** [comment]
This is definitely fixed
