### ISSUE TITLE
Bug: Vscript vector math is broken

### ISSUE THREAD

**Issue by TheEnderek0** [ChaosInitiative/Portal-2-Community-Edition#773]
### Describe the bug

Vscript vector math is broken.
It worked in the previous update (playtest branch)

Vector + vector makes this error
![image](https://user-images.githubusercontent.com/67070613/145851075-0949588a-79ca-4ec4-9422-ae7d0df0a0d3.png)
Even though all vectors are valid.

### To Reproduce

1. Make a script that adds two vectors.
2. Place logic_script in the map
3. Compile the map
4. The bug occurs

### Expected Behavior

Vector math should be working as in previous update.

### Operating System

Tested on Windows 11

**Comment by koerismo** [comment]
Could you paste the relevant parts of your code? It says you are trying to add a vector and an integer.

**Comment by TheEnderek0** [comment]
It's a fragment from sendificator code
`local origin = self.GetOrigin();`
`local tvec = EntityGroup[1].GetOrigin() - origin;`
`local tloc = origin + tvec;`

**Comment by JJL772** [comment]
This is fixed on our end, can you confirm that your code is now functional?

**Comment by TheEnderek0** [comment]
Fixed
