### ISSUE TITLE
weapon_portalgun Show PotatOS keyvalue is nonfunctional

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#776]
### Describe the bug

The Show PotatOS (`showingpotatos`) keyvalue on `weapon_portalgun` doesn't do anything when enabled.

### To Reproduce

1. Place `weapon_portalgun`
2. Enable Show PotatOS
3. Compile the map and pick up the gun
4. PotatOS does not appear.

### Expected Behavior

The keyvalue should make PotatOS appear.

### Operating System

Tested on Windows 10

**Comment by Trico-Everfire** [comment]
This has been an issue since the dawn of time, The VDC states as such, It'd be nice to have it be operational tho.

**Comment by JJL772** [comment]
this has been fixed
