### ISSUE TITLE
Catwalks have no transparency in DX11 mode

### ISSUE THREAD

**Issue by Lord-of-Squishe** [ChaosInitiative/Portal-2-Community-Edition#780]
### Describe the bug

(also posted in the Chaos Source github page)
Catwalk holes are non-transparent when P2CE is running in DX11 mode.

### To Reproduce

Launch P2CE in DX11 mode
Open any map wiht catwalks in it
Look at the catwalk

### Expected Behavior

The catwalk holes should be transparent.

### Operating System

Windows

**Comment by seagemgames** [comment]
I don't think it needs to be posted here as it isn't P2:CE specific, and affects the engine itself

**Comment by Lord-of-Squishe** [comment]
Yeah you're right, I'll close it.
