### ISSUE TITLE
Disable r_portal_fastpath by default

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#781]
### Which component should be improved?

Render

### Describe your suggestion

`r_portal_fastpath` is a cvar related to portal rendering which is enabled by default, and has several adverse effects:
- It limits the game to rendering 4 portals on-screen at once; any more than this will cause extreme visual corruptions.
- It locks portal borders to the default size, causing them to not match portals that have been resized (via the keyvalues or `Portals_ResizeAll`)
- It causes objects to randomly become invisible through portals if a `point_camera` is active.

The name of the cvar implies that these things are done for the sake of performance, but I have yet to see any actual case where having fastpath disabled is measurably slower than having it enabled. The one exception to this is when more than 4 portals are actually visible, but this is only "slower" with fastpath off because with it on this situation doesn't work at all.

For reference, my main computer is made up of mostly parts from around 2013, and I also once tried it on a 2012 MacBook with the same results (no measurable performance impact).

Momentum has supposedly now disabled fastpath by default and hasn't had anyone complain about bad performance, though they obviously use portals far less than the game literally called Portal. Regardless, without any real evidence that fastpath significantly affects performance, I think it's reasonable for us to disable it by default in P2CE. If after this change we start receiving complaints about portals slowing the game down, we can consider reverting it and/or some other alternative.

### Expected result

`r_portal_fastpath` should be disabled by default.

**Comment by JJL772** [comment]
Done in latest update (Thanks @Luke18033  lol)
