### ISSUE TITLE
Coop maps get stuck on a black screen

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#783]
### Describe the bug

When loading any Coop map in splitscreen, the game gets stuck on a black screen with only player 2's crosshair visible.
![image](https://user-images.githubusercontent.com/19228201/147797502-b4229c40-4dbe-4cda-95b0-912ac8d37949.png)
No idea if this still happens in online multiplayer.

### To Reproduce

1. Run `ss_map mp_coop_lobby_3`
2. Game gets stuck on a black screen

### Expected Behavior

It should not

### Operating System

Tested on Windows 10

**Comment by FrozenDragon0** [comment]
Are the bots spawning in one of the dark rooms outside the map that's failing to teleport them?

**Comment by Luke18033** [comment]
The coop bots don't spawn in dark rooms, that only happens in singleplayer. It's just a black screen.

**Comment by JJL772** [comment]
This is a dx11-only bug

**Comment by Luke18033** [comment]
Fixed, although you still can't move.
