### ISSUE TITLE
Bug: Coop remote view crashes the game.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#784]
### Describe the bug

Title says it all, whenever you press TAB to view your partners screen in coop the game immediately crashes.

### To Reproduce

1. Play coop with another playtester/dev.
2. Wait until the Calibration course cutscene is over or change the map to mp_coop_lobby_3
3. Press TAB or type +remote_view in console and see that your game will immediately crash.

### Expected Behavior

Your partners screen is meant to show properly like in normal Portal 2 and not crash the game.

### Operating System

N.A

**Comment by FrozenDragon0** [comment]
This issue seems to be fixed in the current version of the game.

**Comment by JJL772** [comment]
Going to close this then. If it happens again, please re-open!
