### ISSUE TITLE
Bug: "connect" Command Times Out

### ISSUE THREAD

**Issue by kyleraykbs** [ChaosInitiative/Portal-2-Community-Edition#795]
### Describe the bug

When hosting a session through the "map" console command, clients that attempt to connect to the server using the "connect (ip)" command will attempt to connect to the server until time out. The console will spew out the error of attempting to reconnect multiple times:

`[engine] Retrying public(ip:27015) . . .`

This happens regardless of port forwarding, version differences, and OS.

Please note that we have tested this out in normal Portal 2 and it works flawlessly. This means that it shouldn't be an issue with port forwarding.

### To Reproduce

1. Have the host type "map (MAPNAME)"
2. Before the host times out, have a client attempt to connect with "connect IP"
3. Observe the console debug info

### Expected Behavior

The client should connect to the server successfully.

### Operating System
All

**Comment by Luke18033** [comment]
This is definitely fixed
