### ISSUE TITLE
Launch Option "-maxplayers_override" Doesn't Change Maxplayers

### ISSUE THREAD

**Issue by kyleraykbs** [ChaosInitiative/Portal-2-Community-Edition#796]
### Describe the bug

When using the leftover "-maxplayers_override" launch option from CS:GO before starting P2:CE, the game's maxplayers will not be affected.

### To Reproduce

1. Add "-maxplayers_override" with a value of 3-30 and  "+map mp_coop_lobby_3" (just to make things easy)
2. Launch P2:CE
3. Once at the bot loading screen quickly turn on sv_cheats and spawn as many bots as possible
4. Observe how only 1 bot is able to initialize and how the others fail to initialize

### Expected Behavior

The "-maxplayers_override" launch option (or maxplayers console command) should override the maxplayers in the current session

### Operating System

All

**Comment by Luke18033** [comment]
This is sorta intentional, although I feel like we should enable it - it's a fairly hidden/advanced feature, we could use this as a way to test 3+ player multiplayer and see what's actually broken before making it available normally in-game.

**Comment by JJL772** [comment]
This launch option isn't in P2CE and we don't plan on supporting it either. `maxplayers` and `sv_portal_gamemode_override` (introduced in an upcoming update) are used to control this sort of thing
