### ISSUE TITLE
Bug: Semi-transparent portal overlays with fastpath

### ISSUE THREAD

**Issue by DarviL82** [ChaosInitiative/Portal-2-Community-Edition#797]
### Describe the bug

When setting `r_portal_fastpath` to 0 (now by default), closed portals seem to be rendered semi-transparent, thus letting us view the surface under them, including other overlays, such as signs or antlines. Note that this bug only occurs with DirectX11.
![image](https://user-images.githubusercontent.com/48654552/149607523-5f1be513-fd16-4c44-aa43-034faac1c69c.png)
![image](https://user-images.githubusercontent.com/48654552/149607566-f12d13e2-1c72-490b-94f2-90bbb8b94fa7.png)
Turning fastpath on fixes this bug.

### To Reproduce

1. Open any map.
2. Make sure you have the convar `r_portal_fastpath` set to 0.
3. Place a portal.

### Expected Behavior

The portal should render just like how it does with fastpath on:
![image](https://user-images.githubusercontent.com/48654552/149607635-31b85b04-239e-41fb-8828-8eb9361b500c.png)

**Comment by JJL772** [comment]
Will be fixed in next push
