### ISSUE TITLE
Settings Reset

### ISSUE THREAD

**Issue by AshleyAvacado** [ChaosInitiative/Portal-2-Community-Edition#798]
### Describe the bug

When I close the game or it crashes the vgui settings reset

### To Reproduce

1. change settings the apply them
2. close the game or make it crash

### Expected Behavior

The settings should save when closing out of the game

### Operating System

Linux (kubuntu)

**Comment by craftablescience** [comment]
@AshleyAvacado can you test this again? I can't replicate it

**Comment by Luke18033** [comment]
I think this is just because the game is crashing
