### ISSUE TITLE
Bug: Challenge mode crashes 

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#799]
### Describe the bug

Starting a map on challenge mode causes a crash

### To Reproduce

1. Start map on cm
2. crash

### Expected Behavior

Should not crash

**Comment by JJL772** [comment]
Will be fixed in next push

**Comment by slambo311** [comment]
To be honest, I don't think this should be that high priority. Challenge mode is basically just playing normally but with a bunch of counters, after all.
