### ISSUE TITLE
Bug: P2:CE's Nodraw is portalable.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#801]
### Describe the bug

As the title suggests, P2:CE's nodraw texture can have portals placed on it whereas in Portal 2 this is not the case.

### To Reproduce

Pretty simple to do, just launch any map and noclip out of bounds and place a portal on any nodraw surface.

![image](https://user-images.githubusercontent.com/18079316/152351601-1c0e3e0d-0d22-4e2f-93fa-26e125638088.png)

### Operating System

N.A

**Comment by luxeleios** [comment]
Wouldn't adding %noportal keyvalue to the vmt solve it? Unless it's already there.

**Comment by craftablescience** [comment]
yes, and I've opened a pr to do just that

**Comment by AWildErin** [comment]
This has been fixed. It will be in the next build when that goes live!
