### ISSUE TITLE
Open-source the P2:CE UI

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#802]
- [ ] Break up `chaosstyles.sass` into several files, and move them to the `controls` directory
- [x] Scan through and delete unnecessary JS files (especially the ones in the `common` and `popups` directories)
- [x] Remove `tools/demoui.xml` (make sure there are no engine hooks)
- [x] What is `browser/webkit.css`?? Answer: it is for HTML surfaces
- [x] Remove the privacy disclaimer in the readme

**Comment by AWildErin** [comment]
Open-sourced at: https://github.com/ChaosInitiative/p2ce-panorama-ui
