### ISSUE TITLE
Feature Request: Expand the customizability of hard coded testing elements 

### ISSUE THREAD

**Issue by luxeleios** [ChaosInitiative/Portal-2-Community-Edition#806]
### Which component should be improved?

Entity

### Describe your suggestion

This issue is meant to compile all of the desired and useful customization options for hard coded P2 and P1 testing elements that I can think of into one cohesive list. In some places this might reiterate the suggestions submitted by [ErinRoseWebs](https://github.com/ErinRoseWebs) on Jan 11th. 

The first suggestion would be to implement something like a config system, that allows custom maps to pack their own configs - each config would contain custom values for each keyvalue that has anything to do with the customization of a relevant entity class - paths to custom VFX materials, sounds, colors, particle systems names etc. The configs would then be picked up by the entity in hammer and hammer should also be able to save current entity settings to a config. This would make it possible to apply complex configurations by simply picking one from a list in hammer, instead of having to copy-paste an already configured entity around from one of your maps. 

### **For: prop_tractor_beam**
- Allow us to specify a custom vortex vmt as a replacement for the effects/tractor_beam.vmt
- Have normal/reversed states use two separate vmts for each state, so that each can be set separately 
- Allow us to set custom particles 
- Set custom sounds for entering, exiting, funnel rotation ambience, funnel interior ambience
- Set any custom model
- Implement the ability to set optional color correction effects for when entering/inside the funnel, that have adjustable falloff radiuses (like color_correction point entity) shaped as tubes parallel to the to the central funnel axis. See the illustration.
![funnel](https://user-images.githubusercontent.com/95643875/153773977-9c98c538-c26e-4707-8180-9c24217002cd.png)
- Add optional particle/sprite trail effects for entities inside of the funnel (as in trigger_vphysics_motion), allow other entities to have their trails enabled/disabled on a per entity and or class basis. 

**Additionally:**
- Have an output that can be fired each time an entity enters or exits the funnel, with filtering being handled by a separate entity [as per this suggestion](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/803)
- Set the funnel tube shape (circular, square, triangular, rectangular etc) and XY dimensions/diameter of it.
- [Some other suggestions](https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/790)

### **For: prop_wall_projector**
- Set custom model for the emitter (already available for tractor beams and lasers)
- Set custom vmt replacement for projected_wall.vmt, projected_wall_rail.vmt
- Set custom wall end particles 
- Set custom bridge ambience sound
- Set custom color for the bridge VFX, either both particles and materials, or just the materials

**Additionally:**
- Fire an output when an entity touches the bridge or is standing on it 
- Set bridge height (not thickness)
- Allow users to define how a specific bridge config interacts with other entities:
  - Whether the players are allowed to shoot portals through it or not
  - Whether the bridge is solid to certain entities/entity classes or players or not (allow using a filter entity or a simple set of flags for this?)
  - Whether the bridge is blocking enemy LOS or not
  - Whether the bridge can be painted or not
  - Fire an output or run a script for when an entity passes through/interacts with the bridge in any way based on the previous settings

### **For: env_portal_laser**
- Set custom laser material
- Set custom emitter, redirection cube and endcap particles
- Set custom wall decal (the one that's spawned when the laser hits a surface)
- Set custom laser sounds
- Make endcap spawn two particle systems - one being customizable, the other being set to default P2 sparkles, with the option to turn either of them off (this is mainly needed so that you don't have to add sparkles to your custom particles if you want to have both)
- Replace the UnlitGeneric shader of the laser material with SolidEnergy to be in line with light bridges, funnels and fizzlers and therefore allow for more complex vfx (I'm mentioning it here because I don't know if laser rendering relies on UnlitGeneric specifically for some reason)
- Add other relevant keyvalues from env_beam and env_laser entites, including laser width, alpha amount etc 

**Additionally:**
- Fire outputs for when an entity touches, gets damaged or pushed back by the laser
- Allow to turn off damage completely
- Allow to control the amount of pushback force applied to players
- Allow for entity filtering
- Optionally spawn sprites/particles along the beam

### **For: point_combine_ball_launcher (and potentially for point_combine_ball)**
- Set custom sounds
- Optionally spawn an attached particle system in addition to the existing ball sprite vfx
- Allow disabling the sprite/texture based vfx of the energy ball and leaving only the new particle based one
- Set custom textures
- Set custom hit decal
- Set custom explosion particles
- Add customizable particle effect displayed briefly when hitting a surface
- Set how strongly the ball bounces off of surfaces (unless it's already taken care of by the ball speed parameter)
- Make the pulsing size effect of the energy ball sprite optional
- Add optional color correction effect identical to color_correction point entity that moves with the ball. 

**Additionally:**
- Set color
- Add outputs "OnPlayerContact" for when the ball touches the player, "OnHitSurface", "OnExplosion" and "OnPortalled" (or "OnExiting/EnteringPortal"
- Add "Point_template to spawn on surface hit" and "Point_template to spawn on explosion" functionality
- Add "Point_template to attach" which would spawn a point_template contents and parent them to the ball automatically, and then remove them on ball explosion - this is totally doable with IO, but as anything IO it's prone to be buggy and hacky, which is why I think coding that in would help. Being able to spawn additional entities that move with the ball smoothly without any weird physics bugs would be extremely useful in general. 

On a sidenote, I think ideally the hard coded sprite-like vfx of the ball should be replaced with particles by default due to them having much better customizability and being much easier to understand. 

This is quite a significant list but most of these features would be extremely useful, especially for map makers.

**Comment by Luke18033** [comment]
Please split this into separate issues for the config file itself and each test element. These are really all separate things which will be implemented at different points in time, and combining the issues makes that a pain to manage.

Also note that a lot of the things you suggested for HEPs are already implemented as keyvalues on the entity.

**Comment by luxeleios** [comment]
I've specifically checked all of the entities mentioned here to see what has and hasn't been implemented. The only thing implemented for HEPs that is also mentioned here is the ability to set materials used for the sprites. 
I'll move the config part to a separate issue, but I typed it out here because it's specific to and only really needed for this implementation of customizable entities.

**Comment by ErinRoseWebs** [comment]
i can double check all of my expansion issues and see what i already have in it, and add whats not already there

**Comment by luxeleios** [comment]
I'm going to split this into separate issues tomorrow, no need.

**Comment by ErinRoseWebs** [comment]
oki
