### ISSUE TITLE
Energy Pellet Max Bounces

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#82]
Energy pellet's max bounces doesn't work, only the combine ball entity has it. Also if comes into any surface near a portal it doesn't register as a bounce (probably caused by how portals change physical space around them)

**Comment by SpyceTewan** [comment]
Cool idea, there could be an energy pellet that can bounce like.. 3 times and it gets progressively darker and lower pitched

**Comment by Konclan** [comment]
I needed it for an energy pellet that can't bounce that I was using for a custom element but it wasn't supported

**Comment by SpyceTewan** [comment]
Done
