### ISSUE TITLE
Bug: Fucked up cubemaps

### ISSUE THREAD

**Issue by Godohwar** [ChaosInitiative/Portal-2-Community-Edition#821]
### Describe the bug

When I build cubemaps my map looks like it's on acid
![20220224204001_1](https://user-images.githubusercontent.com/69369873/155645237-2042b5a7-f623-42bd-aeca-15f6ad436a7d.jpg)

### To Reproduce

1. Full compile HDR
2. Build cubemaps
3. wtf

### Operating System

Windows

**Comment by luxeleios** [comment]
I think it's a known bug, it can be avoided but I don't know how exactly. It just goes away sometimes for me.

**Comment by luxeleios** [comment]
If it actually happens.

**Comment by ozxybox** [comment]
Fixed per craftable
