### ISSUE TITLE
Feature: Playtest system

### ISSUE THREAD

**Issue by JJL772** [ChaosInitiative/Portal-2-Community-Edition#822]
### Which component should be improved?

Gameplay

### Describe your suggestion

For closed playtests of campaign maps, provide a system that automatically records and uploads demos of sessions. 

`cl_playtest_enable` determines if the system should be active at all. Defaults to 0. 
In playtest builds of the game, clicking "Begin Playtest" on the main menu should ask the user if it's OK to record+upload a demo of the session to steam. Yes will set `cl_playtest_enable` to 1.

`scripts/playtest_maps.ekv` will be an encrypted keyvalues file that lists the maps in which the playtest system should be allowed for. This is to prevent users from using the playtest system on custom maps and flooding our leaderboards with junk. The playtest system should also be inactive unless the user has the campaign DLC installed, once again, to prevent junk uploads.  

Leaderboard entries should be formatted `playtest_<mapname>` and contain an integer with the number of seconds it took for the user to complete the playtest (time between BeginPlaytest and EndPlaytest). Demos and other relevant files will get attached to the leaderboard entry as UGC. Demos and leaderboard entries will get created on map shutdown, but only if `EndPlaytest` was actually called in one way or another. 

### Input: `BeginPlaytest`
Begin recording of playtest demo and other data
### Input: `EndPlaytest`
Finish recording of playtest demo

### `PlaytestMgr.EndPlaytest()`

**Comment by hexaflexahexagon** [comment]
fyi mmod has plans for something pretty similar to this for testing maps before they get classified as full maps. if that's done whenever this gets worked on it may be useful to reference (though, using replays instead of demos).

**Comment by JJL772** [comment]
I have this implemented on a branch internally, not sure how momentum will approach this sorta thing
