### ISSUE TITLE
Bug: Some overlays don't appear (DX11)

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#829]
### Describe the bug

Some overlays like graffiti in destructed areas don't appear in DX11 mode.

### To Reproduce

Play P2:CE in DX11 mode and open the map sp_a1_intro4 and head into the observation room near where you fall onto the glass and break it.

### Operating System

Windows 10

**Comment by craftablescience** [comment]
![image](https://user-images.githubusercontent.com/26600014/164011224-43c8303c-e84c-49e7-8367-948dd048f5d0.png)
![image](https://user-images.githubusercontent.com/26600014/164011584-4878064a-f161-4760-b8cf-d886e5a77f25.png)

**Comment by Luke18033** [comment]
Isn't this basically just a duplicate then...?

**Comment by craftablescience** [comment]
No, this issue is 99% probably fixed but we don't know if this is the same problem for sure until they show up ingame again

**Comment by JJL772** [comment]
Was this fixed?

**Comment by JJL772** [comment]
Nvm, confirmed it was fixed.
