### ISSUE TITLE
Main menu concept

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#83]
For the main menu, keeping the theme around the perpetual testing initiative, an office of bendies as the background video would fit the mod perfectly. Also the menu music could include those random sounds that the puzzle maker plays when you interact with it as instruments.

Images for reference:
![unknown](https://user-images.githubusercontent.com/16567080/84560121-77d3ce00-ad06-11ea-9fef-87e3e41b7e25.png)
![20190805160716_1](https://user-images.githubusercontent.com/16567080/84560122-7904fb00-ad06-11ea-8977-c4520306bbc1.jpg)

**Comment by SpyceTewan** [comment]
We already have a concept, but what you're suggesting is actually not too far off.

**Comment by SpyceTewan** [comment]
Issues are not for "suggestions of how things maybe could look", but actual tasks that can be ticked off. Marking this as invalid
