### ISSUE TITLE
Bug: Deleting groups crashes Hammer

### ISSUE THREAD

**Issue by Lord-of-Squishe** [ChaosInitiative/Portal-2-Community-Edition#834]
### Describe the bug

When I delete a group without "group ignore" enabled, it crashes Hammer for some reason.  I don't know if anyone else has this issue other than me, however.

### To Reproduce

Just delete a group without "group ignore" turned on

### Operating System

Windows

**Comment by craftablescience** [comment]
This is fixed internally and for Momentum, and there's already an issue for it as well

**Comment by Lord-of-Squishe** [comment]
I searched for an issue and didn't find one, I might have searched the wrong things, sorry

**Comment by craftablescience** [comment]
No worries, I'm fairly sure it was both closed and on the chaos tracker, so really hard to find. It's more our fault for not updating the playtest branch in a while
