### ISSUE TITLE
Bug: Falling through the floor in a Rattmann cave with a portal placed

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#841]
### Describe the bug

The player falls through the floor in this area when a portal is placed.
https://user-images.githubusercontent.com/69723642/161445740-75a6c628-66c2-4128-8b2e-d87c7138a6d6.mp4

### To Reproduce

Go to sp_a2_pull_the_rug and try to replicate in the Rattmann cave what you see in the video.

### Operating System

Windows 10

**Comment by ozxybox** [comment]
Superseded by https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/907
