### ISSUE TITLE
Change dmv_ cvars to a different prefix

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#843]
### Which component should be improved?

Other

### Describe your suggestion

The `dmv_` prefix stands for "Dynamic MoVement", which as discussed about a year ago, is somewhat inaccurate (and I also can't read it without thinking of the Department of Motor Vehicles). I'd suggest instead `pmv_` (Player MoVement), `pm_` (also Player Movement), or just `mv_` (MoVement).

Given how only 5 of these cvars currently exist and pretty much nobody knows about them, I don't think we have to worry too much about breaking backwards compatibility. Better to change this sooner rather than later.

**Comment by Deepfried-Chips** [comment]
"Also I can't read it without thinking Department of Motor Vehicle" that came out of nowhere but I love it

**Comment by JJL772** [comment]
dmv_duckjump being broken is really true to the Department of Motor Vehicles name

**Comment by craftablescience** [comment]
Will be renamed to `mv_*` in next build

**Comment by Luke18033** [comment]
No more Department of Motor Vehicles.

**Comment by Luke18033** [comment]
Fixed...not sure that this really needed testing.
