### ISSUE TITLE
Bug(DX9): Loading screens don't actually show any progress until the level is fully loaded

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#845]
### Describe the bug

On both VGUI and Panorama, loading screens do not show any progress until the level is fully loaded in on DX9.

### To Reproduce

Obvious

### Operating System

Reported on Windows 10

**Comment by Luke18033** [comment]
I haven't noticed this for VGUI, maybe I just wasn't paying attention...?

**Comment by craftablescience** [comment]
Not seeing this issue anymore, odd but not complaining
