### ISSUE TITLE
Bug: weapons don't damage you

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#847]
### Describe the bug

In p2ce weapons given to npcs don't damage you.

### To Reproduce

give a combine soldier a gun.
let him shoot at you.
you take no damage.

### Operating System

any

**Comment by Konclan** [comment]
Probably due to missing the HL2 skill file

**Comment by Luke18033** [comment]
I found that NPCs shooting at you didn't work at all, although I was spawning them from the console instead of placing them in a map. Adding the skill cfg only allowed them to damage you by melee.

**Comment by AWildErin** [comment]
Yeah skill.cfg will fix some problems. I was considering bringing back skill manifest so we can keep hl2 stuff separate and the like. I'll look into this again eventually, got a bit tired of looking into it hence why I unassigned myself. But I'd be happy to take another look and fix bugs relating to the weapons

**Comment by Luke18033** [comment]
Seems to be fixed, the citizens in my test map were able to shoot and kill a combine soldier
