### ISSUE TITLE
Talos Like Laser System

### ISSUE THREAD

**Issue by Konclan** [ChaosInitiative/Portal-2-Community-Edition#85]
A standalone element set that works exactly like the emitters, tripod redirectors, and receivers in the Talos Principle

The first and shortest video I found with them:
https://youtu.be/EWtQTTneNeE

**Comment by SpyceTewan** [comment]
Is this secretly just another way to try and make me play that game?

**Comment by mariovct** [comment]
I don’t see why you’d need the full set I mean, there’s already lasers and receivers. 
But. The Tripods could be used for puzzles, seeing as how Reflections Cubes can only aim on a plane whereas Tripods could aim anywhere.

And Jammers could be interesting, would allow for more variety in Fizzler/Laserfield puzzles.
And would make Turrets a more interesting threat. But then there would be the problem of grabbing the jammer through a Laserfield. Unlike Talos Principal which prevents you from doing that in the first place.

**Comment by Konclan** [comment]
The problem is that in talos there is no laser until the tripod makes a connection to it, also the laser in talos can be blocked unlike in portal. The two lasers just aren’t the same. You could try to implement a tripod that uses the default laser but it wouldn’t be the same as Talos

**Comment by BlightedLight** [comment]
I can't see us implementing gameplay elements from other games. If you want elements like these you can implement them via VScript. I'm closing this issue.

**Comment by Luke18033** [comment]
I was going to mention that. It'd be better to expand VScript to make things like this possible/easier, instead of implementing every possible custom test element in code.
