### ISSUE TITLE
Bug: info_lighting_relative entity missing

### ISSUE THREAD

**Issue by Nanoman2525** [ChaosInitiative/Portal-2-Community-Edition#853]
### Describe the bug

Self explanatory.
![image](https://user-images.githubusercontent.com/75224575/161859618-289d87f6-479e-4ab1-83e8-0530286e6eda.png)

### Issue Map

The issue can occur on any map with the entity compiled in it or if you attempt to create it yourself manually.

### To Reproduce

1. Open any map
2. In the console, type "ent_create info_lighting_relative"
3. Error appears

### Operating System

Tested on Windows 10

**Comment by Nanoman2525** [comment]
The entity itself doesn't actually exist in-game, along with info_lighting. They get destroyed from VBSP so this issue is actually fine.

**Comment by craftablescience** [comment]
Actually it is a real entity and we are missing it according to TeamSpen

**Comment by TeamSpen210** [comment]
Here it is in [SDK 2013](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/baseanimating.cpp#L61) and [ASW](https://github.com/NicolasDe/AlienSwarm/blob/c5a2d3fa853c726d040032ff2c7b90c8ed8d5d84/src/game/server/baseanimating.cpp#L68). Interestingly commented out in the latter. Doesn't seem like the entity is checked for specifically, so actually you can just use `info_target` instead, the only useful feature is it force-transmitting.

**Comment by Trico-Everfire** [comment]
Entity appears to be in the game, as I can ent_create the entity and ent_fire recognizes it as a valid entity.
