### ISSUE TITLE
Bug: Wheatley's flashlight doesn't turn on in the pitch black BTS sequence

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#857]
### Describe the bug

Wheatley's flashlight doesn't turn on in the pitch black BTS sequence even though his spotlight does.
![image](https://user-images.githubusercontent.com/69723642/162040994-e032ff35-ba61-4932-8e63-e10b66af83bd.png)

### Issue Map

sp_a2_bts3

### To Reproduce

Go to sp_a2_bts3 and wait for Wheatley to try and turn on his flashlight.

### Operating System

Windows 10

**Comment by craftablescience** [comment]
Closing in favor of https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/956
