### ISSUE TITLE
Bug: Portal gun viewmodel doesn't appear in "The Fall" as well as after the map

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#858]
### Describe the bug

The portal gun viewmodel doesn't appear while falling in "The Fall" map as well as in the next map.
![image](https://user-images.githubusercontent.com/69723642/162043228-9808363f-1fff-4065-a166-e5c52149109f.png)

### Issue Map

sp_a3_00, sp_a3_01

### To Reproduce

Go to sp_a3_00 and the portal gun viewmodel should not show up.

### Operating System

Windows 10

**Comment by slambo311** [comment]
In my opinion, I think the portal gun should just be disabled entirely in sp_a3_00, since it's pretty useless in there.

**Comment by Luke18033** [comment]
There aren't any portal surfaces, but you can still fire portals, so without the viewmodel visible they'd be coming out of nothing.

**Comment by slambo311** [comment]
Good point. A player_weaponstrip would help with that, though, adding the portal gun in sp_a3_01.

**Comment by slambo311** [comment]
Good point.

**Comment by Smaedd** [comment]
Fixed internally!

**Comment by Deepfried-Chips** [comment]
appears in nightly on both mentioned levels
