### ISSUE TITLE
Bug: Things render behind Wheatley while held (DX11)

### ISSUE THREAD

**Issue by craftablescience** [ChaosInitiative/Portal-2-Community-Edition#859]
### Describe the bug

This one is a bit hard to explain, so here are some pictures.

## Regular held Wheatley:
![image](https://user-images.githubusercontent.com/26600014/162385170-bdd9c8c8-fef6-4344-a496-26741fc62bfa.png)

## Bug:
![image](https://user-images.githubusercontent.com/26600014/162385211-3f85cf0a-81fd-4325-8ad9-3b0a1088a40d.png)

### Issue Map

`sp_a1_wakeup`

### To Reproduce

1. Open map `sp_a1_wakeup`
2. Hold Wheatley behind a prop or brush
3. He renders in front of the prop or brush

### Operating System

Reported on Windows 10

**Comment by AWildErin** [comment]
Isn't this intended tho? I swear it's like that in normal Portal 2?

**Comment by Luke18033** [comment]
This is because picking up cores forces viewmodel grabbing on, it's annoying and I'm not sure why they did it that way

**Comment by AWildErin** [comment]
From Portal 2:
![image](https://user-images.githubusercontent.com/28122025/162385946-ebcb44ed-8898-4981-84d7-909501bfaaf7.png)

**Comment by craftablescience** [comment]
Well that sucks

**Comment by Luke18033** [comment]
We should add a keyvalue on the entity to disable that behavior though.

**Comment by AWildErin** [comment]
Yeah, I do agree we should. I suggest probably making that in a new issue though
