### ISSUE TITLE
Bug: Coop gelocity track stage 3 crashes the game.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#867]
### Describe the bug

As the title suggests, essentially Gelocity track Stage 3 crashes the game before even fully loaded. This crash does not occur with the other 2 gelocity maps or any of the time trial versions.

### Issue Map

https://steamcommunity.com/sharedfiles/filedetails/?id=115869888

BSP zip was too big apparently, wouldn't allow an upload.

### To Reproduce

1. Subscribe to the map mentioned above.
2. Launch the map in P2:CE via splitscreen.
3. Notice that the game immediately crashes before the map is even done loading.

### Operating System

Windows

**Comment by Luke18033** [comment]
Does the singleplayer version also crash? This might just be P2CE Coop being P2CE Coop.

**Comment by FrozenDragon0** [comment]
> Does the singleplayer version also crash? This might just be P2CE Coop being P2CE Coop.

Nope attempting to load the map in singleplayer via changelevel also crashes, and as stated the time trial tracks load completely fine without issue along with the coop tracks 2 and 1.

**Comment by JJL772** [comment]
This issue should've been fixed in dev, can you confirm it's been fixed?

**Comment by Luke18033** [comment]
@FrozenDragon0 Can you test this

**Comment by FrozenDragon0** [comment]
@Luke18033 Will do shortly.

**Comment by FrozenDragon0** [comment]
@Luke18033 Can confirm the map loads on the Nightly branch.

**Comment by AWildErin** [comment]
Closed as it seems fixed as per their response

**Comment by FrozenDragon0** [comment]
@AWildErin What was even causing the map to crash in the first place?

**Comment by AWildErin** [comment]
On `prop_energy_ball` we added the option to add an override material, it ended up being null because it was added by us, maps that used it caused it to be null, and the code didn't anticipate it to be null causing it to crash. Was a really simple fix tbh
