### ISSUE TITLE
Energy pellet set to negative max bounces explodes on the first bounce

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#872]
### Describe the bug

Given the behavior of most other entities and that this is the default, it would be expected to produce a pellet with infinite bounces.

### Issue Map

Any map with a HEP emitter

### To Reproduce

1. Open the map
2. If the pellet launcher entity wasn't specifically set to negative max bounces, change it using AddOutput
3. Fire pellet
4. Pellet explodes upon hitting first wall

### Operating System

Tested on Windows 10

**Comment by Luke18033** [comment]
Fixed...although it now seems to be completely impossible to make an energy ball that explodes on the first hit with a surface. I don't think we can make 0 max bounces do that because it would break backwards compatibility, so instead we might want to revert this change so negative bounces explodes instantly again, but update the FGD to default to 0 max bounces and explain the behavior in the description.

**Comment by AWildErin** [comment]
With this change, it's possible to set it to 1 to explode on the first hit. If you want, we can still revert this change though.

**Comment by Luke18033** [comment]
Did some more testing, seems like the ball never explodes if the surface it hits is an unlinked portal, this works fine.
