### ISSUE TITLE
Feature: Remove Cheat protection from ch_airboat to keep p1 airboat% parity.

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#879]
### Which component should be improved?

Other

### Describe your suggestion

ch_airboat is a command left over in p1 that allows you to spawn an airboat a distance away from the player's current viewing angle, standing near/close to walls allows you to clip this airboat into them. A left over in p1 is that this command is also not cheat protected, and allows you to complete the game using only airboats. In P2CE, who adds p1 parity back by adding back HL2 entities (including the airboat and it's command), but has it cheat protected, unlike portal 1. making Airboat% impossible without sv_cheats. a simple change to allow this to be in parity with p1.

**Comment by CitadelCore** [comment]
Team consensus is this won't be implemented
