### ISSUE TITLE
Real-time scaling for "linked_portal_door"

### ISSUE THREAD

**Issue by Hambrix** [ChaosInitiative/Portal-2-Community-Edition#886]
### Which component should be improved?

Entity

### Describe your suggestion

**Linked_portal_door** entities in Portal 2/P2:CE have a pre-rendered size (scale) in Hammer. 
So the size can't be changed right in game via console or other entities.

Could you add inputs such as **SetScaleX** and **SetScaleY**?

**Comment by Luke18033** [comment]
`SetWidth` and `SetHeight` would make more sense

**Comment by Trico-Everfire** [comment]
I've taken the time to test this, and setwidth and setheight work. (tested via ent_fire).

**Comment by craftablescience** [comment]
thanks!
