### ISSUE TITLE
Feature: Option to Protect Workshop Items from being reverse engineered / decompiled with Encryption

### ISSUE THREAD

**Issue by EllingtonElectrician** [ChaosInitiative/Portal-2-Community-Edition#891]
### Which component should be improved?

Other

### Describe your suggestion

We need a option (that's optional) to Protect Workshop Items with encryption published to the workshop to prevent people from reverse engineering and decompiling them if you make a custom new test element in a map etc and you don't want your idea stolen by anyone else and having them claim the credit of what you created.

**Comment by DrMeepster** [comment]
This is impossible.

**Comment by Luke18033** [comment]
We're not adding DRM to workshop addons, or whatever you're trying to suggest here.
