### ISSUE TITLE
Feature: env_lightmap for (moving) brush entities.

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#893]
### Which component should be improved?

Entity

### Describe your suggestion

env_lightmap would be a point entity that'd allow for a brush to have more than 1 lightmap, having another lightmap at the env_lightmap's location and rotation. you'd assign brush ids to the entity similar to how decals assign brushes to be applied to (this'd allow only the desired brushes to get a lightmap at the env_lightmap rather than every brush entity in the map), the way it'd work is that it'd interpolate the distance between the entity's current lightmap/starting position and the env_lightmap entity, slowly fading between them depending on a distance value. (for performance, if the brush stops moving, it'd stop calculating every frame and apply the current values to it's lightmap.)

**Comment by JJL772** [comment]
I'm thinking this probably won't be implemented considering the amount of effort involved for the payoff. Changes to the rendering pipeline might also make this irrelevant in the future. A workaround until then is to make your map leverage CSM in some way.

**Comment by ozxybox** [comment]
This will not be implemented for the time being.
