### ISSUE TITLE
Bug: Multiplayer players spawn at info_player_start instead of info_coop_spawn

### ISSUE THREAD

**Issue by Nanoman2525** [ChaosInitiative/Portal-2-Community-Edition#901]
### Describe the bug

Self-explanatory...

This is in the most recent nightly build. Despite the issue being super obvious, I didn't hear anyone talk about it yet so I just wanted to make an issue for it.

Happens regardless of player team.

### Issue Map

All maps. 

### To Reproduce

1. Set ConVar **mp_dev_wait_for_other_player** to 0
2. Start a multiplayer game through **map mp_coop_2paints_1bridge**
3. Player spawns at info_player_start

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
Fixed internally!

**Comment by ozxybox** [comment]
This has been fixed in steam release `0.7.5`. Had to do with the game not overriding something, getting confused, and thinking it wasn't in a coop map. This fix also seems to make coop work better overall!
