### ISSUE TITLE
Feature: allow npc_security_camera to have it's model changed via KV

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#902]
### Which component should be improved?

Entity

### Describe your suggestion

npc_security_camera has a in code hardcoded path to the model, requiring you to override the existing model, forcing you to only have 1 camera model. to allow us to set it to any model like prop_dynamic would be optimal.

**Comment by Luke18033** [comment]
Duplicate of #130
