### ISSUE TITLE
Bug: prop_testchamber_sign not showing up in game

### ISSUE THREAD

**Issue by Lord-of-Squishe** [ChaosInitiative/Portal-2-Community-Edition#906]
### Describe the bug

When using the prop_testchamber_sign, the compiled map does not show the sign at all, it just disappears.
I tested this on both DX11 and DX9, it doesn't show up at all, in the same way that dynamic props don't show up if they're a prop_static.  I don't know what's going on and after asking Erin I was told to report it.

Hopefully this is self-explanatory, if there's something else that needs explained I'd be happy to give more detail.

### Issue Map

https://drive.google.com/file/d/1z3_uQbfVj5M035i0_H9Y4KKrqpCkV9Hd/view?usp=sharing

### To Reproduce

Place prop_testchamber_sign in a map and compile it
Run it and see the void where the sign should be (unless it's just on my end)

### Operating System

Windows

**Comment by Trico-Everfire** [comment]
@Lord-of-Squishe the sign is on backwards, yes, it's really dumb but the sign has the same front/back side texture. I suggested a change for this back when Stefan (the creator of the entity) was still working for P2CE and it got denied for whatever reason. flip it over and it should render.

**Comment by Luke18033** [comment]
@Lord-of-Squishe Can you confirm that the sign being backwards is the issue here? The entity works fine on my end.

**Comment by Lord-of-Squishe** [comment]
Yeah it was backwards, I turned it around and it was fixed. I can close this since it’s no longer an issue.
