### ISSUE TITLE
Bug: Falling through floor near portal in sp_a1_intro4

### ISSUE THREAD

**Issue by Klunkyone** [ChaosInitiative/Portal-2-Community-Edition#907]
### Describe the bug

When placing the blue portal in a certain spot on sp_a1_intro4 (and I assume some other maps) you can fall through the floor momentarily as shown in the video.

### Issue Map

sp_a1_intro4

### To Reproduce

Open sp_a1_intro4
Enter the second chamber (which contains 2 buttons)
Find the white surface left of the passageway that leads into the main chamber
Place a portal as close to the passageway as possible
Walk near the portal

https://user-images.githubusercontent.com/80126040/173256138-c0674b00-bdfe-4be5-87f6-829a90b3a133.mp4

l

**Comment by ozxybox** [comment]
Was able to replicate on Portal 1's `testchmb_a_01` as well. It seems to only affect gamemovement, with physics props not falling through the ground.

**Comment by ozxybox** [comment]
Bug is fixed internally! Will be pushed out

**Comment by ozxybox** [comment]
This has been fixed in steam release `0.7.5`. Had to do with an identity matrix being all zeros lol.
