### ISSUE TITLE
Be able to mute prop_dynamic animations

### ISSUE THREAD

**Issue by L89David** [ChaosInitiative/Portal-2-Community-Edition#91]
Basically, add an option to remove the sounds that models can play when animating.
I can't see a purpose to add this, but it could be good in some cases. :p2ce_stuff:

**Comment by Luke18033** [comment]
There's already a `Suppress Animation Sounds` keyvalue that does exactly this.

**Comment by L89David** [comment]
Oh, didn't know about it... It's not even in the VDC tho... Bruh.

**Comment by L89David** [comment]
Yep just checked it, it exists, my bad. Closing it.
