### ISSUE TITLE
Feature: built-in Gameinfo.txt

### ISSUE THREAD

**Issue by maxik34** [ChaosInitiative/Portal-2-Community-Edition#914]
### Which component should be improved?

Other

### Describe your suggestion

When you launch the game, it needs Gameinfo.txt. However, there are cases when something has happened to the file (due to the player's fault, for example) and it is impossible to load it or it does not exist at all. The idea is that if the game can't load the Gameinfo.txt file it will use the default one (built-in). To make it clear that something is wrong with the file, you can print a message about the impossibility of loading the file, and using the standard instead, like this:

![Gameinfo_warning](https://user-images.githubusercontent.com/76464778/174171568-472abf84-cac2-4eab-a384-cb4b6804728e.png)

P. S. perhaps due to this, there will be less of the same questions about the launch error from new players who are not familiar with the Source.

**Comment by AWildErin** [comment]
How exactly would this be useful to "new players who are not familiar with the Source"? Generally, you're not supposed to be editing the base gameinfo for P2CE anyway, if you want to add new content you do so through the custom folder, so there's no instance as to why you should be editing the gameinfo.

Overall, if the end-user sorta screws up the gameinfo, that's on them, that file is not meant to be edited by the user unless they're making a mod with their own gameinfo.

**Comment by JJL772** [comment]
We can certainly improve handling of gameinfo.txt for mods, as it could definitely use improved validation and error handling. As it stands though, I'm not aware of any p2ce users who broke their gameinfo fatally. I've seen this sort-of thing happen for standalone mods, but nobody has broken the base p2ce gameinfo afaik.

**Comment by AWildErin** [comment]
Yeah for sure, error handling and information about whats gone wrong would be better suited imo than a built in gameinfo

**Comment by maxik34** [comment]
Error handling and information about what's gone wrong is really better. I guess I'm giving up on my idea.
