### ISSUE TITLE
hammer new file bug

### ISSUE THREAD

**Issue by koerismo** [ChaosInitiative/Portal-2-Community-Edition#92]
This has annoyed me from time to time. I'm hoping that it is fixable.
When saving a new vmf (creating file for the first time), if the path has any periods, the file is saved in the parent folder instead of the selected folder. (It is also named the first section of the folder before the period)

Example:

`myfolder/mysub.folder/test.vmf`
actually saves as
`myfolder/mysub.vmf`

**Comment by AddMGH** [comment]
I mean, it would probably would be easier to not use any dots in your folder names

**Comment by SpyceTewan** [comment]
Hammer. will. either. be. scrapped. or. remade.

**Comment by Luke18033** [comment]
Fixed
