### ISSUE TITLE
Feature: VGUI improve menu background 

### ISSUE THREAD

**Issue by LilyBorb** [ChaosInitiative/Portal-2-Community-Edition#926]
### Which component should be improved?

UI/UX

### Describe your suggestion

currently mods using old vgui, too my knowledge, don't have an easy way to have multiple menu backgrounds. I'm not sure how it works but I believe the names of maps that change the background are hard coded. I might be wrong about it but any other solution is beyond me. I suggest reworking it to add a file in scripts that can allow you to specify which maps change the menu background in the game and add more than 5.

**Comment by Luke18033** [comment]
We're not adding extra modding features to VGUI, that's what Panorama is for. The map names for this aren't hardcoded anyway, Mel has multiple act menu backgrounds...
