### ISSUE TITLE
Bug: P2:CE game movement differs from Portal 2

### ISSUE THREAD

**Issue by Nanoman2525** [ChaosInitiative/Portal-2-Community-Edition#929]
### Describe the bug

For some reason, I noticed that the walking acceleration ––if that's even the right phrase to describe this–– is different when starting a bunnyhop in P2:CE when compared to Portal 2. With closer examination, the game apparently forces players to move a certain amount of distance _minimum_ before allowing one to stop, making movement input both less accurate and less precise.

Here's what I mean:

https://user-images.githubusercontent.com/75224575/176085669-a34dd575-dd2a-45f5-89e0-b5806259df40.mp4

Notice how in P2:CE, it is easy to land in the exact same spot that a player starts from.
This issue occurs regardless of whether or not one is standing or crouching.

### Issue Map

All maps, sp & mp gamerules

### To Reproduce

1. Open any map.
2. Attempt to barely move with cardinal movement inputs (WASD).
3. The game forces you to move a _minimum_ distance not according to your input.

### Operating System

Tested on Windows 10

**Comment by ozxybox** [comment]
fixed internally!

**Comment by ozxybox** [comment]
This fix is now on steam for version `0.7.5`. This had to do with `mv_acceleration_min`` being set as 200 by default. It now defaults to 0.
