### ISSUE TITLE
Allow for using version control systems like git for hammer

### ISSUE THREAD

**Issue by skyem123** [ChaosInitiative/Portal-2-Community-Edition#93]
IIRC hammer has a thing for integrating with version control, but it is made for perforce. It would be good if it could be made it use something like git.

**Comment by ENDERZOMBI102** [comment]
yeah, hammer has version control, but its broken

**Comment by SpyceTewan** [comment]
Again, hammer will either be scrapped for rebuilt

**Comment by ozxybox** [comment]
VMFs can be tracked in Git. Manifests and instances can be used for collaborative map development.
If you would like to reopen or create future hammer feature requests, please do so here https://github.com/ChaosInitiative/Chaos-Source/
