### ISSUE TITLE
Feature/Bug: serverbrowser.so not compiled for the Linux platform.

### ISSUE THREAD

**Issue by KonradCzerw** [ChaosInitiative/Portal-2-Community-Edition#931]
### Which component should be improved?

Other

### Describe your suggestion

The above mentioned component of source engine (serverbrowser.so/dll) is missing in the Linux build of P2:CE.
With some additional files it allows for relatively functional server browser ingame, similar to the cstrike one.
This works on both P2:CE and stock Portal 2 on Windows.
This module is also missing in the above mentioned stock build of Portal 2, however there is one present for MacOS, thus I assume it should not be hard to add it to the build.

**Comment by AWildErin** [comment]
Not sure if we’re going to be adding this as server browser will be handled by panorama, so this was probably intentional to not ship it and I don’t think that will change

**Comment by craftablescience** [comment]
This was not intentional, it ships with our Windows builds

**Comment by AWildErin** [comment]
Yeah after talking internally we won’t be doing this. We’re going to add the same functionality to panorama and eventually strip this binary from release, aswell as the code that loads it.
