### ISSUE TITLE
Bug: Instant Crash: Unable to load version from steam.inf

### ISSUE THREAD

**Issue by DeliWasTaken** [ChaosInitiative/Portal-2-Community-Edition#939]
### Describe the bug

This bug is known but no issue has been made.

When the game is launched, Engine Error: Unable to load version from steam.inf.

From conversations had in the Discord, the cause is unknown and steam.inf provides no benefit.
From Craftable, the best solution would be:
"refactor the game to not look for that file at all"

### Issue Map

No Map

### To Reproduce

There's no known cause and seemingly starts at random, but once it begins the game has the error at launch.

**Comment by DeliWasTaken** [comment]
Sorry! User error, I made modifications to gameinfo that put a custom folder _above_  "Game p2ce".

**Comment by Luke18033** [comment]
Uh, that's how a custom folder should be set up?

**Comment by DeliWasTaken** [comment]
Not sure what to tell you, it was causing the game to crash on startup. When I fixed it, the crashes stopped and my custom folders still work.
