### ISSUE TITLE
Add WebM support for ingame movies

### ISSUE THREAD

**Issue by cdetn** [ChaosInitiative/Portal-2-Community-Edition#94]
idk if it's already in the version of the CS:GO branch, but it would be a nice alternative to Bink where possible.

**Comment by L89David** [comment]
Panorama works with webm iirc...

**Comment by SpyceTewan** [comment]
Already used webm in my gui 👌

**Comment by Luke18033** [comment]
Would that be able to apply to `logic_playmovie` and `vgui_movie_display` as well?

**Comment by CitadelCore** [comment]
Done
