### ISSUE TITLE
Bug: Cannot place portals on actuated panel 

### ISSUE THREAD

**Issue by ozxybox** [ChaosInitiative/Portal-2-Community-Edition#940]
### Describe the bug

When the wall panel is extended and angled, portals cannot be placed on it. 
![image](https://user-images.githubusercontent.com/24679671/177259570-447d9bda-d8bf-4dbe-bc8d-4b24e91ac00e.png)

### Issue Map

`testchmb_a_14` from Portal 1

### To Reproduce

1. Mount Portal 1 in mounts.kv
2. Run `map testchmb_a_14`
3. Run `god;noclip;setpos 1632 964 1300;ent_fire func_door_rotating`
4. Try firing portals at the rotated panel
5. Tah dah, no portals show up

**Comment by JJL772** [comment]
Known issue fixed by !1225

**Comment by ozxybox** [comment]
Marked as resolved. Left open for now until next release with the fix. Not sure if this issue is a duplicate or not of another. If it is, I'll close it.

**Comment by craftablescience** [comment]
Tested, this is fixed
