### ISSUE TITLE
Bug: Music Slider in Audio Options not set at max even though snd_volume_music is set to 1.0

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#944]
### Describe the bug

Exactly as described in the title.

### Issue Map

None.

### To Reproduce

Go to Options -> Audio and notice that, at least by default, the Music Slider is set to be half of its max setting which is inconsistent if you check snd_volume_music that should be set to 1.0 by default in the Developer Console.

### Operating System

Windows 10

**Comment by AWildErin** [comment]
This was fixed a few months ago, but I forgot to list the github link on the internal pr lmao
