### ISSUE TITLE
Feature: Add refraction built in to the SolidEnergy Shader

### ISSUE THREAD

**Issue by November-N** [ChaosInitiative/Portal-2-Community-Edition#949]
### Which component should be improved?

Render

### Describe your suggestion

This would add in support to have refraction in the SolidEnergy shader (used by fizzlers, light bridges, funnels, etc). This could be extremely useful for fizzlers, excursion funnels, particles, water, etc.

This could be implemented in a way such as:

r_solidenergy_refract (bool, enables or disables the effect globally) 
$refract (bool, enables or disables effect)
$refractamount (float, sets the amount of refraction)
$bluramount (float, sets the intensity of the blur effect used by the refraction
$normalmap (texture, specifies the normal map used)
$bumptransform (vector3, allows for the scaling, rotation, & placement of the normal)

$refract_layer (bool, 0 is 'under' the typical effect; 0 is on top, probably can use a better name)
$refract_mask (texture, adds a mask to the refract effect)

$vortex_refract_intensity (float, sets a scale for the refract near the vortex)
$vortex_refract_blur (float, sets a scale for the blur effect near the vortex)
$vortex_refract_tint (RGB matrix, sets the colour tint of the refract effect near the vortex)
$vortex_refract_texture (texture, alternatively set a completely different normal map for the vortex effect)

This would be in addition to the various other refract parameters i'm too lazy to list. There's also probably a few other completely new parameters that would be useful, but i can't really think of them. (also making translucent materials render through the refract would be very appreciated.
Attached is a video of what this may look like.

https://user-images.githubusercontent.com/100051380/178885072-21313902-dfc3-4bd4-b0e1-546bd96d54ee.mp4

**Comment by JJL772** [comment]
I'm implementing this only for DX11, but only doing it in a simplified manner. The refraction intensity will follow the flowmap, and can be controlled with `$refractscale`. Effect is enabled with `$refract 1` and can be disabled globally using `r_fizzler_refract 0/1`. 

The effect looks nice enough as is, I don't think it needs the rest of the fine-tuned controls- I doubt they'll be used very often. 

https://user-images.githubusercontent.com/19717056/181638256-fe863525-9757-43db-8344-a2f50e3ed711.mp4

**Comment by November-N** [comment]
Yeah that looks really great,

**Comment by verygladen** [comment]
That looks quite amazing! Will this effect be added for the other entities listed in the suggestion or only the fizzler?

**Comment by JJL772** [comment]
Done in next update

**Comment by JJL772** [comment]
> That looks quite amazing! Will this effect be added for the other entities listed in the suggestion or only the fizzler?

Only works when `$flowmap` is specified. You could modify the lightbridge mats and such to use flowmaps though
