### ISSUE TITLE
Feature: CFG option

### ISSUE THREAD

**Issue by emir4169** [ChaosInitiative/Portal-2-Community-Edition#950]
### Which component should be improved?

Gameplay

### Describe your suggestion

There should be a Option for the famous speedrunning glitch, excursion funnel crouch fly glich. that makes the glitch possible.

**Comment by AWildErin** [comment]
All speed run stuff will have cvars for them once they get fixed, so I don’t think we need a separate issue for this

**Comment by emir4169** [comment]
thanks for replying

**Comment by FrozenDragon0** [comment]
And wouldn't this be a duplicate of: https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/259 ?

**Comment by emir4169** [comment]
> 

that ones fixing it, this ones adding a option to unpatch it

**Comment by AWildErin** [comment]
And a cvar was discussed in the issue too
