### ISSUE TITLE
Bug: Underground elevators not working

### ISSUE THREAD

**Issue by Lord-of-Squishe** [ChaosInitiative/Portal-2-Community-Edition#951]
### Describe the bug

When loading into an underground map the elevator doesn't move.

### Issue Map

Any sp_a3 map.

### To Reproduce

Open console
Load into any sp_a3 map
Wait indefinitely

**Comment by AWildErin** [comment]
I can't seem to reproduce this myself, can you give me a map that you can experience it happening on in case it's a map-specific thing?
