### ISSUE TITLE
Bug: All the assets won't load

### ISSUE THREAD

**Issue by nluziaf** [ChaosInitiative/Portal-2-Community-Edition#952]
### Describe the bug

So I run Portal 2 Community Edition, and I see that the assets in triple laser cannot load properly. It has been 3 months I'm living with it and no one knows why
[Logs.txt](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/9126703/Logs.txt)
.

### Issue Map

Every map

### To Reproduce

Nothing, just occurs.

**Comment by nluziaf** [comment]
[console.log](https://github.com/ChaosInitiative/Portal-2-Community-Edition/files/9127054/console.log)
full log

**Comment by craftablescience** [comment]
As discussed in P2:CE discord, this was fixed by reinstalling Portal 2. Since the console provides no information as to what happened I'm going to close this.
