### ISSUE TITLE
vscript player object features

### ISSUE THREAD

**Issue by ENDERZOMBI102** [ChaosInitiative/Portal-2-Community-Edition#96]
the player object ( the one returned by GetPlayer() ) doesn't have much functions, i'd like to  see more functions or properties to it!<br>
also GetPlayer() should be modified to accept a value that gives the n player ( GetPlayer(n) ) but if nothing is provided it defaults to player 0
those are some ideas that i had:
|type|name|description|
|----------|------------|------------|
|function |resetASHPD|reset the player's portals|
|property|pos|return the player's position(x,y,z)|
|function|tp|teleport the player to x y z|
|function|damage(n)|do n damage to the player|
|property|selSlot|return the index of the player's selected inventory slot|
|function|setItemSlot|set the item in a slot|

those are only some ideas, some good and some not : )

**Comment by SpyceTewan** [comment]
Doesn't CBaseEntity already provide position, teleportation and health functions?

And we'll definitely **not** call it ASHPD

**Comment by ENDERZOMBI102** [comment]
Like i said, those are only ideas, not "rules to follow", for the reset function, resetPortals() its good too

**Comment by SpyceTewan** [comment]
Issues are for tasks and not vague ideas
