### ISSUE TITLE
Bug: Rocket Turrets rockets don't do any damage.

### ISSUE THREAD

**Issue by Trico-Everfire** [ChaosInitiative/Portal-2-Community-Edition#967]
### Describe the bug

The Rocket Turrets rockets don't do any damage.

### Issue Map

any (use sp_a2_triple_laser lol)

### To Reproduce

1. open sp_a2_triple_laser
2. spawn rocket turret (ent_create npc_rocket_turret)
3. let it fire at you.
4. take no damage.

**Comment by Trico-Everfire** [comment]
Apparently, you CAN take damage, but it's under very specific circumstances, I had to spawn like 10 rocket turrets and only then took damage.

**Comment by Luke18033** [comment]
Replaced by #1203, cry about it

**Comment by Trico-Everfire** [comment]
*cries about it*
