### ISSUE TITLE
Bug: mp_dev_wait_for_other_player still kicks players in Splitscreen regardless of what it's set to.

### ISSUE THREAD

**Issue by FrozenDragon0** [ChaosInitiative/Portal-2-Community-Edition#968]
### Describe the bug

Whenever mp_dev_wait_for_other_player is set to 0 in a splitscreen session the game will stick kick the player to the main menu after a certain amount of time.

### Issue Map

All coop maps in Splitscreen apart from community hub

### To Reproduce

1. Set mp_dev_wait_for_other_player to 0
2. Load any coop map in Splitscreen.
3. Wait awhile and notice that the game will still kick you regardless of the command's setting above ^^

### Operating System

N.A

**Comment by craftablescience** [comment]
You're not supposed to run this in splitscreen
