### ISSUE TITLE
fix OnFiredPortal2 for weapon_portalgun

### ISSUE THREAD

**Issue by CamBen** [ChaosInitiative/Portal-2-Community-Edition#97]
The output OnFiredPortal1 fires correctly when firing a blue portal from a portal gun; OnFiredPortal2 does not fire at all. This suggestion is just to fix that, so OnFiredPortal2 fires when the gun fires an orange portal.

**Comment by SpyceTewan** [comment]
fixed

**Comment by CamBen** [comment]
poggers

**Comment by SpyceTewan** [comment]
Valve literally just forgot to call the output...
