### ISSUE TITLE
Bug: media webm files fix

### ISSUE THREAD

**Issue by ShygalCoco** [ChaosInitiative/Portal-2-Community-Edition#972]
### Describe the bug

Considering nobody has decided to fix the corrupted media webm files yet, I've decided to make my own and upload them here. Replace the webm files with these in the next update. All made via Bik to WebM HandBrake conversion.

https://mega.nz/file/A09lBIDQ#Cn3LAfeCPBCt0BWNTd31US1F_Got8D12PGs4jmq2RCA

### Issue Map

Any that play webm media.

### To Reproduce

Go to "Portal 2 Community Edition\p2ce\media" and view corrupted files.

### Operating System

Windows 10

**Comment by craftablescience** [comment]
Thank you for the conversions! They're kind of obviously compressed, so I made a converter script and tweaked the ffmpeg inputs a bit to make them look nicer while still keeping file size below current values. That script and the fixed webms should be in the next build hopefully. Thanks for getting me off my butt to fix this lol
