### ISSUE TITLE
Add filters to floor buttons

### ISSUE THREAD

**Issue by NoNameToPut** [ChaosInitiative/Portal-2-Community-Edition#98]
Add filters to floor buttons. This could be useful for a custom floor button only able to be pressed by certain cubes

**Comment by AddMGH** [comment]
Possibly also allow it to specify a type of cube, and then a named cube?

**Comment by NoNameToPut** [comment]
Yes, like trigger filters you can use filter_activator_name, filter_activator_model, or the other filter entities for filtering

**Comment by AddMGH** [comment]
I suppose that would make it `Allow filters to interface with floor buttons like triggers`, then?

**Comment by NoNameToPut** [comment]
Yes

**Comment by Luke18033** [comment]
This is already possible. Floor buttons generate a `trigger_portal_button` entity used for the actual player/cube detection, which you can locate with a VScript and apply filters or change the flags. Having a way to do it directly on the button entity would be nice though.

**Comment by AWildErin** [comment]
Superseded by #873
