### ISSUE TITLE
Missing libssl.so.1.1

### ISSUE THREAD

**Issue by JoshuaFern** [ChaosInitiative/Portal-2-Community-Edition#983]
### Describe the bug

Portal 2 Community Edition won't launch using Steam in a Flatpak, missing libssl.so.1.1:
`/home/jdf/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Portal 2 Community Edition/bin/linux64/crashpad_handler: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Consider bundling this library with the game on Steam.

Workarounds: Copy libssl.so.1.1 from elsewhere or simply run the game using the "Steam Linux Runtime" compatibility tool.

### Issue Map

N/A

### To Reproduce

* Launch the game.

### Operating System

NixOS Linux

**Comment by JJL772** [comment]
The game shouldn't depend on libssl.so.1.1 anymore. Can you let me know if you can run this out of the box now?

**Comment by JoshuaFern** [comment]
@JJL772 Getting further now, tracking the next crash in a new issue.

https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/1036
