### ISSUE TITLE
Panorama access to health, ammo, and weapon switching

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Portal-2-Community-Edition#984]
### Which component should be improved?

UI/UX

### Describe your suggestion

Add the C++ side of the Panorama HUD logic. I'm not super familiar with panorama/web development, so I don't know exactly how the implementation would look, but the following would need to be possible in some way:
- Access to player's health (and suit charge if/when that's supported)
- Access to the player's selected weapon, as well as its current ammo and reserve ammo
- A way to get a list of the player's current weapons, as well as the various info defined in each weapon's script - bucket ID, slot ID, icon, and name
- Ability for the UI to respond to `invnext`, `invprev`, and the various `slot#` commands, as well as change the player's currently equipped weapon (via `use`).

I think that's mainly it?

**Comment by JJL772** [comment]
This is being tracked here https://github.com/ChaosInitiative/p2ce-panorama-ui/issues/42 and here https://github.com/ChaosInitiative/p2ce-panorama-ui/issues/49
