### ISSUE TITLE
'Game Type' Map Property for switching between Portal 1 and Portal 2 Gameplay/Mechanics

### ISSUE THREAD

**Issue by AddMGH** [ChaosInitiative/Portal-2-Community-Edition#99]
In the discord, there's been discussion over having a Portal 1 and a Portal 2 Crosshair being part of the settings, and BEEmod in Vanilla Portal 2 already has the Portal 1 gun with full sounds and animations working, so the ability for a map to have a 'Game Type' map property, 1 being Portal 1, with the gun and crosshair by default and the Portal 1 movement, and 2 being Portal 2, with the Portal 2 movement and the default Portal Gun and everything else. I suppose a naming system like `p2_a1-5_mapnamehere` or `p1_a1-5_mapnamehere` could also be an alternative?

Something such as this;
![image](https://user-images.githubusercontent.com/26350889/84668850-01a8b480-af1c-11ea-807d-ccd7da20f317.png)

**Comment by SpyceTewan** [comment]
I'd rather just have cvars you can set

**Comment by BlightedLight** [comment]
An entity would do well too, would be easier to set in maps, isn't very useful to be able to set in out of maps not made for it anyway, as it will likely break gameplay in certain situations.

**Comment by SpyceTewan** [comment]
I'd much rather have cvars for each individual setting. For example, setting the portalgun viewmodel via command would enable workshop maps to be able to have custom portal guns models.

**Comment by SpyceTewan** [comment]
Splitting these up into individual issues
